using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


//    public class ConceptosUtil
//    {

//        public static List<pCONCEPTO_VIAGUB> ConceptoViaGub(List<vCONCEPTO_VIAGUB> lista)
//        {
//            var q = from i in lista
//                    select new pCONCEPTO_VIAGUB()
//                    {
//                        NUMERO_COMBINADA = i.NUMERO_COMBINADA,
//                        ID_ANALISTA = (i.ID_ANALISTA.HasValue) ? i.ID_ANALISTA.Value : 0,
//                        ID_DOCUMENTO = (i.ID_DOCUMENTO.HasValue) ? i.ID_DOCUMENTO.Value : 0,
//                        TIPO_DE_DOCUMENTO = i.TIPO_DE_DOCUMENTO,
//                        DECISION = i.DECISION,
//                        CODIGO_SIPOD = i.CODIGO_SIPOD,
//                        PROCEDE_APELACION = i.PROCEDE_APELACION,
//                        CAUSAL_1 = i.CAUSAL_1,
//                        CAUSAL_2 = i.CAUSAL_2,
//                        DETALLE_DE_RECURSO = i.DETALLE_DE_RECURSO,
//                        FUNDAMENTOS_DE_DECISION_DE_RECURSO = i.FUNDAMENTOS_DE_DECISION_DE_RECURSO,
//                        RESOLUCION = i.RESOLUCION,
//                        RESOLUCION_RECURSO = i.RESOLUCION_RECURSO,
//                        FECHA_RESPUESTA = (i.FECHA_RESPUESTA.HasValue) ? i.FECHA_RESPUESTA.Value : DateTime.Now,
//                        DIA = i.DIA,
//                        MES = i.MES,
//                        AÑO = i.AÑO,
//                        FECHA_RESOLUCION_NO_INCLUSION = (i.FECHA_RESOLUCION_NO_INCLUSION.HasValue) ? i.FECHA_RESOL_NO_INCLUSION.Value : DateTime.Now,
//                        GENERO = i.GENERO,
//                        RECURRENTE = i.RECURRENTE,
//                        IDENTIFICACION = i.IDENTIFICACION,
//                        DIRECCION = i.DIRECCION,
//                        TELEFONO = i.TELEFONO,
//                        FECHA_DECLARACION = (i.FECHA_DECLARACION.HasValue) ? i.FECHA_DECLARACION.Value : DateTime.Now,
//                        FECHA_DECLARACION_STRING = i.FECHA_DECLARACION_STRING,
//                        FECHA_RADICADO_UT = (i.FECHA_RADICADO_UT.HasValue) ? i.FECHA_RADICADO_UT.Value : DateTime.Now,
//                        FECHA_RADICADO_UT_STRING = i.FECHA_RADICADO_UT_STRING,
//                        FECHA_RADICACION_RECURSO = (i.FECHA_RADICACION_RECURSO.HasValue) ? i.FECHA_RADICACION_RECURSO.Value : DateTime.Now,
//                        FECHA_RADICACION_RECURSO_STRING = i.FECHA_RADICACION_RECURSO_STRING,
//                        FECHA_NOTIFICACION = (i.FECHA_NOTIFICACION.HasValue) ? i.FECHA_NOTIFICACION.Value : DateTime.Now,
//                        FECHA_NOTIFICACION_STRING = i.FECHA_NOTIFICACION_STRING,
//                        MINISTERIO_DECLARACION = i.MINISTERIO_DECLARACION,
//                        MUNICIPIO_DECLARACION = i.MUNICIPIO_DECLARACION,
//                        UT_NOTIFICACION = i.UT_NOTIFICACION,
//                        ENTIDAD_TERRITORIAL_NOTIFICACION = i.ENTIDAD_TERRITORIAL_NOTIFICACION,
//                        MUNICIPIO__DE_NOTIFICACION = i.MUNICIPIO__DE_NOTIFICACION,
//                        LUGAR_DE_NOTIFICACION = i.LUGAR_DE_NOTIFICACION,
//                        LUGAR_DE_NOTIFICACION_II = i.LUGAR_DE_NOTIFICACION_II,
//                        NOTIFICADOR = i.NOTIFICADOR,
//                        CARGO_NOTIFICADOR = i.CARGO_NOTIFICADOR,
//                        ENTIDAD_QUE_NOTIFICA = i.ENTIDAD_QUE_NOTIFICA,
//                        CIUDAD = i.CIUDAD,
//                        UT = i.UT,
//                        UT_3 = i.UT_3,
//                        COORDINADOR_UT = i.COORDINADOR_UT,
//                        TELEFONO_UT = i.TELEFONO_UT,
//                        DIRECCION_UT = i.DIRECCION_UT,
//                        ANALISTA = i.ANALISTA,
//                        FECHDEZPL = i.FECHDEZPL,
//                        FECHA_NOTINOTI = i.FECHA_NOTINOTI,
//                        DIAS_LETRAS = i.DIAS_LETRAS,
//                        DIAS_NUMEROS = i.DIAS_NUMEROS,
//                        OBSERVACIONES = i.OBSERVACIONES,
//                        ID_RECURSO_TUTELA = i.ID_RECURSO_TUTELA,
//                        NUMERO_STICKER = i.NUMERO_STICKER,
//                        TRATO_1 = i.TRATO_1,
//                        TRATO_2 = i.TRATO_2,
//                        TRATO_3 = i.TRATO_3,
//                        TRATO_4 = i.TRATO_4,
//                        TRATO_5 = i.TRATO_5,
//                        TRATO_6 = i.TRATO_6,
//                        TRATO_7 = i.TRATO_7,
//                        TRATO_0 = i.TRATO_0,
//                        Unidad__territorial2 = i.Unidad__territorial2,
//                        FECHA_RESOL_NO_INCLUSION = (i.FECHA_RESOL_NO_INCLUSION.HasValue) ? i.FECHA_RESOL_NO_INCLUSION.Value : DateTime.Now,
//                        FECHA_RESOLUCION_NI = i.FECHA_RESOLUCION_NI,
//                        VALORADOR = i.VALORADOR,
//                        FECHA_RADIC_RECURSO_PER = (i.FECHA_RADIC_RECURSO_PER.HasValue) ? i.FECHA_RADIC_RECURSO_PER.Value : DateTime.Now,
//                        FECHA_RADICACION_RECURSO_PERSONERIA = i.FECHA_RADICACION_RECURSO_PERSONERIA,
//                        FECHA_FALLO_TUTELA = (i.FECHA_FALLO_TUTELA.HasValue) ? i.FECHA_FALLO_TUTELA.Value : DateTime.Now,
//                        FECHA_FALLO_TUTELA_STRING = i.FECHA_FALLO_TUTELA_STRING,
//                        NUMERO_ACCION_TUTELA = i.NUMERO_ACCION_TUTELA,
//                        JUZGADO = i.JUZGADO,
//                        DETALLE_DE_RESUELVE = i.DETALLE_DE_RESUELVE,
//                        LUGAR_DE_NOTIFICACION_DE_LA_UAO = i.LUGAR_DE_NOTIFICACION_DE_LA_UAO,
//                        LUGAR_DE_NOTIFICACION_DE_LA_II_DIR_UAO = i.LUGAR_DE_NOTIFICACION_DE_LA_II_DIR_UAO,
//                        APODERADO = i.APODERADO,
//                        CIUDAD_NOTIFICACION = i.CIUDAD_NOTIFICACION,
//                        TIPO_RECURSO_2 = i.TIPO_RECURSO_2,
//                        FECHA_RESOLUCION_RECURSO = (i.FECHA_RESOLUCION_RECURSO.HasValue) ? i.FECHA_RESOLUCION_RECURSO.Value : DateTime.Now,
//                        FECHA_RESOLUCION_RECURSO_STRING = i.FECHA_RESOLUCION_RECURSO_STRING,
//                        FECHA_REAL_REGISTRO = (i.FECHA_REAL_REGISTRO.HasValue) ? i.FECHA_REAL_REGISTRO.Value : DateTime.Now,
//                        TIPO_DE_ERROR = i.TIPO_DE_ERROR,
//                        Firmado = (i.Firmado.HasValue) ? i.Firmado.Value : false
//                    };
//            return q.ToList();
//        }


//        public static List<pCONCEPTO_VALORACION> ConceptoNoInclu(List<vCONCEPTO_VALORACION> lista)
//        {
//            var q = from i in lista
//                    select new pCONCEPTO_VALORACION()
//                    {
//                        ID_VALORADOR = (i.ID_VALORADOR.HasValue) ? i.ID_VALORADOR.Value : 0,
//                        VALORADOR = i.VALORADOR,
//                        UNIDAD_TERRITORIAL = i.UNIDAD_TERRITORIAL,
//                        ENTIDAD_DECLARACION = i.ENTIDAD_DECLARACION,
//                        DECLARANTE = i.DECLARANTE,
//                        IDENTIFICACION = i.IDENTIFICACION,
//                        DIRECCION_Y_BARRIO = i.DIRECCION_Y_BARRIO,
//                        TELEFONO = i.TELEFONO,
//                        FECHA_DECLARACION = i.FECHA_DECLARACION,
//                        FECHA_RADICADO_UT = i.FECHA_RADICADO_UT,
//                        CODIGO_SIPOD = i.CODIGO_SIPOD,
//                        CODIGO_UT = i.CODIGO_UT,
//                        CIUDAD_CORRESPONDENCIA = i.CIUDAD_CORRESPONDENCIA,
//                        NOMBRE_PERSONERO = i.NOMBRE_PERSONERO,
//                        RESOLUCION = i.RESOLUCION,
//                        DIA = i.DIA,
//                        MES = i.MES,
//                        AÑO = i.AÑO,
//                        GENERO = i.GENERO,
//                        CAUSAL_1 = i.CAUSAL_1,
//                        CAUSAL_2 = i.CAUSAL_2,
//                        MOTIVACION = i.MOTIVACION,
//                        DECISION = i.DECISION,
//                        TIPO_DE_DESPLAZAMIENTO = i.TIPO_DE_DESPLAZAMIENTO,
//                        UAOS = i.UAOS,
//                        FIRMA_CITACION = i.FIRMA_CITACION,
//                        CARGO_CITACION = i.CARGO_CITACION,
//                        COORDINADOR_UT = i.COORDINADOR_UT,
//                        TELEFONO_UT = i.TELEFONO_UT,
//                        DIRECCION_UT = i.DIRECCION_UT,
//                        CIUDAD_UT = i.CIUDAD_UT,
//                        TRATO_1 = i.TRATO_1,
//                        TRATO_2 = i.TRATO_2,
//                        TRATO_3 = i.TRATO_3,
//                        TRATO_4 = i.TRATO_4,
//                        TRATO_5 = i.TRATO_5,
//                        TIPO = i.TIPO,
//                        DECISION_5 = i.DECISION_5,
//                        ENTIDAD_DE_DECLARACION_2 = i.ENTIDAD_DE_DECLARACION_2,
//                        DECISION_2 = i.DECISION_2,
//                        DECISION_3 = i.DECISION_3,
//                        DECISION_4 = i.DECISION_4,
//                        TRATO_6 = i.TRATO_6,
//                        TELÉFONO_RESIDENCIA = i.TELÉFONO_RESIDENCIA,
//                        DIRECCIÓN_RESIDENCIA = i.DIRECCIÓN_RESIDENCIA,
//                        Num_acto_admin = i.num_acto_admin,
//                        ESTADO = i.ESTADO,
//                        FECHA_REGISTRO = (i.FECHA_REGISTRO.HasValue) ? i.FECHA_REGISTRO.Value : DateTime.Now,
//                        NUM_FILA = (i.NUM_FILA.HasValue) ? i.NUM_FILA.Value : 0,
//                        Nom_usuario = i.nom_usuario,
//                        Trato7 = i.trato7,
//                        OBSERVACIONES = i.OBSERVACIONES,
//                        FECHA_REAL_REGISTRO = (i.FECHA_REAL_REGISTRO.HasValue) ? i.FECHA_REAL_REGISTRO.Value : DateTime.Now,
//                        Firmado = (i.Firmado.HasValue) ? i.Firmado.Value : false
//                    };
//            return q.ToList();
//        }

//        public static List<pCONCEPTO_EXTEMPO> ConceptoExtempo(List<vCONCEPTO_EXTEMPO> lista)
//        {
//            var q = from i in lista
//                    select new pCONCEPTO_EXTEMPO()
//                    {
//                        Resolucion = i.Resolucion,
//                        FechaValoracion = (i.FechaValoracion.HasValue) ? i.FechaValoracion.Value : DateTime.MinValue,
//                        FechaValoracionString = i.FechaValoracionString,
//                        Dia = i.Dia,
//                        Mes = i.Mes,
//                        Año = i.Año,
//                        UsuarioId = (i.usuarioId.HasValue) ? i.usuarioId.Value : 0,
//                        ResolucionNI = i.ResolucionNI,
//                        FechaResolucionNI = (i.FechaResolucionNI.HasValue) ? i.FechaResolucionNI.Value : DateTime.Now,
//                        FechaResolucionNIString = i.FechaResolucionNIString,
//                        Recurrente = i.Recurrente,
//                        UtId = (i.utId.HasValue) ? i.utId.Value : 0,
//                        UnidadTerritorial = i.UnidadTerritorial,
//                        Genero = i.Genero,
//                        Direccion = i.Direccion,
//                        Telefono = i.Telefono,
//                        MinisterioId = (i.MinisterioId.HasValue) ? i.MinisterioId.Value : 0,
//                        MinisterioDeclaracion = i.MinisterioDeclaracion,
//                        MunicipioDeclaracion = i.MunicipioDeclaracion,
//                        FechaDeclaracion = (i.FechaDeclaracion.HasValue) ? i.FechaDeclaracion.Value : DateTime.Now,
//                        FechaDeclaracionString = i.FechaDeclaracionString,
//                        FechaRadicadoUt = (i.FechaRadicadoUt.HasValue) ? i.FechaRadicadoUt.Value : DateTime.Now,
//                        FechaRadicadoUtString = i.FechaRadicadoUtString,
//                        Causal1 = i.Causal1,
//                        Causal2 = i.Causal2,
//                        FundamentoDecisionRecurso = i.FundamentoDecisionRecurso,
//                        CodigoSipod = i.CodigoSipod,
//                        Identificacion = i.Identificacion,
//                        Ut3 = i.Ut3,
//                        LugarNotificacion = i.LugarNotificacion,
//                        LugarNotificacionII = i.LugarNotificacionII,
//                        Notificador = i.Notificador,
//                        CargoNotificador = i.CargoNotificador,
//                        IdEntidadNotifica = (i.IdEntidadNotifica.HasValue) ? i.IdEntidadNotifica.Value : 0,
//                        EntidadQueNotifica = i.EntidadQueNotifica,
//                        Ciudad = i.Ciudad,
//                        CoordinadorUt = i.CoordinadorUt,
//                        TelefonoUt = i.TelefonoUt,
//                        DireccionUt = i.DireccionUt,
//                        Analista = i.Analista,
//                        Trato1 = i.Trato1,
//                        Trato2 = i.Trato2,
//                        Trato3 = i.Trato3,
//                        Trato4 = i.Trato4,
//                        Trato5 = i.Trato5,
//                        NumeroCombianda = (i.NumeroCombianda.HasValue) ? i.NumeroCombianda.Value : 0,
//                        FechaRealRegistro = (i.FechaRealRegistro.HasValue)?i.FechaRealRegistro.Value : DateTime.Now,
//                        Firma = i.firma,
//                        UnidadTerritorialMin = i.UnidadTerritorialMin,
//                        Firmado = (i.Firmado.HasValue) ? i.Firmado.Value : false,
//                        FormatoId = (i.FormatoId.HasValue) ? i.FormatoId.Value : 0,
//                        Formato = i.Formato,
//                    };
//            return q.ToList();
//        }
//    }
//}