//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.Infrastructure.Crosscutting.Resources.Dependencias {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Objetos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Objetos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruv.Infrastructure.Crosscutting.Resources.Dependencias.Objetos", typeof(Objetos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcciones.BL.
        /// </summary>
        public static string CorreccionesBusiness {
            get {
                return ResourceManager.GetString("CorreccionesBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcciones.DL.
        /// </summary>
        public static string CorreccionesData {
            get {
                return ResourceManager.GetString("CorreccionesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CriticaN.BL.
        /// </summary>
        public static string CriticaNBusiness {
            get {
                return ResourceManager.GetString("CriticaNBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CriticaN.DL.
        /// </summary>
        public static string CriticaNData {
            get {
                return ResourceManager.GetString("CriticaNData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devolucion.BL.
        /// </summary>
        public static string DevolucionBusiness {
            get {
                return ResourceManager.GetString("DevolucionBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devolucion.DL.
        /// </summary>
        public static string DevolucionData {
            get {
                return ResourceManager.GetString("DevolucionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feriados.BL.
        /// </summary>
        public static string FeriadosBusiness {
            get {
                return ResourceManager.GetString("FeriadosBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feriados.DL.
        /// </summary>
        public static string FeriadosData {
            get {
                return ResourceManager.GetString("FeriadosData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GestionFormulario.BL.
        /// </summary>
        public static string GestionFormularioBusiness {
            get {
                return ResourceManager.GetString("GestionFormularioBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GestionFormulario.DL.
        /// </summary>
        public static string GestionFormularioData {
            get {
                return ResourceManager.GetString("GestionFormularioData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glosas.DL.
        /// </summary>
        public static string GlosasData {
            get {
                return ResourceManager.GetString("GlosasData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiderRadicacion.BL.
        /// </summary>
        public static string LiderRadicacionBusiness {
            get {
                return ResourceManager.GetString("LiderRadicacionBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiderRadicacion.DL.
        /// </summary>
        public static string LiderRadicacionData {
            get {
                return ResourceManager.GetString("LiderRadicacionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiderValoracion.BL.
        /// </summary>
        public static string LiderValoracionBusiness {
            get {
                return ResourceManager.GetString("LiderValoracionBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiderValoracion.DL.
        /// </summary>
        public static string LiderValoracionData {
            get {
                return ResourceManager.GetString("LiderValoracionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificacion.BL.
        /// </summary>
        public static string NotificacionBusiness {
            get {
                return ResourceManager.GetString("NotificacionBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificacion.DL.
        /// </summary>
        public static string NotificacionData {
            get {
                return ResourceManager.GetString("NotificacionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotificacionInterna.BL.
        /// </summary>
        public static string NotificacionInternaBussiness {
            get {
                return ResourceManager.GetString("NotificacionInternaBussiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotificacionInterna.DL.
        /// </summary>
        public static string NotificacionInternaData {
            get {
                return ResourceManager.GetString("NotificacionInternaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orfeo.BL.
        /// </summary>
        public static string OrfeoBusiness {
            get {
                return ResourceManager.GetString("OrfeoBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orfeo.DL.
        /// </summary>
        public static string OrfeoData {
            get {
                return ResourceManager.GetString("OrfeoData", resourceCulture);
            }
        }
    }
}
