//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.Infrastructure.Crosscutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruv.Infrastructure.Crosscutting.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cnBaseDatos.
        /// </summary>
        public static string CadenaConexionODAC {
            get {
                return ResourceManager.GetString("CadenaConexionODAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIFF files (*.tif)|*.tif|PDF files (*.pdf)|*.pdf|JPG files (*.jpg)|*.jpg|Todos los archivos (*.tif;*.pdf;*.jpg)|*.tif;*.pdf;*.jpg.
        /// </summary>
        public static string FiltrosCargasDescargas {
            get {
                return ResourceManager.GetString("FiltrosCargasDescargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RuvObjects.
        /// </summary>
        public static string ObjetoRuv {
            get {
                return ResourceManager.GetString("ObjetoRuv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LogicalNegation.
        /// </summary>
        public static string ParametroNegacionLogica {
            get {
                return ResourceManager.GetString("ParametroNegacionLogica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a set_.
        /// </summary>
        public static string PropiedadSet {
            get {
                return ResourceManager.GetString("PropiedadSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Templates/FormatoConstanciaAtencion.pdf.
        /// </summary>
        public static string RutaFormatoConstanciaAtencion {
            get {
                return ResourceManager.GetString("RutaFormatoConstanciaAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Templates/GENERA_FUD_V2.1.pdf.
        /// </summary>
        public static string RutaTemplatePdf {
            get {
                return ResourceManager.GetString("RutaTemplatePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Templates/GENERA_FUD_CONNACIONALES_V2.1.pdf.
        /// </summary>
        public static string RutaTemplatePdfConnacionales {
            get {
                return ResourceManager.GetString("RutaTemplatePdfConnacionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Templates/GENERA_DEVOLUCION.pdf.
        /// </summary>
        public static string RutaTemplatePdfDevolucion {
            get {
                return ResourceManager.GetString("RutaTemplatePdfDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string RutaTemporalLocal {
            get {
                return ResourceManager.GetString("RutaTemporalLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Templates/Temp.
        /// </summary>
        public static string RutaTemporalServidor {
            get {
                return ResourceManager.GetString("RutaTemporalServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bogotá,
        ///{0}
        ///Señores {1},
        ///{2}
        ///
        ///Cordial saludo,
        ///
        ///
        ///El motivo de la presente es para hacer efectiva la devolución  de la declaración numero {3} tomada en la fecha {4} cuyo declarante es {5} identificado con documento {6} {7} , dicha declaración ha sido devuelta por las siguientes causas:
        ///
        ///{8}
        ///
        ///
        ///
        ///Atentamente,
        ///
        ///
        ///
        /// 
        ///_____________________________________________
        ///Dirección Unidad para la Atención y Reparación integral
        ///a las Victimas..
        /// </summary>
        public static string TextoDevolucion {
            get {
                return ResourceManager.GetString("TextoDevolucion", resourceCulture);
            }
        }
    }
}
