//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.WPF.Captura.RadicacionServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RadicacionServiceReference.IRadicacionService")]
    public interface IRadicacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionService/CargarDatos", ReplyAction="http://tempuri.org/IRadicacionService/CargarDatosResponse")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.LiderRadicacion.clsLiderRadicacion CargarDatos(long nIdDeclaracion, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionService/ActualizarRadicacion", ReplyAction="http://tempuri.org/IRadicacionService/ActualizarRadicacionResponse")]
        bool ActualizarRadicacion(Ruv.Infrastructure.Crosscutting.Common.Entidades.clsRadicacion rad, string cObservaciones, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionService/RadicarDevolucion", ReplyAction="http://tempuri.org/IRadicacionService/RadicarDevolucionResponse")]
        int RadicarDevolucion(Ruv.Infrastructure.Crosscutting.Common.Entidades.clsRadicacion rad, ref string cError);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRadicacionServiceChannel : Ruv.WPF.Captura.RadicacionServiceReference.IRadicacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RadicacionServiceClient : System.ServiceModel.ClientBase<Ruv.WPF.Captura.RadicacionServiceReference.IRadicacionService>, Ruv.WPF.Captura.RadicacionServiceReference.IRadicacionService {
        
        public RadicacionServiceClient() {
        }
        
        public RadicacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RadicacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RadicacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RadicacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.LiderRadicacion.clsLiderRadicacion CargarDatos(long nIdDeclaracion, ref string cError) {
            return base.Channel.CargarDatos(nIdDeclaracion, ref cError);
        }
        
        public bool ActualizarRadicacion(Ruv.Infrastructure.Crosscutting.Common.Entidades.clsRadicacion rad, string cObservaciones, ref string cError) {
            return base.Channel.ActualizarRadicacion(rad, cObservaciones, ref cError);
        }
        
        public int RadicarDevolucion(Ruv.Infrastructure.Crosscutting.Common.Entidades.clsRadicacion rad, ref string cError) {
            return base.Channel.RadicarDevolucion(rad, ref cError);
        }
    }
}
