--MODIFICACION : AUMENTO DEL MAXIMO DE CARACTERES DE 200 A 500  
ALTER TABLE TBBIEN_AFECTADO_A1 MODIFY DESCRIPCION VARCHAR2(500);
--MODIFICACION : AUMENTO DEL MAXIMO DE CARACTERES DE 200 A 500 
ALTER TABLE TBDISCAPACIDADOTRO_PERSONA MODIFY OTRO VARCHAR2(500);

--SE AGREGA NUEVA COLUMNA A LA TABLA PERSONA (NUMERO DE REGISTRO DE DEFUNCION)
alter table TBPERSONAS add NRO_REGDEFUNCION VARCHAR2(50);