//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.WPF.Captura.CriticaNServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CriticaNServiceReference.ICriticaNService")]
    public interface ICriticaNService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriticaNService/ObtenerImagenRadicacion", ReplyAction="http://tempuri.org/ICriticaNService/ObtenerImagenRadicacionResponse")]
        byte[] ObtenerImagenRadicacion(long nId, ref string cNombreImagen, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriticaNService/InsertaCriticaN", ReplyAction="http://tempuri.org/ICriticaNService/InsertaCriticaNResponse")]
        bool InsertaCriticaN(Ruv.Infrastructure.Crosscutting.Common.Entidades.CriticaN.clsRespuestaCritica[] lstRespuesta, ref string cError);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICriticaNServiceChannel : Ruv.WPF.Captura.CriticaNServiceReference.ICriticaNService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CriticaNServiceClient : System.ServiceModel.ClientBase<Ruv.WPF.Captura.CriticaNServiceReference.ICriticaNService>, Ruv.WPF.Captura.CriticaNServiceReference.ICriticaNService {
        
        public CriticaNServiceClient() {
        }
        
        public CriticaNServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CriticaNServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriticaNServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriticaNServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] ObtenerImagenRadicacion(long nId, ref string cNombreImagen, ref string cError) {
            return base.Channel.ObtenerImagenRadicacion(nId, ref cNombreImagen, ref cError);
        }
        
        public bool InsertaCriticaN(Ruv.Infrastructure.Crosscutting.Common.Entidades.CriticaN.clsRespuestaCritica[] lstRespuesta, ref string cError) {
            return base.Channel.InsertaCriticaN(lstRespuesta, ref cError);
        }
    }
}
