//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.WPF.Captura.LoginService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsDefaultFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Ruv.WPF.Server")]
    [System.SerializableAttribute()]
    public partial class clsDefaultFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ruv.Infrastructure.Crosscutting.Common.eCodigoAutenticacion CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ruv.Infrastructure.Crosscutting.Common.eCodigoAutenticacion Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/Authenticate", ReplyAction="http://tempuri.org/ILoginService/AuthenticateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ruv.WPF.Captura.LoginService.clsDefaultFaultContract), Action="http://tempuri.org/ILoginService/AuthenticateclsDefaultFaultContractFault", Name="clsDefaultFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Ruv.WPF.Server")]
        Ruv.Infrastructure.Crosscutting.Common.clsUsuario Authenticate(string cuenta, string contraseña, Ruv.Infrastructure.Crosscutting.Common.clsInterfaseRed ir, string info);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginService/Authenticate", ReplyAction="http://tempuri.org/ILoginService/AuthenticateResponse")]
        System.IAsyncResult BeginAuthenticate(string cuenta, string contraseña, Ruv.Infrastructure.Crosscutting.Common.clsInterfaseRed ir, string info, System.AsyncCallback callback, object asyncState);
        
        Ruv.Infrastructure.Crosscutting.Common.clsUsuario EndAuthenticate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/CerrarSesion", ReplyAction="http://tempuri.org/ILoginService/CerrarSesionResponse")]
        void CerrarSesion(string nombreUsuario, string cuentaUsuario);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginService/CerrarSesion", ReplyAction="http://tempuri.org/ILoginService/CerrarSesionResponse")]
        System.IAsyncResult BeginCerrarSesion(string nombreUsuario, string cuentaUsuario, System.AsyncCallback callback, object asyncState);
        
        void EndCerrarSesion(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : Ruv.WPF.Captura.LoginService.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.clsUsuario Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Ruv.Infrastructure.Crosscutting.Common.clsUsuario)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<Ruv.WPF.Captura.LoginService.ILoginService>, Ruv.WPF.Captura.LoginService.ILoginService {
        
        private BeginOperationDelegate onBeginAuthenticateDelegate;
        
        private EndOperationDelegate onEndAuthenticateDelegate;
        
        private System.Threading.SendOrPostCallback onAuthenticateCompletedDelegate;
        
        private BeginOperationDelegate onBeginCerrarSesionDelegate;
        
        private EndOperationDelegate onEndCerrarSesionDelegate;
        
        private System.Threading.SendOrPostCallback onCerrarSesionCompletedDelegate;
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AuthenticateCompletedEventArgs> AuthenticateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CerrarSesionCompleted;
        
        public Ruv.Infrastructure.Crosscutting.Common.clsUsuario Authenticate(string cuenta, string contraseña, Ruv.Infrastructure.Crosscutting.Common.clsInterfaseRed ir, string info) {
            return base.Channel.Authenticate(cuenta, contraseña, ir, info);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAuthenticate(string cuenta, string contraseña, Ruv.Infrastructure.Crosscutting.Common.clsInterfaseRed ir, string info, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthenticate(cuenta, contraseña, ir, info, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Ruv.Infrastructure.Crosscutting.Common.clsUsuario EndAuthenticate(System.IAsyncResult result) {
            return base.Channel.EndAuthenticate(result);
        }
        
        private System.IAsyncResult OnBeginAuthenticate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cuenta = ((string)(inValues[0]));
            string contraseña = ((string)(inValues[1]));
            Ruv.Infrastructure.Crosscutting.Common.clsInterfaseRed ir = ((Ruv.Infrastructure.Crosscutting.Common.clsInterfaseRed)(inValues[2]));
            string info = ((string)(inValues[3]));
            return this.BeginAuthenticate(cuenta, contraseña, ir, info, callback, asyncState);
        }
        
        private object[] OnEndAuthenticate(System.IAsyncResult result) {
            Ruv.Infrastructure.Crosscutting.Common.clsUsuario retVal = this.EndAuthenticate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthenticateCompleted(object state) {
            if ((this.AuthenticateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthenticateAsync(string cuenta, string contraseña, Ruv.Infrastructure.Crosscutting.Common.clsInterfaseRed ir, string info) {
            this.AuthenticateAsync(cuenta, contraseña, ir, info, null);
        }
        
        public void AuthenticateAsync(string cuenta, string contraseña, Ruv.Infrastructure.Crosscutting.Common.clsInterfaseRed ir, string info, object userState) {
            if ((this.onBeginAuthenticateDelegate == null)) {
                this.onBeginAuthenticateDelegate = new BeginOperationDelegate(this.OnBeginAuthenticate);
            }
            if ((this.onEndAuthenticateDelegate == null)) {
                this.onEndAuthenticateDelegate = new EndOperationDelegate(this.OnEndAuthenticate);
            }
            if ((this.onAuthenticateCompletedDelegate == null)) {
                this.onAuthenticateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateCompleted);
            }
            base.InvokeAsync(this.onBeginAuthenticateDelegate, new object[] {
                        cuenta,
                        contraseña,
                        ir,
                        info}, this.onEndAuthenticateDelegate, this.onAuthenticateCompletedDelegate, userState);
        }
        
        public void CerrarSesion(string nombreUsuario, string cuentaUsuario) {
            base.Channel.CerrarSesion(nombreUsuario, cuentaUsuario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCerrarSesion(string nombreUsuario, string cuentaUsuario, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCerrarSesion(nombreUsuario, cuentaUsuario, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndCerrarSesion(System.IAsyncResult result) {
            base.Channel.EndCerrarSesion(result);
        }
        
        private System.IAsyncResult OnBeginCerrarSesion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string nombreUsuario = ((string)(inValues[0]));
            string cuentaUsuario = ((string)(inValues[1]));
            return this.BeginCerrarSesion(nombreUsuario, cuentaUsuario, callback, asyncState);
        }
        
        private object[] OnEndCerrarSesion(System.IAsyncResult result) {
            this.EndCerrarSesion(result);
            return null;
        }
        
        private void OnCerrarSesionCompleted(object state) {
            if ((this.CerrarSesionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CerrarSesionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CerrarSesionAsync(string nombreUsuario, string cuentaUsuario) {
            this.CerrarSesionAsync(nombreUsuario, cuentaUsuario, null);
        }
        
        public void CerrarSesionAsync(string nombreUsuario, string cuentaUsuario, object userState) {
            if ((this.onBeginCerrarSesionDelegate == null)) {
                this.onBeginCerrarSesionDelegate = new BeginOperationDelegate(this.OnBeginCerrarSesion);
            }
            if ((this.onEndCerrarSesionDelegate == null)) {
                this.onEndCerrarSesionDelegate = new EndOperationDelegate(this.OnEndCerrarSesion);
            }
            if ((this.onCerrarSesionCompletedDelegate == null)) {
                this.onCerrarSesionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCerrarSesionCompleted);
            }
            base.InvokeAsync(this.onBeginCerrarSesionDelegate, new object[] {
                        nombreUsuario,
                        cuentaUsuario}, this.onEndCerrarSesionDelegate, this.onCerrarSesionCompletedDelegate, userState);
        }
    }
}
