-- Create new package
create or replace PACKAGE PKG_NOTIFICACIONINTERNA AS

  TYPE CURSOR_TYPE IS REF CURSOR;
 
  PROCEDURE SP_GENERANOTIFICACION(PI_IDUSUARIOGENERA IN NUMBER,
                                  PI_IDPROCESO       IN NUMBER,
                                  PI_TIPOPROCESO     IN NUMBER,
                                  PI_IDUSUARIORECIBE IN NUMBER,
                                  PI_TEXTO           IN NVARCHAR2,
                                  PI_DESCRIPCION     IN NVARCHAR2);
                                  
  PROCEDURE SP_GENERANOTIFICACIONMULTIPLE(PI_IDUSUARIOGENERA IN NUMBER,
                                          PI_IDPROCESO       IN NUMBER,
                                          PI_TIPOPROCESO     IN NUMBER,
                                          PI_LISTAUSUARIOS   IN NUMBERARRAY,
                                          PI_TEXTO           IN NVARCHAR2,
                                          PI_DESCRIPCION     IN NVARCHAR2);
 
  PROCEDURE SP_OBTENERNOTIUSUARIO(PI_IDUSUARIORECIBE IN NUMBER,
                                  PO_CURSOR OUT CURSOR_TYPE);
 
  PROCEDURE SP_MARCALEIDOS(PI_IDNOTINTERNA IN NUMBER);
 
END  PKG_NOTIFICACIONINTERNA;
/

-- Create package body
create or replace PACKAGE BODY PKG_NOTIFICACIONINTERNA AS

 PROCEDURE SP_GENERANOTIFICACION(PI_IDUSUARIOGENERA IN NUMBER,
                                 PI_IDPROCESO       IN NUMBER,
                                 PI_TIPOPROCESO     IN NUMBER,
                                 PI_IDUSUARIORECIBE   IN NUMBER,                                 
                                 PI_TEXTO           IN NVARCHAR2,
                                 PI_DESCRIPCION     IN NVARCHAR2) AS
 
 BEGIN
 INSERT INTO TBNOTIFICACIONINTERNA VALUES (SEQ_TBNOTIFICACIONINTERNA.NEXTVAL,0,PI_IDUSUARIOGENERA,SYSDATE,PI_IDUSUARIORECIBE,PI_IDPROCESO,PI_TIPOPROCESO,NULL,PI_TEXTO,PI_DESCRIPCION);  
 END;
 
  PROCEDURE SP_GENERANOTIFICACIONMULTIPLE(PI_IDUSUARIOGENERA IN NUMBER,
                                          PI_IDPROCESO       IN NUMBER,
                                          PI_TIPOPROCESO     IN NUMBER,
                                          PI_LISTAUSUARIOS   IN NUMBERARRAY,
                                          PI_TEXTO           IN NVARCHAR2,
                                          PI_DESCRIPCION     IN NVARCHAR2) AS
  BEGIN
    IF PI_LISTAUSUARIOS.Count > 0 THEN
      FOR ix IN PI_LISTAUSUARIOS.First..PI_LISTAUSUARIOS.Last LOOP
        INSERT INTO TBNOTIFICACIONINTERNA
        VALUES (SEQ_TBNOTIFICACIONINTERNA.NEXTVAL,0,PI_IDUSUARIOGENERA,SYSDATE,PI_LISTAUSUARIOS(ix),PI_IDPROCESO,PI_TIPOPROCESO,NULL,PI_TEXTO,PI_DESCRIPCION);  
      END LOOP;
    END IF;
  END;
 
 PROCEDURE SP_OBTENERNOTIUSUARIO(PI_IDUSUARIORECIBE IN NUMBER,
                                 PO_CURSOR OUT CURSOR_TYPE) AS
                                 
 BEGIN
    OPEN PO_CURSOR FOR
      SELECT N.ID,N.FECHAGENERADO,N.TEXTO,N.DESCRIPCION
      FROM TBNOTIFICACIONINTERNA N
      WHERE N.ESTADO = 0 AND N.ID_USUARIORECIBE = PI_IDUSUARIORECIBE;
 END;
 
 PROCEDURE SP_MARCALEIDOS(PI_IDNOTINTERNA IN NUMBER) AS
 
 BEGIN
  UPDATE TBNOTIFICACIONINTERNA SET ESTADO = 1
  WHERE ID = PI_IDNOTINTERNA;
 END;
 
END  PKG_NOTIFICACIONINTERNA;
/