-- Create new package
create or replace PACKAGE PKG_ORFEO AS

USUARIO                   NUMBER:=7;
USUARIODESTINO            NUMBER:=7;
ENTIDAD                   VARCHAR2(50):='UARIV-REGISTRO';
DPTOADMINISTRATIVO        NUMBER:=900; 
DPTOADMINISTRATIVODESTINO NUMBER:=900;

TYPE CURSOR_TYPE IS REF CURSOR;

PROCEDURE SP_GETORFEOPORIDVALORACION(PI_IDVALORACION IN NUMBER,
                                     PO_CURSOR OUT CURSOR_TYPE);
/*	DESCRIPCION: INSERTA UN NUEVO CODIGO ORFEO GENERADO POR EL SERVICIO Y LO RELACIONA
**  A UNA VALORACION DADA
**	AUTOR: JAIRO VALDERRAMA
**	FECHA: 20130211
**	CAMBIOS:
**		FECHA Y NOMBRE DE QUIEN REALIZA EL CAMBIO EN FORMATO (YYYYMMDD - NOMBRE APELLIDO)
**		1. DESCIPCIÓN DE LA MODIFICACION
*/
PROCEDURE SP_RELACIONARVALORACIONORFEO
                (
                  PI_IDVALORACION IN  NUMBER,
                  PI_CCODIGOORFEO IN  VARCHAR2,
                  PO_RESULTADO    OUT NUMBER
                );
                
PROCEDURE SP_GETCODORFEOPORIDVALORACION(PI_IDVALORACION IN NUMBER,
                                        PO_CCODIGOORFEO OUT VARCHAR);
                                     
END PKG_ORFEO;
/

-- Create package body
create or replace PACKAGE BODY PKG_ORFEO AS


    PROCEDURE SP_GETORFEOPORIDVALORACION(PI_IDVALORACION IN NUMBER,
                                         PO_CURSOR OUT CURSOR_TYPE) AS
    
    
    BEGIN
    OPEN PO_CURSOR FOR
    SELECT P.PRIMERNOMBRE,P.PRIMERAPELLIDO,P.SEGUNDOAPELLIDO,P.NUMERODOCUMENTO,RG.DIRECCION AS DIRECCIONPERSONA,RG.DIRECCION AS DIRECCIONCORRESPONDENCIA,
         RG.TELEFONO AS TELEFONOPERSONA,RG.TELEFONO AS TELEFONOCORRESPONDENCIA,DPT.CODIGOCODAZZI AS DEPARTAMENTOCODAZZIPERSONA,MP.CODIGOCODAZZI AS MUNICIPIOCODAZZIPERSONA,
       DPT.CODIGOCODAZZI AS DEPARTAMENTOCODAZZICORREO,MP.CODIGOCODAZZI AS MUNICIPIOCODAZZICORREO,RG.EMAIL,USUARIO AS USUARIO,USUARIODESTINO AS USUARIODESTINO,ENTIDAD AS ENTIDAD,
       DPTOADMINISTRATIVO AS DPTOADMIN,DPTOADMINISTRATIVODESTINO AS DPTOADMINDESTINO,P.PRIMERNOMBRE AS NOMBREDIRECCION
    FROM TBREGISTROS_PERSONAS RG
    INNER JOIN TBGEOGRAFIA DPT ON DPT.ID = RG.ID_DEPARTAMENTO
    INNER JOIN TBGEOGRAFIA MP ON MP.ID = RG.ID_MUNICIPIO
    INNER JOIN TBPERSONAS P ON P.ID = RG.ID_PERSONA
    INNER JOIN TBDECLARACIONES D ON D.ID = RG.ID_DECLARACION
    INNER JOIN TBVALORACION V ON V.ID_DECLARACION = D.ID
    WHERE V.ID = PI_IDVALORACION;
    END;
    
    PROCEDURE SP_RELACIONARVALORACIONORFEO
                (
                  PI_IDVALORACION IN  NUMBER,
                  PI_CCODIGOORFEO IN  VARCHAR2,
                  PO_RESULTADO    OUT NUMBER
                ) AS
    NCONTADOR  NUMBER;
    NIDUSUARIO      NUMBER;
    
    -- EXCEPCIONES
    CODIGOEXISTENTE       EXCEPTION;
    VALORACIONRELACIONADA EXCEPTION;
    BEGIN
      SELECT  COUNT(ID) INTO NCONTADOR
      FROM    TBCODIGOORFEO
      WHERE   NUMERO = PI_CCODIGOORFEO;
      
      IF NCONTADOR > 0 THEN
        RAISE CODIGOEXISTENTE;
      END IF;
      
      SELECT  COUNT(ID) INTO NCONTADOR
      FROM    TBCODIGOORFEO
      WHERE   NIDVALORACION = PI_IDVALORACION;
      
      IF NCONTADOR > 0 THEN
        RAISE VALORACIONRELACIONADA;
      END IF;
      
      SELECT ID_VALORADOR INTO NIDUSUARIO FROM TBVALORACION WHERE ID = PI_IDVALORACION;
      
      PO_RESULTADO := SEQ_TBCODIGOORFEO.NEXTVAL;
      INSERT INTO TBCODIGOORFEO(ID, NUMERO, ID_USUARIOSOLICITANTE, NIDVALORACION)
      VALUES(PO_RESULTADO, PI_CCODIGOORFEO, NIDUSUARIO, PI_IDVALORACION);
    EXCEPTION
      WHEN CODIGOEXISTENTE THEN
        RAISE_APPLICATION_ERROR(-20000, 'El código orfeo que desea insertar ya existe en la BD.');
      WHEN VALORACIONRELACIONADA THEN
        RAISE_APPLICATION_ERROR(-20001, 'El ID de la valoración ingresada ya ha sido relacionada previamente.');
    END;
    
    PROCEDURE SP_GETCODORFEOPORIDVALORACION(PI_IDVALORACION IN NUMBER,
                                            PO_CCODIGOORFEO OUT VARCHAR) AS
    NCONTADOR           NUMBER;
    CODIGONOEXISTENTE   EXCEPTION;
    BEGIN
    
      SELECT  COUNT(ID) INTO NCONTADOR
      FROM    TBCODIGOORFEO
      WHERE   NIDVALORACION = PI_IDVALORACION;
      
      IF NCONTADOR = 0 THEN
        PO_CCODIGOORFEO := '';
        --RAISE CODIGONOEXISTENTE;
      ELSE
        SELECT NUMERO INTO PO_CCODIGOORFEO FROM TBCODIGOORFEO WHERE NIDVALORACION = PI_IDVALORACION;        
      END IF;

    EXCEPTION
      WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20000, 'Ocurrió un error consultando el código orfeo relacionado con la valoración en la BD.');
      
    END;
    
END PKG_ORFEO;
/