-- Create PKG_RADICACION package
create or replace PACKAGE PKG_RADICACION AS

  TYPE CURSOR_TYPE IS REF CURSOR;

  INICIO_CAPTURA_SINRADICAR   NUMBER := 694;
  RADICADO_PENDIENTE_CAPTURA  NUMBER := 704;
  RADICADO_INICIA_CAPTURA     NUMBER := 737;
  RAD_RESP_DEVOL_INI_CAPT     NUMBER := 1689;

  FINALIZA_CAPTURA_SINRADICAR NUMBER := 696;
  PROCESO_FINALIZADO          NUMBER := 703;
  RESTAURACION_FRAUDE_TIPO_1  NUMBER := 5017;

  --Roles
  ROL_DIGITADOR               NUMBER := 90;
  ROL_CRITICA_5               NUMBER := 1011;
  LIDER_RADICADOR             NUMBER := 1012;
  ROL_LIDER_DEVOLUCION        NUMBER := 1013;

  VALORACION_PEND_PORASIGNAR  NUMBER := 702;
  PENDIENTE_POR_VALORAR       NUMBER := 722;
  INICIA_VALORACION           NUMBER := 741;
  VALORACION_FINALIZADA       NUMBER := 777;

  PEND_POR_ASIG_MOD_NORADICA  NUMBER := 766;
  PEND_POR_ASIG_MOD_FIN       NUMBER := 767;
  PEND_POR_ASIG_MOD_NOVALORA  NUMBER := 1677;

  INICIA_MOD_NORADICA         NUMBER := 768;
  INICIA_MOD_FIN              NUMBER := 769;
  INICIA_MOD_PEND_VALORAR     NUMBER := 776;
  INICIA_MOD_NOPEND_VALORAR   NUMBER := 1676;
  DECLARA_GLOSADA             NUMBER := 1678;
  VALORA_GLOSADA              NUMBER := 1679;
  EN_VIA_GUB                  NUMBER := 1690;
  INICIA_CAP_VIAGUB           NUMBER := 955;
  FINALIZA_CAP_VIAGUBER       NUMBER := 956;

  PROCESO_DECLARACION         NUMBER := 547;

  FORMULARIO_RADICADO         NUMBER := 5;
  PEND_RADI_VERI              NUMBER := 10016;
  TIPO_RADICACION_DEVOLUCION  NUMBER := 10013;

  RAD_PENDIENTE_POR_CRITICA_5    NUMBER :=  10015;
  RAD_PENDIENTE_POR_VERIFICAR    NUMBER :=  10016;
  --DEC_PENDIENTE_POR_DEVOLUCION  NUMBER :=  10024;

  VALIDACION_CORRECTA         NUMBER := 10017;

  /* Auto asigna declaraciones a digitador */
  PROCEDURE SP_AUTO_ASIGNAR_PROCESO
  (
    P_ID_RADICACION              IN NUMBER
  );

  /* Guarda el estado del proceso? PENDIENTE QUITAR SI NO SE USA */
  PROCEDURE SP_GUARDAR_ESTADO_PROCESO
  (
    P_ID_ESTADO_PROCESO     IN NUMBER
   ,P_ID_USUARIO            IN NUMBER
   ,P_PARAM_PROCESO         IN NUMBER
   ,P_ID_PROCESO            IN NUMBER
   ,P_ESTADO_FIN            OUT NUMBER
   ,P_ID_DETALLE_RADICACION OUT NUMBER
  );

  /* Inserta la radicacion */
  PROCEDURE SP_SETRADICACION
  (
    P_ID                            IN OUT NUMBER,
    P_ID_MUNICIPIO                  NUMBER,
    P_PARAM_TIPOENTIDAD             NUMBER,
    P_FECHALLEGADA                  DATE,
    P_ID_USUARIO_RADICA             NUMBER,
    P_NRO_FORMULARIO                VARCHAR2,
    P_NRO_ID_TIPO_RADICACION        NUMBER,
    P_OBSERVACIONES                 VARCHAR2,
    P_ID_ENTIDADMUNICIPIO           NUMBER,
    P_ID_DECLARACION                NUMBER,
    P_PARAM_RESULTADO_VALIDACION    NUMBER
  );

  /*  DESCRIPCION: ACTUALIZA LA RADICACION
  **  AUTOR:
  **  FECHA:
  **  CAMBIOS:
  **    20121107 - JAIRO VALDERRAMA
  **    1. SE ACTUALIZA EL NUMERO DE FORMULARIO EN LA DECLARACION EN CASO TAL QUE ESTE SEA
  **    DIFERENTE AL QUE EXISTIA. SE ADICIONA UN NUEVO PARAMETRO (P_PARAM_RESULTADO_VALIDACION)
  **    20121114 - JAIRO VALDERRAMA
  **    1. SE MODIFICAN LOS PARAMETROS ID_MUNUCIPIO, P_PARAM_TIPOENTIDAD, OBSERVACIONES
  **    Y P_ID_ENTIDADMUNICIPIO DE TAL FORMA QUE RECIBAN NULL
  **    20130607 - JAIRO VALDERRAMA
  **    1. SE ELIMINAN EL COMMIT Y EL ROLLBACK CON EL FIN DE PERMITIR LA TRANSACCIONABILIDAD
  **    EN EL SISTEMA
  */
  PROCEDURE SP_UPDRADICACION
   (
    P_ID                            IN OUT NUMBER,
    P_ID_MUNICIPIO                  NUMBER DEFAULT NULL,
    P_PARAM_TIPOENTIDAD             NUMBER DEFAULT NULL,
    P_NRO_FORMULARIO                VARCHAR2,
    P_NRO_ID_TIPO_RADICACION        NUMBER,
    P_OBSERVACIONES                 VARCHAR2 DEFAULT NULL,
    P_RUTAIMAGEN                    VARCHAR2,
    P_ID_ENTIDADMUNICIPIO           NUMBER DEFAULT NULL,
    P_PARAM_RESULTADO_VALIDACION    NUMBER DEFAULT NULL
   );

  PROCEDURE SP_OBTENERRADFROMDECLA
  (
    PI_IDDECLARACION IN NUMBER,
    PO_RADICACION OUT CURSOR_TYPE
  );

  PROCEDURE SP_OBTENERRADFROMNROFORM( PI_NUMEROFORMULARIO IN VARCHAR2,
                                      PI_IDDECLARACION IN NUMBER,
                                      PO_RADICACION OUT CURSOR_TYPE
                                    );

  /*  DESCRIPCION: INSERTA UNA RADICACIï¿½N DE DEVOLUCION
  **  AUTOR:
  **  FECHA:
  **  CAMBIOS:
  **    20121108 - JAIRO VALDERRAMA
  **    1. SE BUSCA EL USUARIO QUE TENIA ASIGNADO PREVIAMENTE LA RADICACION Y SE LE
  **    ASIGNA A ESTE
  **    20121109 - JAIRO VALDERRAMA
  **    1. SE MODIFICA EL PARAMETRO P_OBSERVACIONES DE TAL FORMA QUE RECIBA NULL
  **    2012113 - JAIRO VALDERRAMA
  **    1. SE MODIFICA LA BUSQUEDA DE LA DECLARACION ADICIONANDOLE LA BUSQUEDA DE LA
  **    DEVOLUCION RESPECTIVA
  **    2. SE ELIMINAN LOS ROLLBACK Y EL COMMIT DEL PROCEDIMIENTO
  */
  PROCEDURE SP_INSERTARADICACIONDEV
   (
    PI_FECHALLEGADA                 DATE,
    PI_IDUSUARIO                    NUMBER,
    PI_NUMEROFORMULARIO             VARCHAR2,
    P_OBSERVACIONES                 VARCHAR2 DEFAULT NULL,
    PO_IDRADICACION                 OUT NUMBER
   );

END PKG_RADICACION;
/

-- Create PKG_RADICACION package body
create or replace PACKAGE BODY PKG_RADICACION AS

  /* Auto asigna declaraciones a digitador */
 PROCEDURE SP_AUTO_ASIGNAR_PROCESO
 (
    P_ID_RADICACION              IN NUMBER
 )
 AS
    V_ID                         NUMBER;
    V_ID_USUARIO                 NUMBER;
    RADICADO_PENDIENTE_CAPTURA   NUMBER := 704;
 BEGIN

       SELECT R.id_declaracion
       INTO   V_ID
       FROM   TBRADICACION R
       WHERE  R."ID" = P_ID_RADICACION;

       V_ID_USUARIO := pkg_common.F_USUARIOMENOSCARGA(ROL_DIGITADOR);

       pkg_common.sp_updestado_declaracion(V_ID,V_ID_USUARIO,RADICADO_PENDIENTE_CAPTURA);

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;

 END;

  /* Guarda el estado del proceso? PENDIENTE QUITAR SI NO SE USA */
  PROCEDURE SP_GUARDAR_ESTADO_PROCESO
  (
    P_ID_ESTADO_PROCESO     IN NUMBER
   ,P_ID_USUARIO            IN NUMBER
   ,P_PARAM_PROCESO         IN NUMBER
   ,P_ID_PROCESO            IN NUMBER
   ,P_ESTADO_FIN            OUT NUMBER
   ,P_ID_DETALLE_RADICACION OUT NUMBER
  ) AS
    V_ID              NUMBER;
    V_ID_UTERRITORIAL NUMBER := 0;
    V_ESTADO_INI      NUMBER;
  BEGIN
    P_ID_DETALLE_RADICACION := NULL;

    V_ESTADO_INI := -1;

    IF (P_ID_ESTADO_PROCESO IS NOT NULL) THEN
      SELECT PARAM_ESTADO
        INTO V_ESTADO_INI
        FROM TBESTADOPROCESOS
       WHERE ID = P_ID_ESTADO_PROCESO;
    END IF;

    SELECT ID_UTRERRITORIAL
      INTO V_ID_UTERRITORIAL
      FROM TBUSUARIOS
     WHERE ID = P_ID_USUARIO;

    -- No existe ningun registro en la base de datos

    IF (V_ESTADO_INI = -1) THEN
      SELECT SEQ_ESTADO_PROCESO.NEXTVAL INTO V_ID FROM DUAL;

      INSERT INTO TBESTADOPROCESOS
        (ID,
         ID_USUARIO,
         PARAM_ESTADO,
         FECHAPROCESO,
         PARAM_PROCESO,
         ID_UTERRITORIAL,
         ID_PROCESO)
      VALUES
        (V_ID,
         P_ID_USUARIO,
         INICIO_CAPTURA_SINRADICAR,
         SYSDATE,
         P_PARAM_PROCESO,
         V_ID_UTERRITORIAL,
         P_ID_PROCESO);

      P_ESTADO_FIN := INICIO_CAPTURA_SINRADICAR;
    END IF;

    IF (V_ESTADO_INI = INICIO_CAPTURA_SINRADICAR OR
       V_ESTADO_INI = INICIA_MOD_NORADICA) THEN
      P_ESTADO_FIN := FINALIZA_CAPTURA_SINRADICAR;
      
    ELSIF (V_ESTADO_INI = INICIA_MOD_NOPEND_VALORAR) THEN
      P_ESTADO_FIN := VALORACION_FINALIZADA;

      -- 17-Jan-2011 NAFR: Nuevo estado.
    ELSIF (V_ESTADO_INI = RESTAURACION_FRAUDE_TIPO_1) THEN
      P_ESTADO_FIN := VALORACION_PEND_PORASIGNAR;

    ELSIF (V_ESTADO_INI = RADICADO_PENDIENTE_CAPTURA) THEN
      SELECT ID_DETALLE_RADICACION
        INTO P_ID_DETALLE_RADICACION
        FROM TBESTADOPROCESOS
       WHERE ID = P_ID_ESTADO_PROCESO;

      P_ESTADO_FIN := RADICADO_INICIA_CAPTURA;

      UPDATE TBESTADOPROCESOS
         SET ID_PROCESO = P_ID_PROCESO
       WHERE ID = P_ID_ESTADO_PROCESO;

    ELSIF (V_ESTADO_INI = PENDIENTE_POR_VALORAR) THEN
      P_ESTADO_FIN := INICIA_VALORACION;

    ELSIF (V_ESTADO_INI = INICIA_VALORACION) THEN
      P_ESTADO_FIN := VALORACION_FINALIZADA;

    ELSIF (V_ESTADO_INI = VALORACION_FINALIZADA) THEN
      P_ESTADO_FIN := INICIA_VALORACION;

    ELSIF (V_ESTADO_INI = RADICADO_INICIA_CAPTURA OR
          V_ESTADO_INI = INICIA_MOD_FIN OR
          V_ESTADO_INI = INICIA_MOD_PEND_VALORAR) THEN
      P_ESTADO_FIN := PROCESO_FINALIZADO;

      IF (PROCESO_DECLARACION = P_PARAM_PROCESO) THEN
        P_ESTADO_FIN := VALORACION_PEND_PORASIGNAR;
      END IF;

    ELSIF (V_ESTADO_INI = VALORACION_PEND_PORASIGNAR) THEN
      P_ESTADO_FIN := INICIA_MOD_PEND_VALORAR;

    ELSIF (V_ESTADO_INI = FINALIZA_CAPTURA_SINRADICAR) THEN
      P_ESTADO_FIN := INICIA_MOD_NORADICA;

    ELSIF (V_ESTADO_INI = PROCESO_FINALIZADO) THEN
      P_ESTADO_FIN := INICIA_MOD_FIN;

    END IF;

    IF (V_ESTADO_INI != -1) THEN
      UPDATE TBESTADOPROCESOS
         SET ID_USUARIO      = P_ID_USUARIO,
             ID_UTERRITORIAL = V_ID_UTERRITORIAL,
             PARAM_ESTADO    = P_ESTADO_FIN,
             FECHAPROCESO    = SYSDATE
       WHERE ID = P_ID_ESTADO_PROCESO;
    END IF;

  END;

  /* Inserta la radicacion */
  PROCEDURE SP_SETRADICACION
   (
    P_ID                            IN OUT NUMBER,
    P_ID_MUNICIPIO                  NUMBER,
    P_PARAM_TIPOENTIDAD             NUMBER,
    P_FECHALLEGADA                  DATE,
    P_ID_USUARIO_RADICA             NUMBER,
    P_NRO_FORMULARIO                VARCHAR2,
    P_NRO_ID_TIPO_RADICACION        NUMBER,
    P_OBSERVACIONES                 VARCHAR2,
    P_ID_ENTIDADMUNICIPIO           NUMBER,
    P_ID_DECLARACION                NUMBER,
    P_PARAM_RESULTADO_VALIDACION    NUMBER
   )
   AS
   TOMORROW                                    DATE;
   FechaExcepcion                              EXCEPTION;
   CANTIDAD                                    NUMBER;
   BEGIN
      SELECT SEQ_RADICACION.NEXTVAL INTO P_ID FROM DUAL;
      SELECT to_date(to_char(sysdate,'yyyymmdd'),'yyyymmdd')INTO TOMORROW FROM DUAL;
      SELECT TOMORROW + 1 day INTO TOMORROW FROM DUAL;

      IF P_FECHALLEGADA >= TOMORROW THEN
        RAISE FechaExcepcion;
      END IF;

      INSERT INTO tbradicacion
      (
        "ID",
        fecharegistro,
        id_municipio,
        param_tipoentidad,
        fechallegada,
        id_usuario_radica,
        nro_formulario,
        id_tipo_radicacion,
        observaciones,
        id_entidadmunicipio,
        id_declaracion,
        param_resultado_validacion
      )
      VALUES
      (
        P_ID,
        SYSDATE,
        P_ID_MUNICIPIO,
        P_PARAM_TIPOENTIDAD,
        P_FECHALLEGADA,
        P_ID_USUARIO_RADICA,
        P_NRO_FORMULARIO,
        P_NRO_ID_TIPO_RADICACION,
        P_OBSERVACIONES,
        P_ID_ENTIDADMUNICIPIO,
        p_id_declaracion,
        P_PARAM_RESULTADO_VALIDACION
      );

      SELECT COUNT(1)
      INTO   CANTIDAD
      FROM   tbidentificadorformulario i
      WHERE  i.numeroformulario = P_NRO_FORMULARIO;

      -- El FORMULARIO SOLO SE ACTUALIZA SI PASA TODAS LAS VERIFICACIONES. SE HACE DESDE EL SERVICIO: johnatan.garcia
      /*IF CANTIDAD > 0 THEN
         UPDATE tbidentificadorformulario
         SET    id_estadoidformulario = FORMULARIO_RADICADO
         WHERE  numeroformulario = P_NRO_FORMULARIO;
      END IF;*/

      COMMIT;

    EXCEPTION
    WHEN FechaExcepcion THEN
         dbms_output.put_line('La fecha no puede ser mayor a la fecha actual del sistema.');
         dbms_output.put_line('CUSTOM ERR001: SP_SETRADICACION ERR-FECHAEXCEPCION');
         ROLLBACK;
         RAISE_APPLICATION_ERROR(-20001, 'La fecha no puede ser mayor a la fecha actual del sistema ' || sysdate || '. CODE: SP_SETRADICACION ERR-FECHAEXCEPCION.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
  END;

  PROCEDURE SP_UPDRADICACION
   (
    P_ID                            IN OUT NUMBER,
    P_ID_MUNICIPIO                  NUMBER DEFAULT NULL,
    P_PARAM_TIPOENTIDAD             NUMBER DEFAULT NULL,
    P_NRO_FORMULARIO                VARCHAR2,
    P_NRO_ID_TIPO_RADICACION        NUMBER,
    P_OBSERVACIONES                 VARCHAR2 DEFAULT NULL,
    P_RUTAIMAGEN                    VARCHAR2,
    P_ID_ENTIDADMUNICIPIO           NUMBER DEFAULT NULL,
    P_PARAM_RESULTADO_VALIDACION    NUMBER DEFAULT NULL
   )
   AS

  V_RADICA NUMBER;
  V_ID_DECLARACION NUMBER;
  ID_USUARIOASIGNADO NUMBER;
  CFORMULARIO VARCHAR2(20);
  V_PAISDECLARACION NUMBER;
  V_DPTODECLARACION NUMBER;

   BEGIN
     SELECT D.PADREID INTO V_DPTODECLARACION FROM TBGEOGRAFIA D WHERE D.ID =  P_ID_MUNICIPIO;
      SELECT P.PADREID INTO V_PAISDECLARACION FROM TBGEOGRAFIA P WHERE P.ID =  V_DPTODECLARACION;
      INSERT INTO TBRADICACION_HISTORICO SELECT SEQ_TBRADICAHISTORICO.NEXTVAL,R.ID, R.NRO_FORMULARIO,
      R.ID_ENTIDADMUNICIPIO,R.OBSERVACIONES,SYSDATE,R.ID_USUARIO_RADICA  FROM TBRADICACION R
      WHERE R.ID = P_ID ;

      -- Si el número de formulario cambió, éste debe ser actualizado en la tabla de declaraciones
      SELECT      D.ID, D.NUMEROFORMULARIO INTO V_ID_DECLARACION, CFORMULARIO
      FROM        TBRADICACION R
      INNER JOIN  TBDECLARACIONES D ON D.ID = R.ID_DECLARACION
      WHERE       R.ID = P_ID;

      --En caso de que el numero de formulario sea nulo
      --IF CFORMULARIO IS NULL THEN
      --  CFORMULARIO := '';
      --END IF;

      IF CFORMULARIO <> P_NRO_FORMULARIO OR CFORMULARIO IS NULL THEN
          UPDATE  TBDECLARACIONES
          SET     NUMEROFORMULARIO = P_NRO_FORMULARIO
          WHERE   ID_DETALLERADICACION = P_ID;
      END IF;

      -- SI EL RESULTADO DE LA VALIDACIï¿½N DEL FORMULARIO NO ES NULO, SE EVALï¿½A SU ESTADO Y SE ACTUALIZAN
      -- LAS TABLAS DE RADICACIï¿½N, DECLARACIï¿½N E IDENTIFICADOR FORMULARIO
      IF P_PARAM_RESULTADO_VALIDACION IS NOT NULL THEN
        IF P_PARAM_RESULTADO_VALIDACION = VALIDACION_CORRECTA THEN
          ID_USUARIOASIGNADO := pkg_common.F_USUARIOMENOSCARGA(ROL_CRITICA_5);
          PKG_COMMON.SP_UPDESTADO_DECLARACION(V_ID_DECLARACION, ID_USUARIOASIGNADO, RAD_PENDIENTE_POR_CRITICA_5);

          UPDATE TBIDENTIFICADORFORMULARIO
          SET    ID_ESTADOIDFORMULARIO = FORMULARIO_RADICADO
          WHERE  NUMEROFORMULARIO = P_NRO_FORMULARIO;
        ELSE
          ID_USUARIOASIGNADO := pkg_common.F_USUARIOMENOSCARGA(LIDER_RADICADOR);
          PKG_COMMON.SP_UPDESTADO_DECLARACION(V_ID_DECLARACION, ID_USUARIOASIGNADO, RAD_PENDIENTE_POR_VERIFICAR);
        END IF;
      END IF;

      -- SI ES UNA DEVOLUCION NO SE DEBE ACTUALIZAR NI EL MUNICIPIO NI LA ENTIDAD
      IF P_NRO_ID_TIPO_RADICACION = TIPO_RADICACION_DEVOLUCION THEN
        UPDATE tbradicacion SET
          nro_formulario = P_NRO_FORMULARIO,
          id_tipo_radicacion = P_NRO_ID_TIPO_RADICACION,
          observaciones = P_OBSERVACIONES,
          rutaimagen = P_RUTAIMAGEN
        WHERE ID = P_ID;
      ELSE
        UPDATE tbradicacion SET
          id_municipio = P_ID_MUNICIPIO,
          param_tipoentidad = P_PARAM_TIPOENTIDAD,
          nro_formulario = P_NRO_FORMULARIO,
          id_tipo_radicacion = P_NRO_ID_TIPO_RADICACION,
          observaciones = P_OBSERVACIONES,
          rutaimagen = P_RUTAIMAGEN,
          id_entidadmunicipio = P_ID_ENTIDADMUNICIPIO
        WHERE ID = P_ID;
        UPDATE TBDECLARACIONES SET
          ID_PAISDECLARACION = V_PAISDECLARACION,
          ID_MUNICIPIODECLARACION = P_ID_MUNICIPIO,
          ID_DEPARTAMENTODECLARACION = V_DPTODECLARACION,
          ID_ENTIDADMUNICIPIODECLARACION = P_ID_ENTIDADMUNICIPIO
        WHERE ID = V_ID_DECLARACION;
      END IF; 

    EXCEPTION
    WHEN OTHERS THEN
        RAISE;
  END;

  /* OBTIENE LOS DATOS DE RADICACION Y DE DECLARACION A PARTIR DE UN ID_DECLARACION*/
  PROCEDURE SP_OBTENERRADFROMDECLA( PI_IDDECLARACION IN NUMBER,
                                    PO_RADICACION OUT CURSOR_TYPE
                                  ) IS

  NROFORM VARCHAR2(15);

  BEGIN
  OPEN  PO_RADICACION FOR
    SELECT  R.ID,
            R.FECHALLEGADA,
            R.NRO_FORMULARIO,
            R.ID_ENTIDADMUNICIPIO,
            R.ID_TIPO_RADICACION,
            R.PARAM_RESULTADO_VALIDACION,
            R.RUTAIMAGEN,
            R.OBSERVACIONES,
            PA.PRIMERNOMBRE,
            PA.SEGUNDONOMBRE,
            PA.PRIMERAPELLIDO,
            PA.SEGUNDOAPELLIDO,
            PA.PARAM_TIPODOCUMENTO,
            PA.NUMERODOCUMENTO
    FROM    TBRADICACION R
    INNER JOIN TBDECLARACIONES D ON R.ID_DECLARACION = D.ID
    INNER JOIN TBREGISTROS_PERSONAS RPA ON RPA.ID_DECLARACION = D."ID"
    INNER JOIN TBPERSONAS PA on PA."ID" = RPA.ID_PERSONA
    WHERE D.ID = PI_IDDECLARACION AND RPA.ESDECLARANTE = 1;

  END;

  /* OBTIENE LOS DATOS DE RADICACION Y DE DECLARACION A PARTIR DE UN NUMERO_FORMULARIO*/
  PROCEDURE SP_OBTENERRADFROMNROFORM( PI_NUMEROFORMULARIO IN VARCHAR2,
                                      PI_IDDECLARACION IN NUMBER,
                                      PO_RADICACION OUT CURSOR_TYPE
                                    ) IS
   NROFORM VARCHAR2(15);
  BEGIN

  SELECT RP.NRO_FORMULARIO INTO NROFORM FROM TBRADICACION RP WHERE RP.ID_DECLARACION = PI_IDDECLARACION;

  OPEN  PO_RADICACION FOR
    SELECT R.ID,
            R.FECHALLEGADA,
            R.NRO_FORMULARIO,
            R.ID_ENTIDADMUNICIPIO,
            R.ID_TIPO_RADICACION,
            R.PARAM_RESULTADO_VALIDACION,
            R.RUTAIMAGEN,
            R.OBSERVACIONES,
            PA.PRIMERNOMBRE,
            PA.SEGUNDONOMBRE,
            PA.PRIMERAPELLIDO,
            PA.SEGUNDOAPELLIDO,
            PA.PARAM_TIPODOCUMENTO,
            PA.NUMERODOCUMENTO
    FROM TBRADICACION R
    INNER JOIN TBDECLARACIONES D ON R.ID_DECLARACION = D.ID
    INNER JOIN TBREGISTROS_PERSONAS RPA ON RPA.ID_DECLARACION = D."ID"
    INNER JOIN TBPERSONAS PA ON PA."ID" = RPA.ID_PERSONA
    WHERE D.ID <> PI_IDDECLARACION AND RPA.ESDECLARANTE = 1 AND R.NRO_FORMULARIO = NROFORM;
  END;

  /* Inserta la radicacion */
  PROCEDURE SP_INSERTARADICACIONDEV
   (
    PI_FECHALLEGADA                 DATE,
    PI_IDUSUARIO                    NUMBER,
    PI_NUMEROFORMULARIO             VARCHAR2,
    P_OBSERVACIONES                 VARCHAR2 DEFAULT NULL,
    PO_IDRADICACION                 OUT NUMBER
   )
   AS
   TOMORROW                         DATE;
   FECHAEXCEPCION                   EXCEPTION;
   NOEXISTEDEVEXCEPCION             EXCEPTION;
   CANTIDAD                         NUMBER;
   V_ID_DECLARACION                 NUMBER;
   V_MAXID_DECLARACION              NUMBER;
   V_ESTADODECLANTERIOR             NUMBER;
   V_ID_USUARIO                     NUMBER;
   V_ID_VALORACION                  number := 0;
   V_ID_ENTIDADMUNICIPIO            TBRADICACION.ID_ENTIDADMUNICIPIO%TYPE;
   V_PARAM_TIPOENTIDAD              TBRADICACION.PARAM_TIPOENTIDAD%TYPE;
   V_ID_MUNICIPIO                   TBRADICACION.ID_MUNICIPIO%TYPE;
   BEGIN
      SELECT SEQ_RADICACION.NEXTVAL INTO PO_IDRADICACION FROM DUAL;
      SELECT to_date(to_char(sysdate,'yyyymmdd'),'yyyymmdd')INTO TOMORROW FROM DUAL;
      SELECT TOMORROW + 1 day INTO TOMORROW FROM DUAL;

      IF PI_FECHALLEGADA >= TOMORROW THEN
        RAISE FECHAEXCEPCION;
      END IF;

      --Busca la declaración
      SELECT      DC.ID
      INTO        V_ID_DECLARACION
      FROM        TBDECLARACIONES DC
      INNER JOIN  TBDEVOLUCION DV ON DV.ID_DECLARACION = DC.ID
      WHERE       DC.NUMEROFORMULARIO = PI_NUMEROFORMULARIO
          AND     ROWNUM = 1;

      IF (V_ID_DECLARACION = NULL) THEN
        RAISE NOEXISTEDEVEXCEPCION;
      END IF;

      -- SON SELECCIONADOS LOS PRINCIPALES DATOS DE LA ULTIMA RADICACION PARA SER
      -- INSERTADOS EN LA DE LA DEVOLUCION
      SELECT      R.ID_ENTIDADMUNICIPIO,
                  R.PARAM_TIPOENTIDAD,
                  R.ID_MUNICIPIO
      INTO        V_ID_ENTIDADMUNICIPIO,
                  V_PARAM_TIPOENTIDAD,
                  V_ID_MUNICIPIO
      FROM        TBDECLARACIONES D
      INNER JOIN  TBRADICACION R ON R.ID_DECLARACION = D.ID
      INNER JOIN  (
                    SELECT      MAX(R.FECHAREGISTRO) FECHAREGISTRO, R.ID_DECLARACION
                    FROM        TBRADICACION R
                    WHERE       R.ID_DECLARACION = V_ID_DECLARACION
                    GROUP BY    R.ID_DECLARACION
                  ) RD ON RD.FECHAREGISTRO = R.FECHAREGISTRO
      WHERE       D.ID = V_ID_DECLARACION;


      INSERT INTO tbradicacion
      (
        "ID",
        fecharegistro,
        fechallegada,
        id_usuario_radica,
        nro_formulario,
        id_declaracion,
        id_tipo_radicacion,
        observaciones,
        ID_ENTIDADMUNICIPIO,
        PARAM_TIPOENTIDAD,
        ID_MUNICIPIO,
        PARAM_RESULTADO_VALIDACION
      )
      VALUES
      (
        PO_IDRADICACION,
        SYSDATE,
        PI_FECHALLEGADA,
        PI_IDUSUARIO,
        PI_NUMEROFORMULARIO,
        V_ID_DECLARACION,
        TIPO_RADICACION_DEVOLUCION,
        P_OBSERVACIONES,
        V_ID_ENTIDADMUNICIPIO,
        V_PARAM_TIPOENTIDAD,
        V_ID_MUNICIPIO,
        VALIDACION_CORRECTA
      );

      SELECT COUNT(1)
      INTO   CANTIDAD
      FROM   TBIDENTIFICADORFORMULARIO I
      WHERE  I.NUMEROFORMULARIO = PI_NUMEROFORMULARIO;

      IF CANTIDAD > 0 THEN
         UPDATE tbidentificadorformulario
         SET    id_estadoidformulario = FORMULARIO_RADICADO
         WHERE  numeroformulario = PI_NUMEROFORMULARIO;
      END IF;

      --Busca el estado y el usuario que realizó la devolución de la declaración
      SELECT ESTADODECLANTERIOR, ID_USUARIOSOLICITANTE
      INTO V_ESTADODECLANTERIOR, V_ID_USUARIO
      FROM TBDEVOLUCION
      WHERE ID = (SELECT MAX(ID) FROM TBDEVOLUCION WHERE ID_DECLARACION = V_ID_DECLARACION);

      IF (V_ID_USUARIO IS NOT NULL) THEN

             IF V_ESTADODECLANTERIOR = 10001 then
                      PKG_VALORACION.SP_ASIGNARVALORACION(V_ID_VALORACION,V_ID_DECLARACION,2,V_ID_USUARIO,null);
                      PKG_COMMON.SP_UPDESTADO_DECLARACION(V_ID_DECLARACION, V_ID_USUARIO, V_ESTADODECLANTERIOR);
             ELSIF   V_ESTADODECLANTERIOR = 10000 then
                     PKG_VALORACION.SP_ASIGNARVALORACION(V_ID_VALORACION,V_ID_DECLARACION,1,V_ID_USUARIO,null);
                     PKG_COMMON.SP_UPDESTADO_DECLARACION(V_ID_DECLARACION, V_ID_USUARIO, V_ESTADODECLANTERIOR);
             ELSE
                 PKG_COMMON.SP_UPDESTADO_DECLARACION(V_ID_DECLARACION, V_ID_USUARIO, V_ESTADODECLANTERIOR);
             END IF;
      END IF;


    EXCEPTION
    WHEN FECHAEXCEPCION THEN
         DBMS_OUTPUT.PUT_LINE('La fecha no puede ser mayor a la fecha actual del sistema.');
         DBMS_OUTPUT.PUT_LINE('CUSTOM ERR001: SP_SETRADICACION ERR-FECHAEXCEPCION');
         RAISE_APPLICATION_ERROR(-20001, 'La fecha no puede ser mayor a la fecha actual del sistema ' || SYSDATE || '. CODE: SP_SETRADICACION ERR-FECHAEXCEPCION.');
    WHEN NOEXISTEDEVEXCEPCION THEN
         RAISE_APPLICATION_ERROR(-20001, 'No se encontrï¿½ una devoluciï¿½n relacionada con el nï¿½mero de formulario');
    WHEN OTHERS THEN
        RAISE;
  END;

END PKG_RADICACION;
/