-- Create new package
create or replace PACKAGE PKG_CORRECCIONES AS

  TYPE CURSOR_TYPE IS REF CURSOR;


  PRIMERNOMBRE      NUMBER := 1;
  SEGUNDONOMBRE     NUMBER := 2;
  PRIMERAPELLIDO    NUMBER := 3;
  SEGUNDOAPELLIDO   NUMBER := 4;
  TIPODOCUMENTO     NUMBER := 5;
  DOCUMENTO         NUMBER := 6;
  FECHANACIMIENTO   NUMBER := 7;
  GENERO            NUMBER := 8;
  ETNIA             NUMBER := 9;
  DISCAPACIDADES    NUMBER := 10;
  DIRECCION         NUMBER := 11;
  TELEFONO          NUMBER := 12;
  CORREOELECTRONICO NUMBER := 13;
  SUBETNIA          NUMBER := 14;

  PENDIENTE NUMBER := 2;
  APROBADO NUMBER := 3;
  FIRMADO NUMBER := 4;
  RECHAZADO NUMBER := 5;
  
  ROL NUMBER := 1018;

  TYPE NumberVarray IS VARRAY(100) OF NUMBER;

  PROCEDURE SP_OBTENERINFOCORRECCION (PI_IDCORRECCION IN NUMBER,
                                      PO_CURSOR OUT CURSOR_TYPE);
  
  
  PROCEDURE SP_CARGADATOSCORREGIR(PI_IDREGPERSONA IN NUMBER,
                                  PO_CURSOR OUT CURSOR_TYPE
                                 );

  /*	DESCRIPCION: REALIZA LA SOLICITUD DE LA CORRECCION
  **	AUTOR: DIEGO DUARTE
  **	FECHA: 20121205
  */
  PROCEDURE SP_SOLICITARCORRECCION(PI_IDREGPERSONA IN NUMBER,
                                   PI_IDUSUARIOSOLICITUD IN NUMBER,
                                   PI_CAMPOSCORRECCIONES IN VARCHAR,
                                   PI_VALORESCORRECCIONES IN VARCHAR,
                                   PO_IDCORRECCION OUT NUMBER
                                  );
  
  /*	DESCRIPCION: REALIZA EL CONTEO DE DATOS QUE SE TRAEN EN LA CONSULTA DE PERSONAS
  **	AUTOR: JAIRO VALDERRAMA
  **	FECHA: 20121206
  **	CAMBIOS:
  **		FECHA Y NOMBRE DE QUIEN REALIZA EL CAMBIO EN FORMATO (YYYYMMDD - NOMBRE APELLIDO)
  **		1. DESCIPCIÓN DE LA MODIFICACION
  */
  PROCEDURE SP_BUSCAPERSONASCOUNT(PI_NUMEROFORMULARIO IN VARCHAR2,
                                       PI_PRIMERNOMBRE     IN VARCHAR2,
                                       PI_PRIMERAPELLIDO   IN VARCHAR2,
                                       PI_NUMERODOCUMENTO  IN VARCHAR2,
                                       PO_RECORDCOUNT      OUT NUMBER
                                       );
                                  
  /*	DESCRIPCION: BUSCA PERSONAS CON LA INFO. BASICA DE LA DECLARACION EN LA QUE
  **    SE ENCUENTRA.
  **	AUTOR: JAIRO VALDERRAMA
  **	FECHA: 20121206
  **	CAMBIOS:
  **		FECHA Y NOMBRE DE QUIEN REALIZA EL CAMBIO EN FORMATO (YYYYMMDD - NOMBRE APELLIDO)
  **		1. DESCIPCIÓN DE LA MODIFICACION
  */
  PROCEDURE SP_BUSCAPERSONAS(PI_NUMEROFORMULARIO IN VARCHAR2,
                                  PI_PRIMERNOMBRE     IN VARCHAR2,
                                  PI_PRIMERAPELLIDO   IN VARCHAR2,
                                  PI_NUMERODOCUMENTO  IN VARCHAR2,
                                  PI_PAGENUMBER       IN NUMBER,
                                  PI_PAGESIZE         IN NUMBER,
                                  PO_CURSOR           OUT CURSOR_TYPE
                                  );

  /*	DESCRIPCION: OBTIENE LA INFORMACION DE UNA CORRECCION
  **	AUTOR: DIEGO DUARTE
  **	FECHA: 20121205
  */
  PROCEDURE SP_CONSULTARCORRECCION(PI_IDCORRECCION IN NUMBER,
                                   PO_CURSOR OUT CURSOR_TYPE
                                  );

  /*	DESCRIPCION: RECHAZA UNA CORRECCION
  **	AUTOR: DIEGO DUARTE
  **	FECHA: 20121206
  */
  PROCEDURE SP_RECHAZARCORRECCION(PI_IDCORRECCION IN NUMBER,
                                   PI_IDUSUARIORECHAZA IN NUMBER,
                                   PI_OBSERVACION in VARCHAR
                                  );

  /*	DESCRIPCION: OBTIENE LOS CAMPOS MODIFICADOS EN UNA CORRECCION
  **	AUTOR: DIEGO DUARTE
  **	FECHA: 20121210
  */
  PROCEDURE SP_CONSULTARCAMPOSCORRECCION(PI_IDCORRECCION IN NUMBER,
                                         PO_CURSOR OUT CURSOR_TYPE
                                        );

  /*	DESCRIPCION: OBTIENE EL VALOR ACTUAL DE UN CAMPO PARA EL REGISTRO_PERSONA
  **	AUTOR: DIEGO DUARTE
  **	FECHA: 20121205
  */
  FUNCTION OBTENERVALORANTERIOR(PI_ID_REGPERSONA IN NUMBER, 
                                PI_CAMPO IN NUMBER
                               ) RETURN VARCHAR2;
                               
  /*	DESCRIPCION: OBTIENE EL VALOR NUEVO DE UN CAMPO PARA UNA CORRECCION
  **	AUTOR: DIEGO DUARTE
  **	FECHA: 20121206
  */              
  FUNCTION OBTENERVALORCORRECCION(PI_IDCORRECCION IN NUMBER, 
                                  PI_CAMPO IN NUMBER
                                 ) RETURN VARCHAR2;
                                 
                                 
 PROCEDURE SP_APROBARSOLICITUD(PI_IDCORRECCION IN NUMBER);
 
 FUNCTION F_USUARIOMENOSCARGACORRECCION( P_Rol NUMBER )RETURN NUMBER;

 /*Purpose : Obtiene el nombre de la Subetnia 
   Author  : John Henao
   Fecha   : 12/06/2013
 */

 PROCEDURE SP_OBTENERNOMBRESUBETNIA(P_ID IN NUMBER,
                                    PO_NombreSubEtnia OUT NVARCHAR2);

END PKG_CORRECCIONES;
/

-- Create package body
create or replace PACKAGE BODY PKG_CORRECCIONES AS

  PROCEDURE SP_OBTENERINFOCORRECCION (PI_IDCORRECCION IN NUMBER,
                                      PO_CURSOR OUT CURSOR_TYPE)AS

  BEGIN
   OPEN PO_CURSOR FOR
   SELECT CR.ID,
          CR.ID_REGPERSONA,
          CR.ID_USUARIOSOLICITUD,
          CR.ID_USUARIO,
          CR.FECHASOLICITUD,
          CR.OBSERVACIONES,
          CR.ESTADO
   FROM TBCORRECCION CR
   WHERE CR.ID = PI_IDCORRECCION;
  END;

  PROCEDURE SP_CARGADATOSCORREGIR(PI_IDREGPERSONA IN NUMBER,
                                  PO_CURSOR OUT CURSOR_TYPE
                                 ) IS

    V_DISCAPACIDAD VARCHAR2(300);
    VLIST PKG_SERIALIZATION.NUMBERVARRAY;
  BEGIN
    SELECT PARAM_DISCAPACIDAD BULK COLLECT INTO VLIST
    FROM TBDISCAPACIDAD_PERSONA WHERE ID_REGPERSONA = PI_IDREGPERSONA;
    V_DISCAPACIDAD := PKG_SERIALIZATION.Serialize(VLIST);

    OPEN PO_CURSOR FOR
      SELECT P.PRIMERNOMBRE
           , P.SEGUNDONOMBRE
           , P.PRIMERAPELLIDO
           , P.SEGUNDOAPELLIDO
           , P.PARAM_TIPODOCUMENTO
           , P.NUMERODOCUMENTO
           , P.FECHANACIMIENTO
           , P.PARAM_GENERO
           , P.PARAM_ETNIAPERTENECE
           , V_DISCAPACIDAD AS DISCAPACIDAD
           , RP.DIRECCION
           , RP.EMAIL
           , RP.TELEFONO
      FROM TBREGISTROS_PERSONAS RP
      INNER JOIN TBPERSONAS P ON P.ID = RP.ID_PERSONA
      WHERE RP.ID = PI_IDREGPERSONA;
    END;

  PROCEDURE SP_SOLICITARCORRECCION(PI_IDREGPERSONA IN NUMBER,
                                   PI_IDUSUARIOSOLICITUD IN NUMBER,
                                   PI_CAMPOSCORRECCIONES IN VARCHAR,
                                   PI_VALORESCORRECCIONES IN VARCHAR,
                                   PO_IDCORRECCION OUT NUMBER
                                  ) IS

    V_IDCAMPOS       PKG_COMMON.STRING_ARRAY;
    V_IDVALORES      PKG_COMMON.STRING_ARRAY;
    V_IDCORRECCION   NUMBER;
    V_VALORANTERIOR  VARCHAR(500);
    V_USUARIOMENENOSCARGA NUMBER;

  BEGIN

    V_USUARIOMENENOSCARGA:=PKG_CORRECCIONES.F_USUARIOMENOSCARGACORRECCION(ROL);

    SELECT SEQ_TBCORRECCION.NEXTVAL INTO V_IDCORRECCION FROM DUAL;
    PO_IDCORRECCION := V_IDCORRECCION;

    --_______________Cabecera_________________
    INSERT
    INTO TBCORRECCION
      (
        ID,
        ID_REGPERSONA,
        ID_USUARIOSOLICITUD,
        ID_USUARIO,
        FECHASOLICITUD,
        ESTADO
      )
      VALUES
      (
        V_IDCORRECCION,
        PI_IDREGPERSONA,
        PI_IDUSUARIOSOLICITUD,
        V_USUARIOMENENOSCARGA,
        SYSDATE,
        PENDIENTE
      );
    --_______________________________________

    --_______________Detalle_________________

      V_IDCAMPOS := PKG_COMMON.SPLIT_STRING(PI_CAMPOSCORRECCIONES);
      V_IDVALORES := PKG_COMMON.SPLIT_STRING(PI_VALORESCORRECCIONES);

      IF V_IDCAMPOS.count > 0 THEN
        FOR I IN 1..V_IDCAMPOS.COUNT LOOP

          V_VALORANTERIOR := OBTENERVALORANTERIOR(PI_IDREGPERSONA, V_IDCAMPOS(I));

          INSERT
          INTO TBCORRECCIONCAMPOS
            (
              ID,
              ID_CORRECCION,
              CAMPO,
              VALORANTERIOR,
              VALORNUEVO
            )
            VALUES
            (
              SEQ_TBCORRECCIONCAMPOS.NEXTVAL,
              V_IDCORRECCION,
              V_IDCAMPOS(I),
              V_VALORANTERIOR,
              V_IDVALORES(I)
            );

        END LOOP;
      END IF;

    --_______________________________________

  END;

  PROCEDURE SP_BUSCAPERSONASCOUNT(PI_NUMEROFORMULARIO IN VARCHAR2,
                                  PI_PRIMERNOMBRE     IN VARCHAR2,
                                  PI_PRIMERAPELLIDO   IN VARCHAR2,
                                  PI_NUMERODOCUMENTO  IN VARCHAR2,
                                  PO_RECORDCOUNT      OUT NUMBER) IS
  BEGIN
    SELECT COUNT(1) INTO PO_RECORDCOUNT
    FROM TBREGISTROS_PERSONAS RP
    INNER JOIN TBPERSONAS      PP ON (PP.ID = RP.ID_PERSONA)
    INNER JOIN TBDECLARACIONES DD ON (DD.ID = RP.ID_DECLARACION)
    WHERE DD.NUMEROFORMULARIO = NVL(pi_NumeroFormulario, DD.NUMEROFORMULARIO)
      AND PP.NUMERODOCUMENTO  = NVL(pi_NumeroDocumento , PP.NUMERODOCUMENTO)
      AND UPPER(PP.PRIMERNOMBRE)   LIKE '%' || UPPER(NVL(pi_PrimerNombre  , PP.PRIMERNOMBRE)) || '%'
      AND UPPER(PP.PRIMERAPELLIDO) LIKE '%' || UPPER(NVL(pi_PrimerApellido, PP.PRIMERAPELLIDO)) || '%';
  END;

  PROCEDURE SP_BUSCAPERSONAS(PI_NUMEROFORMULARIO IN VARCHAR2,
                             PI_PRIMERNOMBRE     IN VARCHAR2,
                             PI_PRIMERAPELLIDO   IN VARCHAR2,
                             PI_NUMERODOCUMENTO  IN VARCHAR2,
                             PI_PAGENUMBER       IN NUMBER,
                             PI_PAGESIZE         IN NUMBER,
                             PO_CURSOR           OUT CURSOR_TYPE) IS
    LOWERBOUND NUMBER;
    UPPERBOUND NUMBER;
  BEGIN
     LOWERBOUND := (PI_PAGENUMBER * PI_PAGESIZE) + 1;
    UPPERBOUND := ((PI_PAGENUMBER - 1) * PI_PAGESIZE) + 1;
 
    OPEN PO_CURSOR FOR
      SELECT *
      FROM(
            SELECT INFO.*, ROWNUM AS R
            FROM(
                  SELECT RP.ID               AS NIDREGISTROPRESONA
                       , DD.NUMEROFORMULARIO AS NUMEROFORMULARIO
                       , P2.NOMBRE           AS ESTADOPROCESO
                       , DD.FECHADECLARACION AS FECHADECLARACION
                       , M.NOMBRE            AS MUNICIPIO
                       , D.NOMBRE            AS DEPARTAMENTO
                       , P.NOMBRE            AS PAIS
                       , PP.PRIMERNOMBRE     AS PRIMERNOMBRE
                       , PP.SEGUNDONOMBRE    AS SEGUNDONOMBRE
                       , PP.PRIMERAPELLIDO   AS PRIMERAPELLIDO
                       , PP.SEGUNDOAPELLIDO  AS SEGUNDOAPELLIDO
                       , P1.NOMBRE           AS TIPODOCUMENTO
                       , PP.NUMERODOCUMENTO  AS NUMERODOCUMENTO
                       , DD.ID               AS ID
                  FROM TBREGISTROS_PERSONAS     RP
                  INNER JOIN TBPERSONAS         PP ON (PP.ID = RP.ID_PERSONA)
                  INNER JOIN TBDECLARACIONES    DD ON (DD.ID = RP.ID_DECLARACION)
                  INNER JOIN TBPARAMETROS       P1 ON (P1.ID = PP.PARAM_TIPODOCUMENTO)
                  INNER JOIN TBPARAMETROS       P2 ON (P2.ID = DD.PARAM_ESTADO)
                  LEFT  JOIN TBENTIDADMUNICIPIO EM ON (EM.ID = DD.ID_ENTIDADMUNICIPIODECLARACION)
                  LEFT  JOIN TBGEOGRAFIA        M ON M.ID = EM.ID_MUNICIPIO
                  LEFT  JOIN TBGEOGRAFIA        D ON D.ID = M.PADREID
                  LEFT  JOIN TBGEOGRAFIA        P ON P.ID = D.PADREID
                  WHERE DD.NUMEROFORMULARIO = NVL(pi_NumeroFormulario, DD.NUMEROFORMULARIO)
                    AND NVL(PP.NUMERODOCUMENTO,-1)  = NVL(pi_NumeroDocumento , -1)
                    AND UPPER(PP.PRIMERNOMBRE)   LIKE '%' || UPPER(NVL(pi_PrimerNombre  , PP.PRIMERNOMBRE)) || '%'
                    AND UPPER(PP.PRIMERAPELLIDO) LIKE '%' || UPPER(NVL(pi_PrimerApellido, PP.PRIMERAPELLIDO)) || '%'
                ) INFO
            WHERE ROWNUM < LOWERBOUND)
      WHERE R >= UPPERBOUND;        
  END;

  PROCEDURE SP_CONSULTARCORRECCION(PI_IDCORRECCION IN NUMBER,
                                   PO_CURSOR OUT CURSOR_TYPE
                                  ) IS

    V_DISCAPACIDAD VARCHAR2(300);
    VLIST PKG_SERIALIZATION.NUMBERVARRAY;
    V_ID_REGPERSONA NUMBER;
  BEGIN

    OPEN PO_CURSOR FOR
      SELECT OBTENERVALORCORRECCION(PI_IDCORRECCION, PRIMERNOMBRE) PRIMERNOMBRE
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, SEGUNDONOMBRE) SEGUNDONOMBRE
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, PRIMERAPELLIDO) PRIMERAPELLIDO
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, SEGUNDOAPELLIDO) SEGUNDOAPELLIDO
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, TIPODOCUMENTO) PARAM_TIPODOCUMENTO
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, DOCUMENTO) NUMERODOCUMENTO
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, FECHANACIMIENTO) FECHANACIMIENTO
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, GENERO) PARAM_GENERO
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, ETNIA) PARAM_ETNIAPERTENECE
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, SUBETNIA) PARAM_MINORIAETNICA
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, DISCAPACIDADES) DISCAPACIDAD
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, DIRECCION) DIRECCION
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, TELEFONO) TELEFONO
           , OBTENERVALORCORRECCION(PI_IDCORRECCION, CORREOELECTRONICO) CORREOELECTRONICO
      FROM DUAL;

  END;

  PROCEDURE SP_RECHAZARCORRECCION(PI_IDCORRECCION IN NUMBER,
                                   PI_IDUSUARIORECHAZA IN NUMBER,
                                   PI_OBSERVACION in VARCHAR
                                  ) IS

  BEGIN

    UPDATE TBCORRECCION SET ID_USUARIO    = PI_IDCORRECCION,
                            OBSERVACIONES = PI_OBSERVACION,
                            ESTADO        = RECHAZADO
                        WHERE ID = PI_IDCORRECCION;

  END;

  PROCEDURE SP_CONSULTARCAMPOSCORRECCION(PI_IDCORRECCION IN NUMBER,
                                         PO_CURSOR OUT CURSOR_TYPE
                                        ) IS

  BEGIN

    OPEN PO_CURSOR FOR
      SELECT CC.CAMPO, CC.VALORNUEVO VALOR
        FROM TBCORRECCIONCAMPOS CC
        WHERE ID_CORRECCION = PI_IDCORRECCION;

  END;

  FUNCTION OBTENERVALORANTERIOR(PI_ID_REGPERSONA IN NUMBER,
                                PI_CAMPO IN NUMBER
                               ) RETURN VARCHAR2
                                IS
  RETURN_VALUE VARCHAR2(500);
  V_IDPERSONA NUMBER;
  V_DISCAPACIDAD VARCHAR2(300);
  VLIST PKG_SERIALIZATION.NUMBERVARRAY;

  BEGIN

    SELECT ID_PERSONA INTO V_IDPERSONA FROM TBREGISTROS_PERSONAS WHERE ID = PI_ID_REGPERSONA;

    CASE
      WHEN PI_CAMPO = PRIMERNOMBRE THEN
        SELECT PRIMERNOMBRE INTO RETURN_VALUE FROM TBPERSONAS WHERE ID = V_IDPERSONA;
      WHEN PI_CAMPO = SEGUNDONOMBRE THEN
        SELECT SEGUNDONOMBRE INTO RETURN_VALUE FROM TBPERSONAS WHERE ID = V_IDPERSONA;
      WHEN PI_CAMPO = PRIMERAPELLIDO THEN
        SELECT PRIMERAPELLIDO INTO RETURN_VALUE FROM TBPERSONAS WHERE ID = V_IDPERSONA;
      WHEN PI_CAMPO = SEGUNDOAPELLIDO THEN
        SELECT SEGUNDOAPELLIDO INTO RETURN_VALUE FROM TBPERSONAS WHERE ID = V_IDPERSONA;
      WHEN PI_CAMPO = TIPODOCUMENTO THEN
        SELECT PARAM_TIPODOCUMENTO INTO RETURN_VALUE FROM TBPERSONAS WHERE ID = V_IDPERSONA;
      WHEN PI_CAMPO = DOCUMENTO THEN
        SELECT NUMERODOCUMENTO INTO RETURN_VALUE FROM TBPERSONAS WHERE ID = V_IDPERSONA;
      WHEN PI_CAMPO = FECHANACIMIENTO THEN
        SELECT FECHANACIMIENTO INTO RETURN_VALUE FROM TBPERSONAS WHERE ID = V_IDPERSONA;
      WHEN PI_CAMPO = GENERO THEN
        SELECT PARAM_GENERO INTO RETURN_VALUE FROM TBPERSONAS WHERE ID = V_IDPERSONA;
      WHEN PI_CAMPO = ETNIA THEN
        SELECT PARAM_ETNIAPERTENECE INTO RETURN_VALUE FROM TBPERSONAS WHERE ID = V_IDPERSONA;
      WHEN PI_CAMPO = DISCAPACIDADES THEN
        SELECT PARAM_DISCAPACIDAD BULK COLLECT INTO VLIST
          FROM TBDISCAPACIDAD_PERSONA WHERE ID_REGPERSONA = PI_ID_REGPERSONA;
        RETURN_VALUE := PKG_SERIALIZATION.Serialize(VLIST);
      WHEN PI_CAMPO = DIRECCION THEN
        SELECT DIRECCION INTO RETURN_VALUE FROM TBREGISTROS_PERSONAS WHERE ID = PI_ID_REGPERSONA;
      WHEN PI_CAMPO = TELEFONO THEN
        SELECT TELEFONO INTO RETURN_VALUE FROM TBREGISTROS_PERSONAS WHERE ID = PI_ID_REGPERSONA;
      WHEN PI_CAMPO = CORREOELECTRONICO THEN
        SELECT EMAIL INTO RETURN_VALUE FROM TBREGISTROS_PERSONAS WHERE ID = PI_ID_REGPERSONA;
     WHEN PI_CAMPO = SUBETNIA THEN
        SELECT PARAM_MINORIAETNICA INTO RETURN_VALUE FROM TBPERSONAS WHERE ID = V_IDPERSONA;

    END CASE;

    RETURN RETURN_VALUE;

  END OBTENERVALORANTERIOR;

  FUNCTION OBTENERVALORCORRECCION(PI_IDCORRECCION IN NUMBER,
                                  PI_CAMPO IN NUMBER
                                 ) RETURN VARCHAR2
                                  IS
  RETURN_VALUE VARCHAR2(500);

  BEGIN

    SELECT VALORNUEVO INTO RETURN_VALUE
      FROM TBCORRECCIONCAMPOS
      WHERE ID_CORRECCION = PI_IDCORRECCION AND
            CAMPO         = PI_CAMPO;

    RETURN RETURN_VALUE;

  END OBTENERVALORCORRECCION;

  PROCEDURE SP_APROBARSOLICITUD(PI_IDCORRECCION IN NUMBER) IS
      V_IDREGPERSONA NUMBER;
      V_IDPERSONA    NUMBER;
    BEGIN
      SELECT ID_REGPERSONA INTO V_IDREGPERSONA FROM TBCORRECCION WHERE ID = PI_IDCORRECCION;
      SELECT ID_PERSONA    INTO V_IDPERSONA FROM TBREGISTROS_PERSONAS WHERE ID = V_IDREGPERSONA;
      -- CAMBIAR ESTADO DE LA CORRECION
      UPDATE TBCORRECCION SET ESTADO = APROBADO WHERE ID = PI_IDCORRECCION;


      -- BUSCAR LOS CAMPOS
      FOR X IN (SELECT CC.CAMPO, CC.VALORNUEVO FROM TBCORRECCIONCAMPOS CC
                WHERE CC.ID_CORRECCION = PI_IDCORRECCION) LOOP
        IF X.CAMPO = PRIMERNOMBRE THEN
          UPDATE TBPERSONAS SET PRIMERNOMBRE = X.VALORNUEVO WHERE ID = V_IDPERSONA;


        ELSIF X.CAMPO = SEGUNDONOMBRE THEN
          UPDATE TBPERSONAS  SET SEGUNDONOMBRE = X.VALORNUEVO WHERE ID = V_IDPERSONA;


        ELSIF X.CAMPO = PRIMERAPELLIDO THEN
          UPDATE TBPERSONAS SET PRIMERAPELLIDO = X.VALORNUEVO WHERE ID = V_IDPERSONA;


        ELSIF X.CAMPO = SEGUNDOAPELLIDO THEN
          UPDATE TBPERSONAS SET SEGUNDOAPELLIDO = X.VALORNUEVO WHERE ID = V_IDPERSONA;


        ELSIF X.CAMPO = TIPODOCUMENTO THEN
          UPDATE TBPERSONAS SET PARAM_TIPODOCUMENTO = CAST(X.VALORNUEVO AS NUMBER) WHERE ID = V_IDPERSONA;


        ELSIF X.CAMPO = DOCUMENTO THEN
          UPDATE TBPERSONAS SET NUMERODOCUMENTO = X.VALORNUEVO WHERE ID = V_IDPERSONA;


        ELSIF X.CAMPO = FECHANACIMIENTO THEN
          UPDATE TBPERSONAS SET FECHANACIMIENTO = CAST(X.VALORNUEVO AS DATE) WHERE ID = V_IDPERSONA;


        ELSIF X.CAMPO = GENERO THEN
          UPDATE TBPERSONAS SET PARAM_GENERO = CAST(X.VALORNUEVO AS NUMBER) WHERE ID = V_IDPERSONA;


        ELSIF X.CAMPO = ETNIA THEN
          UPDATE TBPERSONAS SET PARAM_ETNIAPERTENECE = CAST(X.VALORNUEVO AS NUMBER) WHERE ID = V_IDPERSONA;

        ELSIF X.CAMPO = SUBETNIA THEN
          UPDATE TBPERSONAS SET PARAM_MINORIAETNICA = CAST(X.VALORNUEVO AS NUMBER) WHERE ID = V_IDPERSONA;

        ELSIF X.CAMPO = DIRECCION THEN
          UPDATE TBREGISTROS_PERSONAS SET DIRECCION = X.VALORNUEVO WHERE ID = V_IDREGPERSONA;


        ELSIF X.CAMPO = CORREOELECTRONICO  THEN
          UPDATE TBREGISTROS_PERSONAS SET EMAIL = X.VALORNUEVO WHERE ID = V_IDREGPERSONA;


        ELSIF X.CAMPO = TELEFONO THEN
          UPDATE TBREGISTROS_PERSONAS SET TELEFONO = X.VALORNUEVO WHERE ID = V_IDREGPERSONA;


        ELSIF X.CAMPO = DISCAPACIDADES THEN
          DELETE FROM TBDISCAPACIDAD_PERSONA WHERE ID_REGPERSONA = V_IDREGPERSONA;

          DECLARE
            V_DISCAPACIDAD PKG_SERIALIZATION.NUMBERVARRAY;
          BEGIN
            V_DISCAPACIDAD := PKG_SERIALIZATION.DESERIALIZE(X.VALORNUEVO);
            IF V_DISCAPACIDAD.COUNT > 0 THEN
              FOR Z IN V_DISCAPACIDAD.FIRST..V_DISCAPACIDAD.LAST LOOP
                INSERT INTO TBDISCAPACIDAD_PERSONA (ID_REGPERSONA, PARAM_DISCAPACIDAD, ACTIVO)
                VALUES (V_IDREGPERSONA, V_DISCAPACIDAD(Z), 1);
              END LOOP;
            END IF;
          END;
        END IF;
      END LOOP;
    END;

 FUNCTION F_USUARIOMENOSCARGACORRECCION( P_Rol NUMBER )
  RETURN NUMBER IS Result NUMBER;
  BEGIN

    SELECT ID
    INTO   Result
    FROM   (SELECT ID
            FROM   ( SELECT RU.id_usuario AS Id, COUNT(NVL(CC.ID_USUARIO, 0)) AS CONTADOR
                     FROM   tbroles_usuario RU
                     INNER JOIN TBUSUARIOS   UU ON (UU.ID = RU.ID_USUARIO AND UU.ACTIVO = 1)
                     LEFT  JOIN TBCORRECCION CC ON (RU.ID_USUARIO = CC.ID_USUARIO)
                     WHERE  RU.id_rol = P_Rol
                     GROUP BY RU.id_usuario
                     ORDER BY CONTADOR ASC)
             WHERE ROWNUM = 1);
    RETURN (RESULT);
  END;

 /*-------------------------------------------
   Purpose : Obtiene el nombre de la Subetnia
   Author  : John Henao
   Fecha   : 12/06/2013
 --------------------------------------------
 */

 PROCEDURE SP_OBTENERNOMBRESUBETNIA(P_ID IN NUMBER,
                                    PO_NombreSubEtnia OUT NVARCHAR2) IS

  BEGIN
    SELECT NOMBRE INTO PO_NombreSubEtnia FROM TBETNIACOMUNIDADES WHERE ID = P_ID;
  END;

END PKG_CORRECCIONES;
/