//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.Infrastructure.Crosscutting.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Advertencia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advertencia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruv.Infrastructure.Crosscutting.Resources.Globalization.Advertencia", typeof(Advertencia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        public static string AdvertenciaTitulo {
            get {
                return ResourceManager.GetString("AdvertenciaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos de la ubicación del formulario no pueden estar vacíos..
        /// </summary>
        public static string CamposGeografiaVacios {
            get {
                return ResourceManager.GetString("CamposGeografiaVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos &quot;Dirección&quot;, &quot;Teléfono&quot;, &quot;Funcionario&quot; y la parte emotiva de la devolución no pueden estar vacíos. Por favor verifiquelos y corríjalos..
        /// </summary>
        public static string CamposRequeridosDevolucion {
            get {
                return ResourceManager.GetString("CamposRequeridosDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe diligenciar al menos un campo. Por favor vuelva a intentarlo..
        /// </summary>
        public static string DiligenciarAlMenosUnCampo {
            get {
                return ResourceManager.GetString("DiligenciarAlMenosUnCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe escribir una observación para poder continuar.
        /// </summary>
        public static string DiligenciarObservacion {
            get {
                return ResourceManager.GetString("DiligenciarObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe tener presente que si ingresa el &quot;Número de formulario&quot; o el &quot;Número de documento&quot; deberá ingresar también o el &quot;Nombre&quot; o el &quot;Apellido&quot;. Por favor vuelva a intentarlo..
        /// </summary>
        public static string FormularioCedulaConNombreApellido {
            get {
                return ResourceManager.GetString("FormularioCedulaConNombreApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de formulario ingresado está inactivo. Por favor verifíque los datos y vuelva a intentarlo..
        /// </summary>
        public static string FormularioInactivo {
            get {
                return ResourceManager.GetString("FormularioInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de formulario ingresado es inválido. Por favor verifíque los datos y vuelva a intentarlo..
        /// </summary>
        public static string FormularioInvalido {
            get {
                return ResourceManager.GetString("FormularioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de formulario no puede estar vacío. Por favor verifíque los datos y vuelva a intentarlo..
        /// </summary>
        public static string FormularioVacio {
            get {
                return ResourceManager.GetString("FormularioVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de formulario ingresado ya ha sido radicado previamente. Por favor verifíque los datos y vuelva a intentarlo..
        /// </summary>
        public static string FormularioYaRadicado {
            get {
                return ResourceManager.GetString("FormularioYaRadicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar las notificaciones con las que desea generar el paquete. Tenga en cuenta que estas deben estar en estado &apos;Pendiente envío&apos; y haber sido aprobadas..
        /// </summary>
        public static string GeneracionDePaquete {
            get {
                return ResourceManager.GetString("GeneracionDePaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se generarán {0} numeros de formulario, desea continuar?.
        /// </summary>
        public static string GenerarNumerosFormulario {
            get {
                return ResourceManager.GetString("GenerarNumerosFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe tener presente que si ingresa el &quot;Nombre&quot; o el &quot;Apellido&quot; deberá ingresar también o el &quot;Número de formulario&quot; o el &quot;Número de documento&quot;. Por favor vuelva a intentarlo..
        /// </summary>
        public static string NombreApellidoConFormularioCedula {
            get {
                return ResourceManager.GetString("NombreApellidoConFormularioCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Indicar almenos &quot;Primer Nombre&quot; y &quot;Primer Apellido&quot; en caso de no indicar el &quot;Número de formulario&quot; o el &quot;Numero de Documento&quot;.
        /// </summary>
        public static string NombreOApellido {
            get {
                return ResourceManager.GetString("NombreOApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay red disponible en el momento. Por favor vuelva a intentarlo más tarde..
        /// </summary>
        public static string RedNoDisponible {
            get {
                return ResourceManager.GetString("RedNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algunas de las notificaciones provenientes del reporte del Courier no han sido actualizadas puesto que no se encontró coincidencia total de datos con las actuales notificaciones.
        /// </summary>
        public static string SinCoincidenciaTotalNotificacionesCourier {
            get {
                return ResourceManager.GetString("SinCoincidenciaTotalNotificacionesCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud realizada al servidor no puede estar vacía. Por favor intente nuevamente..
        /// </summary>
        public static string SolicitudVacia {
            get {
                return ResourceManager.GetString("SolicitudVacia", resourceCulture);
            }
        }
    }
}
