//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.Infrastructure.Crosscutting.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruv.Infrastructure.Crosscutting.Resources.Globalization.Errores", typeof(Errores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se finalizó con éxito la valoración. Sin embargo, no se lograron generar los documentos de actos administrativos.
        /// </summary>
        public static string ActosAdministrativosError {
            get {
                return ResourceManager.GetString("ActosAdministrativosError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo no puede estar vacío.
        /// </summary>
        public static string CampoVacio {
            get {
                return ResourceManager.GetString("CampoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar adjuntar el archivo.
        /// </summary>
        public static string ErrorAdjuntandoArchivo {
            get {
                return ResourceManager.GetString("ErrorAdjuntandoArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitulo {
            get {
                return ResourceManager.GetString("ErrorTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede activar un formulario que ha sido inactivado previamente.
        /// </summary>
        public static string FormularioYaInactivo {
            get {
                return ResourceManager.GetString("FormularioYaInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error en el aplicativo, por favor vuelva a intentarlo y si el error persiste comuníquese con el administrador indicándole el siguiente mensaje: &quot;{0}&quot;.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El maximo de formularios a generar es de 20.
        /// </summary>
        public static string MaximoFormularios {
            get {
                return ResourceManager.GetString("MaximoFormularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró una devolución relacionada con esta declaración.
        /// </summary>
        public static string NoExisteDevolucionParaDeclaracion {
            get {
                return ResourceManager.GetString("NoExisteDevolucionParaDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe ninguna coincidencia de datos de las actuales notificaciones con el reporte enviado por el Courier.
        /// </summary>
        public static string SinCoincidenciaNotificacionesCourier {
            get {
                return ResourceManager.GetString("SinCoincidenciaNotificacionesCourier", resourceCulture);
            }
        }
    }
}
