//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.Infrastructure.Crosscutting.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Informacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Informacion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruv.Infrastructure.Crosscutting.Resources.Globalization.Informacion", typeof(Informacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede realizar ningún cambio sobre un formulario que ha sido inactivado previamente..
        /// </summary>
        public static string CambioEnFormularioInactivo {
            get {
                return ResourceManager.GetString("CambioEnFormularioInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los cambios han sido guardados exitosamente..
        /// </summary>
        public static string CambiosGuardados {
            get {
                return ResourceManager.GetString("CambiosGuardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro que desea {0} los formularios seleccionados?.
        /// </summary>
        public static string ConfirmarActivaciónInactivación {
            get {
                return ResourceManager.GetString("ConfirmarActivaciónInactivación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de distribuir los numeros de formulario a los que les cambio la ubicación?.
        /// </summary>
        public static string ConfirmarDistribución {
            get {
                return ResourceManager.GetString("ConfirmarDistribución", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de separar a imprenta los numeros de formularios seleccionados?.
        /// </summary>
        public static string ConfirmarSepararImprenta {
            get {
                return ResourceManager.GetString("ConfirmarSepararImprenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha descargado correctamente el archivo clic aquí abrirlo.
        /// </summary>
        public static string DescargadoCorrectamente {
            get {
                return ResourceManager.GetString("DescargadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los documentos fueron generados.
        /// </summary>
        public static string DocumentosGeneradosCorrectamente {
            get {
                return ResourceManager.GetString("DocumentosGeneradosCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha generado correctamente el archivo clic aquí para abrirlo.
        /// </summary>
        public static string GeneradoCorrectamente {
            get {
                return ResourceManager.GetString("GeneradoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay cambios a realizar..
        /// </summary>
        public static string NoCambios {
            get {
                return ResourceManager.GetString("NoCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay datos que cincidan con los parámetros de búsqueda. Por favor vuelva a intentarlo.
        /// </summary>
        public static string NoCoincidencia {
            get {
                return ResourceManager.GetString("NoCoincidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay elementos seleccionados para realizar la operación.
        /// </summary>
        public static string NoDatosParaAccion {
            get {
                return ResourceManager.GetString("NoDatosParaAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro el documento escaneado.
        /// </summary>
        public static string NoDocumentoEscaneado {
            get {
                return ResourceManager.GetString("NoDocumentoEscaneado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si no se selecciona causal alguna debe ingresar una observación.
        /// </summary>
        public static string ObservacionesRequeridasDevolucion {
            get {
                return ResourceManager.GetString("ObservacionesRequeridasDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor Indique la razon por la cual desea inactivar este o estos formularios.
        /// </summary>
        public static string ObservacionRequerida {
            get {
                return ResourceManager.GetString("ObservacionRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La radicación pasó a un estado de &quot;Devolución&quot;..
        /// </summary>
        public static string RadicacionADevolucion {
            get {
                return ResourceManager.GetString("RadicacionADevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La declaración pasó a estado &quot;Radicación finalizada, pendiente captura&quot;..
        /// </summary>
        public static string RadicacionFinalizadaPendCaptura {
            get {
                return ResourceManager.GetString("RadicacionFinalizadaPendCaptura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea asignar el formulario a la distribución geográfica seleccionada?.
        /// </summary>
        public static string RedistribuirFormulario {
            get {
                return ResourceManager.GetString("RedistribuirFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
    }
}
