ALTER TABLE TBENTIDADMUNICIPIO MODIFY DIRECCIONENTIDAD VARCHAR2(500);

ALTER TABLE TBACTO_ADMINISTRATIVO ADD DFIRMA DATE DEFAULT NULL;
ALTER TABLE TBACTO_ADMINISTRATIVO ADD TIPOCODIGOACTO NUMBER(1, 0) NULL;
ALTER TABLE TBACTO_ADMINISTRATIVO ADD CONSTRAINT ACTOADMIN_TIPOCODIGO_CK CHECK (TIPOCODIGOACTO IN (1, 0, NULL));

COMMENT ON COLUMN TBACTO_ADMINISTRATIVO.TIPOCODIGOACTO 
   IS '1 para código nuevo, 0 para codigo antiguo, NULL para no determinado aún';

ALTER TABLE TBVALORACION DROP COLUMN IDENTIDADMUNICIPIO;

COMMENT ON COLUMN TBNOTIFICACION.ID_PAIS
  IS 'Identificador de país donde se dirige el envío (Citación)';
  
COMMENT ON COLUMN TBNOTIFICACION.ID_DEPARTAMENTO
  IS 'Identificador de departamento donde se dirige el envío (Citación)';
  
COMMENT ON COLUMN TBNOTIFICACION.ID_MUNICIPIO
  IS 'Identificador de municipio donde se dirige el envío (Citación)';
  
COMMENT ON COLUMN TBNOTIFICACION.DIRECCIONNOTIFICACION
  IS 'Nomenclatura donde se dirige el envío (Citación)';

/* Correccion de referencias en TBNOTIFICACION. No se puede enviar una notificación a un municipio nulo */

ALTER TABLE TBNOTIFICACION MODIFY DIRECCIONNOTIFICACION VARCHAR2(400) NOT NULL;

-- Crear referencias de geografia (citación)
ALTER TABLE TBNOTIFICACION MODIFY ID_PAIS         NUMBER NOT NULL;
ALTER TABLE TBNOTIFICACION ADD CONSTRAINT NOTIFICACION_PAIS_FK         FOREIGN KEY (ID_PAIS)         REFERENCES TBGEOGRAFIA (ID);
ALTER TABLE TBNOTIFICACION MODIFY ID_DEPARTAMENTO NUMBER NOT NULL;
ALTER TABLE TBNOTIFICACION ADD CONSTRAINT NOTIFICACION_DEPARTAMENTO_FK FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES TBGEOGRAFIA (ID);
ALTER TABLE TBNOTIFICACION MODIFY ID_MUNICIPIO    NUMBER NOT NULL;
ALTER TABLE TBNOTIFICACION ADD CONSTRAINT NOTIFICACION_MUNICIPIO_FK    FOREIGN KEY (ID_MUNICIPIO)    REFERENCES TBGEOGRAFIA (ID);

/* Notificaciones se realizan en puntos de atención y direcciones territoriales, de acuerdo al motor de selección (Diego) */
ALTER TABLE TBNOTIFICACION DROP COLUMN ID_ENTIDADMUNICIPIO;

ALTER TABLE TBNOTIFICACION ADD ID_PUNTOATENCION        NUMBER(10) NULL;
ALTER TABLE TBNOTIFICACION ADD CONSTRAINT NOTIFICACION_PUNTOATENCION_FK  FOREIGN KEY (ID_PUNTOATENCION)        REFERENCES TBPUNTOATENCION        (ID);

ALTER TABLE TBNOTIFICACION ADD ID_DIRECCIONTERRITORIAL NUMBER(10) NULL;
ALTER TABLE TBNOTIFICACION ADD CONSTRAINT NOTIFICACION_DIRECCIONTERRI_FK FOREIGN KEY (ID_DIRECCIONTERRITORIAL) REFERENCES TBDIRECCIONTERRITORIAL (ID);

/* Eliminación de columnas redundantes (y no utilizadas) en Reglas de Citación y Notificación */
ALTER TABLE TBREGLASNOTIFICACION DROP COLUMN IDDEPARTAMENTO;
ALTER TABLE TBREGLASCITACION     DROP COLUMN IDDEPARTAMENTO;

-- Asegurarse que todas las notificaciones tienen un lugar de notificacion

ALTER TABLE TBNOTIFICACION ADD CONSTRAINT NOTIFICACION_LUGAR_CK CHECK (ID_PUNTOATENCION IS NOT NULL OR ID_DIRECCIONTERRITORIAL IS NOT NULL);

-- Paquetes de notificacion siempre deben tener hijos

DELETE FROM TBPAQUETENOTIFICACION WHERE ID NOT IN (SELECT DISTINCT(ID_PAQUETENOTIFICACION) FROM TBNOTIFICACION WHERE ID_PAQUETENOTIFICACION IS NOT NULL);
COMMIT;

--Se agrega la Columna de idcodigoguia para guardar los codigos guias que envia el courier 
ALTER TABLE TBNOTIFICACION ADD IDCODIGOGUIA VARCHAR2(250);

-- Información de dirección de citación

ALTER TABLE TBNOTIFICACION ADD CITACIONAENTIDAD NUMBER(1, 0) DEFAULT 0 NOT NULL;
ALTER TABLE TBNOTIFICACION ADD CONSTRAINT NOTIFICACION_CITACIONENT_CK CHECK (CITACIONAENTIDAD IN (1, 0));
COMMENT ON COLUMN TBNOTIFICACION.CITACIONAENTIDAD IS 'Si la citacion de realiza a una entidad (Direccion Territorial) por falta de una dirección valida, 1. De lo contrario, 0.';

CREATE INDEX NOTIFICACION_PUNTOATENCION_IX ON TBNOTIFICACION (ID_PUNTOATENCION);
CREATE INDEX NOTIFICACION_DIRECCIONTERRI_IX ON TBNOTIFICACION (ID_DIRECCIONTERRITORIAL);

/* Correccion de table TBENCARGADOENTIDAD */
DELETE FROM TBENCARGADOENTIDAD WHERE 1 = 1;
COMMIT;
ALTER TABLE TBENCARGADOENTIDAD DROP COLUMN ID_ENTIDADMUNICIPIO;
ALTER TABLE TBENCARGADOENTIDAD ADD ID_PUNTOATENCION NUMBER(10);
ALTER TABLE TBENCARGADOENTIDAD ADD CONSTRAINT ENCARGADO_PUNTOATENCION_FK FOREIGN KEY (ID_PUNTOATENCION) REFERENCES TBPUNTOATENCION (ID);
ALTER TABLE TBENCARGADOENTIDAD ADD ID_DIRECCIONTERRITORIAL NUMBER(10);
ALTER TABLE TBENCARGADOENTIDAD ADD CONSTRAINT ENCARGADO_DIRECCION_FK FOREIGN KEY (ID_DIRECCIONTERRITORIAL) REFERENCES TBDIRECCIONTERRITORIAL (ID);
ALTER TABLE TBENCARGADOENTIDAD ADD CONSTRAINT ENCARGADO_REFERENCIA_CK CHECK (ID_PUNTOATENCION IS NOT NULL OR ID_DIRECCIONTERRITORIAL IS NOT NULL);

/* Correccion de Historico de Notificaciones */
ALTER TABLE TBHISTORICONOTIFICACION DROP COLUMN ID_ENTIDADMUNICIPIO;
ALTER TABLE TBHISTORICONOTIFICACION ADD ID_PUNTOATENCION NUMBER(10);
ALTER TABLE TBHISTORICONOTIFICACION ADD CONSTRAINT HSTNOTIFICACION_PATENCION_FK FOREIGN KEY (ID_PUNTOATENCION) REFERENCES TBPUNTOATENCION (ID);
ALTER TABLE TBHISTORICONOTIFICACION ADD ID_DIRECCIONTERRITORIAL NUMBER(10);
ALTER TABLE TBHISTORICONOTIFICACION ADD CONSTRAINT HSTNOTIFICACION_DTERRITOR_FK FOREIGN KEY (ID_DIRECCIONTERRITORIAL) REFERENCES TBDIRECCIONTERRITORIAL (ID);
ALTER TABLE TBHISTORICONOTIFICACION ADD APROBADO NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE TBHISTORICONOTIFICACION ADD IDCODIGOGUIA VARCHAR2(250);

/* Texto alterno para envio courier */
ALTER TABLE TBGEOGRAFIA ADD NOMBREALTERNO NVARCHAR2(150);

ALTER TABLE TBNOTIFICACION ADD TIPOCODIGOACTO NUMBER(1);
ALTER TABLE TBNOTIFICACION ADD CONSTRAINT NOTIFICACION_CODIGO_CK CHECK (TIPOCODIGOACTO IN (1, 0, NULL));

COMMENT ON COLUMN TBNOTIFICACION.TIPOCODIGOACTO 
   IS '1 para código nuevo, 0 para codigo antiguo, NULL para no determinado aún';
  
                
ALTER TABLE TBNOTIFICACION MODIFY TIPOCODIGOACTO NUMBER(1) NOT NULL;

-- New

ALTER TABLE TBNOTIFICACION ADD ENVIORESOLUCION NUMBER(1) DEFAULT 0 NOT NULL;

/*  DESCRIPCION: SCRIPT PARA ELIMINAR DATOS CORRUPTOS EN LA TABLA 'TBSINIESTROS_PERSONA'
**  COLUMNA 'PARAM_TIPO_ENTORNO' CON DATO DE 'ID' DE PARAMETRO IGUAL A '0'
**	AUTOR: JAIRO VALDERRAMA
**	FECHA: 20130708
*/
UPDATE TBSINIESTROS_PERSONA SET PARAM_TIPO_ENTORNO = NULL WHERE PARAM_TIPO_ENTORNO = 0;

UPDATE TBCAUSALES SET BHABILITADO = 1, TIPO = 2 WHERE ID IN (32,22,30);

commit;