//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.WPF.Captura.DevolucionServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DevolucionServiceReference.IDevolucionService")]
    public interface IDevolucionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDevolucionService/ObtenerDevolucion", ReplyAction="http://tempuri.org/IDevolucionService/ObtenerDevolucionResponse")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.Devolucion.clsDevolucion ObtenerDevolucion(int nIdDeclaracion, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDevolucionService/SolicitarDevolucion", ReplyAction="http://tempuri.org/IDevolucionService/SolicitarDevolucionResponse")]
        bool SolicitarDevolucion(Ruv.Infrastructure.Crosscutting.Common.Entidades.Devolucion.clsDevolucion dev, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDevolucionService/ActualizarDevolucion", ReplyAction="http://tempuri.org/IDevolucionService/ActualizarDevolucionResponse")]
        bool ActualizarDevolucion(Ruv.Infrastructure.Crosscutting.Common.Entidades.Devolucion.clsDevolucion dev, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDevolucionService/GenerarDocumentoDevolucion", ReplyAction="http://tempuri.org/IDevolucionService/GenerarDocumentoDevolucionResponse")]
        byte[] GenerarDocumentoDevolucion(int nIdDevolucion, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDevolucionService/ObtenerCausalesDevolucion", ReplyAction="http://tempuri.org/IDevolucionService/ObtenerCausalesDevolucionResponse")]
        Ruv.Infrastructure.Crosscutting.Common.General.clsCausal[] ObtenerCausalesDevolucion(ref string cError);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDevolucionServiceChannel : Ruv.WPF.Captura.DevolucionServiceReference.IDevolucionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DevolucionServiceClient : System.ServiceModel.ClientBase<Ruv.WPF.Captura.DevolucionServiceReference.IDevolucionService>, Ruv.WPF.Captura.DevolucionServiceReference.IDevolucionService {
        
        public DevolucionServiceClient() {
        }
        
        public DevolucionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DevolucionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevolucionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevolucionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.Devolucion.clsDevolucion ObtenerDevolucion(int nIdDeclaracion, ref string cError) {
            return base.Channel.ObtenerDevolucion(nIdDeclaracion, ref cError);
        }
        
        public bool SolicitarDevolucion(Ruv.Infrastructure.Crosscutting.Common.Entidades.Devolucion.clsDevolucion dev, ref string cError) {
            return base.Channel.SolicitarDevolucion(dev, ref cError);
        }
        
        public bool ActualizarDevolucion(Ruv.Infrastructure.Crosscutting.Common.Entidades.Devolucion.clsDevolucion dev, ref string cError) {
            return base.Channel.ActualizarDevolucion(dev, ref cError);
        }
        
        public byte[] GenerarDocumentoDevolucion(int nIdDevolucion, ref string cError) {
            return base.Channel.GenerarDocumentoDevolucion(nIdDevolucion, ref cError);
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.General.clsCausal[] ObtenerCausalesDevolucion(ref string cError) {
            return base.Channel.ObtenerCausalesDevolucion(ref cError);
        }
    }
}
