//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.WPF.Captura.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruv.WPF.Captura.Recursos.Controles", typeof(Controles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar O Resaignar.
        /// </summary>
        public static string AsignarOReasignar {
            get {
                return ResourceManager.GetString("AsignarOReasignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las declaraciones que tenga pendientes por transmitir o con errores que requieran revisión se eliminaran de su cola, en caso de cualquier inconveniente consulte con el administrador..
        /// </summary>
        public static string BorrarColaPendiente {
            get {
                return ResourceManager.GetString("BorrarColaPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causales de devolución.
        /// </summary>
        public static string CausalesDevolucion {
            get {
                return ResourceManager.GetString("CausalesDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifico que recibí declaración bajo el código de formato No. &lt;Run Text=&quot;{Binding Source={StaticResource RUV}, Path=Configuraciones.Impresion.DeclaracionEnImpresion.DeclaracionNumero}&quot; /&gt;.
        /// </summary>
        public static string CertificoRecibidoFUD {
            get {
                return ResourceManager.GetString("CertificoRecibidoFUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código formulario.
        /// </summary>
        public static string CodigoFormulario {
            get {
                return ResourceManager.GetString("CodigoFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colilla.
        /// </summary>
        public static string Colilla {
            get {
                return ResourceManager.GetString("Colilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSTANCIA DE SOLICITUD DE INSCRIPCIÓN EN EL REGISTRO ÚNICO DE VÍCTIMAS.
        /// </summary>
        public static string ConstanciaSolicitudInscripcion {
            get {
                return ResourceManager.GetString("ConstanciaSolicitudInscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declarante.
        /// </summary>
        public static string Declarante {
            get {
                return ResourceManager.GetString("Declarante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        public static string Departamento {
            get {
                return ResourceManager.GetString("Departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devolver.
        /// </summary>
        public static string Devolver {
            get {
                return ResourceManager.GetString("Devolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo conectado.
        /// </summary>
        public static string DispositivoConectado {
            get {
                return ResourceManager.GetString("DispositivoConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribuir.
        /// </summary>
        public static string Distribuir {
            get {
                return ResourceManager.GetString("Distribuir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad.
        /// </summary>
        public static string Entidad {
            get {
                return ResourceManager.GetString("Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha solicitud devolución.
        /// </summary>
        public static string FechaDevolucion {
            get {
                return ResourceManager.GetString("FechaDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de entrega.
        /// </summary>
        public static string FechaEntrega {
            get {
                return ResourceManager.GetString("FechaEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha generado.
        /// </summary>
        public static string FechaGenerado {
            get {
                return ResourceManager.GetString("FechaGenerado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha modificado.
        /// </summary>
        public static string FechaModificado {
            get {
                return ResourceManager.GetString("FechaModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha radicación.
        /// </summary>
        public static string FechaRadicacion {
            get {
                return ResourceManager.GetString("FechaRadicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        public static string Filtro {
            get {
                return ResourceManager.GetString("Filtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros de búsqueda.
        /// </summary>
        public static string FiltroBusqueda {
            get {
                return ResourceManager.GetString("FiltroBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar.
        /// </summary>
        public static string Finalizar {
            get {
                return ResourceManager.GetString("Finalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionario.
        /// </summary>
        public static string Funcionario {
            get {
                return ResourceManager.GetString("Funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generación de documentos.
        /// </summary>
        public static string GeneracionDocumentos {
            get {
                return ResourceManager.GetString("GeneracionDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar.
        /// </summary>
        public static string Generar {
            get {
                return ResourceManager.GetString("Generar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar PDF.
        /// </summary>
        public static string GenerarPdf {
            get {
                return ResourceManager.GetString("GenerarPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión masiva.
        /// </summary>
        public static string GestionMasiva {
            get {
                return ResourceManager.GetString("GestionMasiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar toma.
        /// </summary>
        public static string IniciarToma {
            get {
                return ResourceManager.GetString("IniciarToma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string Limpiar {
            get {
                return ResourceManager.GetString("Limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        public static string Municipio {
            get {
                return ResourceManager.GetString("Municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de documento.
        /// </summary>
        public static string NumeroDocumento {
            get {
                return ResourceManager.GetString("NumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número FUD.
        /// </summary>
        public static string NumeroFud {
            get {
                return ResourceManager.GetString("NumeroFud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de guía.
        /// </summary>
        public static string NumeroGuia {
            get {
                return ResourceManager.GetString("NumeroGuia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y.
        /// </summary>
        public static string NumerosSerie {
            get {
                return ResourceManager.GetString("NumerosSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique una observación para inactivar este o estos formularios.
        /// </summary>
        public static string Observacion {
            get {
                return ResourceManager.GetString("Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente por distribuir.
        /// </summary>
        public static string PendienteDistribuir {
            get {
                return ResourceManager.GetString("PendienteDistribuir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer apellido.
        /// </summary>
        public static string PrimerApellido {
            get {
                return ResourceManager.GetString("PrimerApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer nombre.
        /// </summary>
        public static string PrimerNombre {
            get {
                return ResourceManager.GetString("PrimerNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango.
        /// </summary>
        public static string Rango {
            get {
                return ResourceManager.GetString("Rango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El resultado de la validación fue.
        /// </summary>
        public static string ResultadoValidacion {
            get {
                return ResourceManager.GetString("ResultadoValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo apellido.
        /// </summary>
        public static string SegundoApellido {
            get {
                return ResourceManager.GetString("SegundoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo nombre.
        /// </summary>
        public static string SegundoNombre {
            get {
                return ResourceManager.GetString("SegundoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separar imprenta.
        /// </summary>
        public static string SepararImprenta {
            get {
                return ResourceManager.GetString("SepararImprenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string TipoDocumento {
            get {
                return ResourceManager.GetString("TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación geográfica.
        /// </summary>
        public static string UbicacionGeografica {
            get {
                return ResourceManager.GetString("UbicacionGeografica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver colilla.
        /// </summary>
        public static string VerColilla {
            get {
                return ResourceManager.GetString("VerColilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar imagen.
        /// </summary>
        public static string VerImagen {
            get {
                return ResourceManager.GetString("VerImagen", resourceCulture);
            }
        }
    }
}
