//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.WPF.Captura.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruv.WPF.Captura.Recursos.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Tipo de afectación (Selección múltiple):.
        /// </summary>
        public static string a01t001 {
            get {
                return ResourceManager.GetString("a01t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Daños en bienes muebles o inmuebles
        ///2 Fracturas
        ///3 Heridas o laceraciones
        ///4 Infección
        ///5 Muerte
        ///6 Parálisis total o parcial
        ///7 Pérdida de la audición total o parcial
        ///8 Pérdida de la vista total o parcial.
        /// </summary>
        public static string a01t002 {
            get {
                return ResourceManager.GetString("a01t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 Pérdida del habla total o parcial
        ///10 Pérdida o amputación de algún miembro u órgano
        ///11 Pérdida total o parcial de la funcionalidad de algún miembro u órgano diferente a vista, audición o habla.
        ///12 Quemaduras
        ///13 Trastornos psicológicos o psiquiátricos que afectan notablemente el funcionamiento o desempeño en las actividades cotidianas
        ///14 Disminución o pérdida de sus fuentes de ingresos
        ///15 Otro.
        /// </summary>
        public static string a01t003 {
            get {
                return ResourceManager.GetString("a01t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor responda las siguientes preguntas en relación con la víctima 1, es decir, la persona que se registrará en la primera fila del siguiente cuadro (ver flecha). 
        ///Estas preguntas hacen referencia al momento en el que ocurrieron los hechos..
        /// </summary>
        public static string a01t004 {
            get {
                return ResourceManager.GetString("a01t004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la primera fila del siguiente cuadro, registre a la víctima de este hecho. A continuación, registre a los miembros del grupo familiar de la víctima.
        ///En caso de haber más de una víctima como consecuencia de este mismo hecho, registre cualquiera de las víctimas en la primera fila y continúe diligenciando el grupo familiar de esta persona en los renglones subsiguientes..
        /// </summary>
        public static string a01t005 {
            get {
                return ResourceManager.GetString("a01t005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En el siguiente cuadro registre a la víctima de este hecho. A continuación, registre a los miembros del grupo familiar de la víctima.
        ///En caso de haber más de una víctima como consecuencia de este mismo hecho, registre cualquiera de las víctimas en la primera fila y continúe diligenciando el grupo familiar de esta persona en los renglones subsiguientes..
        /// </summary>
        public static string a01t006 {
            get {
                return ResourceManager.GetString("a01t006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacione las demás victimas si las hay..
        /// </summary>
        public static string a01t006V2 {
            get {
                return ResourceManager.GetString("a01t006V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Tipo de afectación (Selección múltiple):.
        /// </summary>
        public static string a02t001 {
            get {
                return ResourceManager.GetString("a02t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 Trastornos psicológicos o psiquiátricos que afectan notablemente el funcionamiento o desempeño en las actividades cotidianas
        ///14 Disminución o pérdida de sus fuentes de ingresos
        ///15 Otro.
        /// </summary>
        public static string a02t002 {
            get {
                return ResourceManager.GetString("a02t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Tipo de afectación (Selección múltiple):.
        /// </summary>
        public static string a03t001 {
            get {
                return ResourceManager.GetString("a03t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Fracturas
        ///3 Heridas o laceraciones
        ///4 Infección
        ///5 Muerte
        ///6 Parálisis total o parcial
        ///7 Pérdida de la audición total o parcial
        ///8 Pérdida de la vista total o parcial
        ///9 Pérdida del habla total o parcial.
        /// </summary>
        public static string a03t002 {
            get {
                return ResourceManager.GetString("a03t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Pérdida o amputación de algún miembro u órgano
        ///11 Pérdida total o parcial de la funcionalidad de algún miembro u órgano diferente a vista, audición o habla.
        ///12 Quemaduras
        ///13 Trastornos psicológicos o psiquiátricos que afectan notablemente el funcionamiento o desempeño en las actividades cotidianas
        ///14 Disminución o pérdida de sus fuentes de ingresos
        ///15 Otro.
        /// </summary>
        public static string a03t003 {
            get {
                return ResourceManager.GetString("a03t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 Trastornos psicológicos o psiquiátricos que afectan notablemente el funcionamiento o desempeño en las actividades cotidianas
        ///14 Disminución o pérdida de sus fuentes de ingresos
        ///15 Otro.
        /// </summary>
        public static string a04t001 {
            get {
                return ResourceManager.GetString("a04t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En el siguiente cuadro registre como víctima 1 a la persona que se encuentra desaparecida. A continuación, registre a los miembros del grupo familiar de la víctima.
        ///En caso de haber más de una víctima como consecuencia de este mismo hecho, registre cualquiera de las víctimas en la primera fila y continúe diligenciando el grupo familiar de esta persona en los renglones subsiguientes..
        /// </summary>
        public static string a04t002 {
            get {
                return ResourceManager.GetString("a04t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique para cada miembro del hogar si este se desplazó..
        /// </summary>
        public static string a05t001 {
            get {
                return ResourceManager.GetString("a05t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor responda las siguientes preguntas en relación con la persona Jefe de Hogar especificada en el cuadro anterior. 
        ///Estas preguntas hacen referencia al momento en el que ocurrieron los hechos..
        /// </summary>
        public static string a05t002 {
            get {
                return ResourceManager.GetString("a05t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si el (la) Declarante manifiesta ser víctima de abandono forzado de bienes inmuebles (tierras, lotes o viviendas) o muebles (herramientas, animales, cultivos, vehículos, etc.), diligencie el anexo 11..
        /// </summary>
        public static string a05t003 {
            get {
                return ResourceManager.GetString("a05t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor responda las siguientes preguntas en relación con la persona Jefe de Hogar especificada en el cuadro anterior. Estas preguntas hacen referencia al momento en el que ocurrieron los hechos..
        /// </summary>
        public static string a05t004 {
            get {
                return ResourceManager.GetString("a05t004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En caso de necesitar más hojas para registrar a todos los miembros del grupo familiar, utilice tantos anexos como sea necesario y numere los folios que correspondan a este grupo familiar..
        /// </summary>
        public static string a06t001 {
            get {
                return ResourceManager.GetString("a06t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Tipo de afectación (Selección múltiple):.
        /// </summary>
        public static string a06t002 {
            get {
                return ResourceManager.GetString("a06t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Heridas o laceraciones
        ///5 Muerte
        ///13 Trastornos psicológicos o psiquiátricos que afectan notablemente el funcionamiento o desempeño en las actividades cotidianas
        ///14 Disminución o pérdida de sus fuentes de ingresos
        ///15 Otro.
        /// </summary>
        public static string a06t003 {
            get {
                return ResourceManager.GetString("a06t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor responda las siguientes preguntas en relación con la víctima 1, es decir, la persona que se registrará en la primera fila del siguiente cuadro (ver flecha). 
        ///Estas preguntas hacen referencia al momento en el que ocurrieron los hechos..
        /// </summary>
        public static string a06t004 {
            get {
                return ResourceManager.GetString("a06t004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la primera fila del siguiente cuadro, registre a la víctima de este hecho. A continuación, registre a los miembros del grupo familiar de la víctima.
        ///En caso de haber más de una víctima como consecuencia de este mismo hecho, registre cualquiera de las víctimas en la primera fila y continúe diligenciando el grupo familiar de esta persona en los renglones subsiguientes..
        /// </summary>
        public static string a06t005 {
            get {
                return ResourceManager.GetString("a06t005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En el siguiente cuadro registre como víctima 1 a la persona fallecida. A continuación, registre a los miembros del grupo familiar de la víctima.
        ///En caso de haber más de una víctima como consecuencia de este mismo hecho, registre cualquiera de las víctimas en la primera fila y continúe diligenciando el grupo familiar de esta persona en los renglones subsiguientes..
        /// </summary>
        public static string a06t006 {
            get {
                return ResourceManager.GetString("a06t006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. Tipo de afectación (Selección múltiple):.
        /// </summary>
        public static string a07t001 {
            get {
                return ResourceManager.GetString("a07t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Daño en bienes muebles o inmuebles
        ///2 Fracturas
        ///3 Heridas o laceraciones
        ///4 Infección
        ///5 Muerte
        ///6 Parálisis total o parcial
        ///7 Pérdida de la audición total o parcial
        ///8 Pérdida de la vista total o parcial
        ///9 Pérdida del habla total o parcial
        ///10 Pérdida o amputación de algún miembro u órgano
        ///11 Pérdida total o parcial de la funcionalidad de algún miembro u órgano diferente a vista, audición o habla.
        ///12 Quemaduras
        ///13 Trastornos psicológicos o psiquiátricos que afectan notablemente el funcionamiento o  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a07t002 {
            get {
                return ResourceManager.GetString("a07t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15. Actividad al momento del hecho:.
        /// </summary>
        public static string a07t003 {
            get {
                return ResourceManager.GetString("a07t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Agricultura
        ///2 Ganadería
        ///3 Tránsito por vía inusual
        ///4 Juego
        ///5 Recolección de comida, madera
        ///6 Labores domésticas
        ///7 Militar
        ///8 Erradicación de cultivos ilicitos
        ///9 Desconocida
        ///10 Otra.
        /// </summary>
        public static string a07t004 {
            get {
                return ResourceManager.GetString("a07t004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Fracturas
        ///3 Heridas o laceraciones
        ///4 Infección
        ///5 Muerte
        ///6 Parálisis total o parcial
        ///7 Pérdida de la audición total o parcial
        ///8 Pérdida de la vista total o parcial
        ///9 Pérdida del habla total o parcial.
        /// </summary>
        public static string a08t001 {
            get {
                return ResourceManager.GetString("a08t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Pérdida o amputación de algún miembro u órgano
        ///11 Pérdida total o parcial de la funcionalidad de algún miembro u órgano diferente a vista, audición o habla.
        ///12 Quemaduras
        ///13 Trastornos psicológicos o psiquiátricos que afectan notablemente el funcionamiento o desempeño en las actividades cotidianas
        ///14 Disminución o pérdida de sus fuentes de ingresos
        ///15 Otro.
        /// </summary>
        public static string a08t002 {
            get {
                return ResourceManager.GetString("a08t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En el siguiente cuadro registre como víctima 1 a la persona secuestrada. A continuación, registre a los miembros del grupo familiar de la víctima.
        ///En caso de haber más de una víctima como consecuencia de este mismo hecho, registre cualquiera de las víctimas en la primera fila y continúe diligenciando el grupo familiar de esta persona en los renglones subsiguientes..
        /// </summary>
        public static string a08t003 {
            get {
                return ResourceManager.GetString("a08t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe al (a la) Declarante que el diligenciamiento de este formulario no reemplaza la solicitud de restitución que debe hacerse ante un(a) representante de la Unidad Administrativa Especial de Gestión para la Restitución de Tierras y, por lo tanto, no inicia el trámite de restitución contemplado en la Ley 1448. 
        ///Para efectos de la restitución, oriente al (a la) Declarante para que surta el trámite correspondiente en el punto de atención de la Unidad Administrativa Especial de Gestión para la Restitución  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a11t001 {
            get {
                return ResourceManager.GetString("a11t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Tipo de Inmueble:.
        /// </summary>
        public static string a11t002 {
            get {
                return ResourceManager.GetString("a11t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Tierra / Lote sin vivienda 
        ///2. Tierra / Lote con vivienda.
        /// </summary>
        public static string a11t003 {
            get {
                return ResourceManager.GetString("a11t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Tipo tenencia.
        /// </summary>
        public static string a11t004 {
            get {
                return ResourceManager.GetString("a11t004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Propiedad
        ///2. Posesión
        ///3. Tenencia.
        /// </summary>
        public static string a11t005 {
            get {
                return ResourceManager.GetString("a11t005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 Unidad de área.
        /// </summary>
        public static string a11t006 {
            get {
                return ResourceManager.GetString("a11t006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hectáreas
        ///2 Metro cuadrado 
        ///3 Fanegadas 
        ///4 Plazas.
        /// </summary>
        public static string a11t007 {
            get {
                return ResourceManager.GetString("a11t007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Cuadras
        ///98 No Sabe
        ///99 No Responde.
        /// </summary>
        public static string a11t008 {
            get {
                return ResourceManager.GetString("a11t008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;Nota:&lt;/Run&gt; En caso que la respuesta a la anterior pregunta sea afirmativa (SI), diligencie el formulario único de solicitud individual de protección de predios abandonados a causa de la violencia. Si el (la) Declarante pertenece a un grupo étnico, diligencie el Formulario Único de solicitud de Protección de los Derechos Territoriales de Grupos Étnicos Afectados a Causa de la Violencia. El diligenciamiento de estos formatos es responsabilidad de los(as) representantes del Ministerio P [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a11t009 {
            get {
                return ResourceManager.GetString("a11t009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15. Tipo Bien.
        /// </summary>
        public static string a11t010 {
            get {
                return ResourceManager.GetString("a11t010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Semovientes
        ///2. Muebles, enseres y electrodomésticos
        ///3. Herramientas.
        /// </summary>
        public static string a11t011 {
            get {
                return ResourceManager.GetString("a11t011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Cultivos y plantaciones
        ///5. Maquinaria y vehículos
        ///6. Otros.
        /// </summary>
        public static string a11t012 {
            get {
                return ResourceManager.GetString("a11t012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de acreedor:.
        /// </summary>
        public static string a11t013 {
            get {
                return ResourceManager.GetString("a11t013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Empresa de servicios públicos
        ///2. Tesorería o Hacienda Municipal o Departamental
        ///3. Entidad financiera pública.
        /// </summary>
        public static string a11t014 {
            get {
                return ResourceManager.GetString("a11t014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Entidad financiera privada
        ///5. Persona natural
        ///6. Establecimiento comercial.
        /// </summary>
        public static string a11t015 {
            get {
                return ResourceManager.GetString("a11t015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señor(a) funcionario(a), relacione a continuación los integrantes de un mismo grupo familiar afectado por el hecho declarado en este formato. El campo (7) relación debe ser diligenciado de acuerdo a la relación de parentesco o consanguinidad de cada persona  &lt;Run TextDecorations=&quot;Underline&quot;&gt;con  respecto al Jefe de Hogar&lt;/Run&gt;..
        /// </summary>
        public static string a13t001 {
            get {
                return ResourceManager.GetString("a13t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señor(a) funcionario(a) firme el siguiente comprobante y entréguelo al(a la) declarante..
        /// </summary>
        public static string c01t001 {
            get {
                return ResourceManager.GetString("c01t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de anexos, soportes y folios que hacen parte de la declaración.
        /// </summary>
        public static string c01t002 {
            get {
                return ResourceManager.GetString("c01t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;Confidencialidad de la Información&lt;/Run&gt;: De conformidad con lo dispuesto en el parágrafo 1º del artículo 156 de la Ley 1448 de 2011, con el fin de proteger el derecho a la intimidad de las víctimas y su seguridad, toda la información suministrada con ocasión de esta declaración es de carácter reservado en concordancia con lo establecido en el artículo 15 de la Constitución Política..
        /// </summary>
        public static string c01t003 {
            get {
                return ResourceManager.GetString("c01t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señor declarante recuerde que la Unidad de Atención y Reparación Integral puede tomar hasta 60 días hábiles para tramitar su solicitud de inscripción en el Registro Único de Víctimas, el consecutivo impreso en este documento es el mismo registrado en las 4 hojas básicas del formato de declaración por lo tanto debe mantenerse en perfecto estado para poder realizar el seguimiento correspondiente ante alguna eventualidad, consulta o solicitud, para lo cual puede dirigirse al punto de atención de esta entidad m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string c01t004 {
            get {
                return ResourceManager.GetString("c01t004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Este documento es distribuido por la Unidad Administrativa Especial para la Atención y Reparación Intergral a las Víctimas de manera GRATUITA, por lo cual NO tiene ningún costo para los ciudadanos..
        /// </summary>
        public static string e01t001 {
            get {
                return ResourceManager.GetString("e01t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Administrativa Especial para la Atención y Reparación Integral a las Víctimas.
        /// </summary>
        public static string e01t002 {
            get {
                return ResourceManager.GetString("e01t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORMATO ÚNICO DE DECLARACIÓN PARA LA SOLICITUD DE INSCRIPCIÓN EN EL REGISTRO ÚNICO DE VÍCTIMAS.
        /// </summary>
        public static string e01t003 {
            get {
                return ResourceManager.GetString("e01t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Único de Víctimas.
        /// </summary>
        public static string e01t004 {
            get {
                return ResourceManager.GetString("e01t004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código: F-UAV-001.
        /// </summary>
        public static string e01t005 {
            get {
                return ResourceManager.GetString("e01t005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha aprobación: 2011-12-09.
        /// </summary>
        public static string e01t006 {
            get {
                return ResourceManager.GetString("e01t006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión: 01.
        /// </summary>
        public static string e01t007 {
            get {
                return ResourceManager.GetString("e01t007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión: 02.
        /// </summary>
        public static string e01t008 {
            get {
                return ResourceManager.GetString("e01t008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha aprobación: 18-10-2024.
        /// </summary>
        public static string e01t009 {
            get {
                return ResourceManager.GetString("e01t009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código: 610,05,15-1.
        /// </summary>
        public static string e01t010 {
            get {
                return ResourceManager.GetString("e01t010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;3 Tipo Documento:&lt;/Run&gt;
        ///1 Cédula de Ciudadanía
        ///2 Tarjeta de Identidad
        ///3 Registro Civil
        ///4 Cédula de Extranjería
        ///5 Indocumentado (No ha tramitado su documento)
        ///98 No sabe (NS)-(No recuerda el número)
        ///99 No responde (NR).
        /// </summary>
        public static string eA13t001 {
            get {
                return ResourceManager.GetString("eA13t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;5 Hechos (Selección múltiple):&lt;/Run&gt;.
        /// </summary>
        public static string eA13t002 {
            get {
                return ResourceManager.GetString("eA13t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;7 Relación:&lt;/Run&gt;
        ///1 Jefe(a) de hogar
        ///2 Esposo(a)/Compañero(a)
        ///3 Hijo(a)/Hijastro(a)
        ///4 Hijo(a) de crianza
        ///5 Yerno/Nuera
        ///6 Nieto(a)
        ///7 Nieto(a) de crianza
        ///8 Padre o Madre
        ///9 Padre o Madre de crianza
        ///10 Suegros
        ///11 Cuñados
        ///12 Hermanos (as)
        ///13 Hermanos (as) de crianza
        ///14 Abuelo (a)
        ///15 Abuelo (a) de crianza
        ///16 Otros Parientes
        ///17 No pariente
        ///98 No sabe (NS)/No responde (NR).
        /// </summary>
        public static string eA13t005 {
            get {
                return ResourceManager.GetString("eA13t005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;8 Estado Civil:&lt;/Run&gt;
        ///1 Unión marital de hecho
        ///2 Casado(a)
        ///3 Viudo(a)
        ///4 Separado(a) / Divorciado(a)
        ///5 Soltero(a)
        ///97 Otro
        ///98 No Sabe (NS)
        ///99 No Responde (NR).
        /// </summary>
        public static string eA13t006 {
            get {
                return ResourceManager.GetString("eA13t006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;9 Régimen especial:&lt;/Run&gt;
        ///1 Policia
        ///2 Fuerzas Militares.
        /// </summary>
        public static string eA13t007 {
            get {
                return ResourceManager.GetString("eA13t007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;10 Género:&lt;/Run&gt;
        ///1 Mujer
        ///2 Hombre
        ///3 LGBTI.
        /// </summary>
        public static string eA13t008 {
            get {
                return ResourceManager.GetString("eA13t008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;11 Discapacidad para llevar a cabo una o varias de las siguientes actividades:&lt;/Run&gt;.
        /// </summary>
        public static string eA13t009 {
            get {
                return ResourceManager.GetString("eA13t009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Afectación (Selección múltiple):.
        /// </summary>
        public static string eA13t010 {
            get {
                return ResourceManager.GetString("eA13t010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Daños en bienes o inmuebles 
        ///2 Fracturas
        ///3 Heridas o laceraciones
        ///4 Infección
        ///5 Muerte
        ///6 Parálisis total o parcial
        ///7 Pérdida de la audición total o parcial
        ///8 Pérdida de la vista total o parcial
        ///9 Pérdida del habla total o parcial.
        /// </summary>
        public static string eA13t011 {
            get {
                return ResourceManager.GetString("eA13t011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 Pérdida del habla total o parcial
        ///10 Pérdida o amputación de algún miembro u órgano
        ///11 Pérdida total o parcial de la funcionalidad de algún miembro u órgano diferente a vista, audición o habla.
        ///12 Quemaduras
        ///13 Trastornos psicológicos o psiquiátricos que afectan notablemente el funcionamiento o desempeño en las actividades cotidianas
        ///14 Otro.
        /// </summary>
        public static string eA13t012 {
            get {
                return ResourceManager.GetString("eA13t012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;13 Tipo Documento:&lt;/Run&gt;
        ///1. Registro Civil
        ///2. Tarjeta de Identidad
        ///3. Cédula de Ciudadanía
        ///4. Cédula de Extranjería
        ///5. Pasaporte
        ///6. Documento Extranjero
        ///7. Permiso por Protección Temporal (PPT)
        ///8. Indocumentado
        ///99. Sin Información.
        /// </summary>
        public static string eh02t001 {
            get {
                return ResourceManager.GetString("eh02t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;15 Hechos (Selección múltiple):&lt;/Run&gt;.
        /// </summary>
        public static string eh02t002 {
            get {
                return ResourceManager.GetString("eh02t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Acto terrorista/Atentados/Combates
        ///Enfrentamientos/Hostigamientos
        ///2 Amenaza
        ///3 Delitos contra la libertad y la integridad sexual en desarrollo del conflicto armado
        ///4 Desaparición forzada
        ///5 Desplazamiento forzado
        ///6 Homicidio/Masacre.
        /// </summary>
        public static string eh02t003 {
            get {
                return ResourceManager.GetString("eh02t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Acto terrorista/Atentados/Combates
        ///Enfrentamientos/Hostigamientos
        ///2 Amenaza
        ///3 Delitos contra la libertad y la integridad sexual en desarrollo del conflicto armado
        ///4 Desaparición forzada
        ///5 Desplazamiento forzado
        ///6 Homicidio/Masacre
        ///7 Minas Antipersonal, Munición sin Explotar y Artefacto Explosivo improvisado
        ///8 Secuestro
        ///9 Tortura.
        /// </summary>
        public static string eh02t003_1 {
            get {
                return ResourceManager.GetString("eh02t003_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Minas Antipersonal, Munición sin Explotar y Artefacto Explosivo improvisado
        ///8 Secuestro
        ///9 Tortura
        ///10 Vinculación de Niños Niñas y Adolescentes a Actividades Relacionadas con grupos armados
        ///11 Abandono o Despojo Forzado de Tierras
        ///12 Otro
        ///13 No Víctima.
        /// </summary>
        public static string eh02t004 {
            get {
                return ResourceManager.GetString("eh02t004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Vinculación de Niños Niñas y Adolescentes a Actividades Relacionadas con grupos armados
        ///11 Abandono y/o Despojo Forzado de Bienes Inmueble
        ///12 Abandono y/o Despojo Forzado de Bienes Mueble
        ///13 Formato Censo Masivo
        ///14 Confinamiento
        ///15 Lesiones personales Psicológicas y/o Físicas
        ///16 Otro
        ///17 No Víctima.
        /// </summary>
        public static string eh02t004_1 {
            get {
                return ResourceManager.GetString("eh02t004_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;16 Relación:&lt;/Run&gt;
        ///1 Jefe(a) de hogar
        ///2 Esposo(a)/Compañero(a)
        ///3 Hijo(a)/Hijastro(a)
        ///4 Hijo(a) de crianza
        ///5 Yerno/Nuera
        ///6 Nieto(a)
        ///7 Nieto(a) de crianza
        ///8 Padre o Madre
        ///9 Padre o Madre de crianza
        ///10 Suegros
        ///11 Cuñados
        ///12 Hermanos (as)
        ///13 Hermanos (as) de crianza
        ///14 Abuelo (a)
        ///15 Abuelo (a) de crianza
        ///16 Otros Parientes
        ///17 No pariente
        ///98 No sabe (NS)/No responde (NR).
        /// </summary>
        public static string eh02t005 {
            get {
                return ResourceManager.GetString("eh02t005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;17 Estado Civil:&lt;/Run&gt;
        ///1 Unión marital de hecho
        ///2 Casado(a)
        ///3 Viudo(a)
        ///4 Separado(a) / Divorciado(a)
        ///5 Soltero(a)
        ///97 Otro
        ///98 No Sabe (NS) / No Responde (NR).
        /// </summary>
        public static string eh02t006 {
            get {
                return ResourceManager.GetString("eh02t006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;18 Régimen especial:&lt;/Run&gt;
        ///1 Policia
        ///2 Fuerzas Militares
        ///3 Fuerza Aérea Colombiana
        ///4 Armada Nacional.
        /// </summary>
        public static string eh02t007 {
            get {
                return ResourceManager.GetString("eh02t007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;19 Género:&lt;/Run&gt;
        ///1 Mujer
        ///2 Hombre
        ///3 LGBTI.
        /// </summary>
        public static string eh02t008 {
            get {
                return ResourceManager.GetString("eh02t008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;20 Discapacidad para llevar a cabo una o varias de las siguientes actividades:&lt;/Run&gt;.
        /// </summary>
        public static string eh02t009 {
            get {
                return ResourceManager.GetString("eh02t009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Pensar, memorizar
        ///2 Percibir la luz, distinguir objetos o personas a pesar de usar lentes o gafas
        ///3 Oír, aun con aparatos especiales
        ///4 Distinguir sabores u olores
        ///5 Dificultades para hablar y comunicarse
        ///6 Desplazarse en trechos cortos por problemas respiratorios o de corazón
        ///7 Masticar, tragar, asimilar y transformar los alimentos
        ///8 Retener o expulsar la orina, tener relaciones sexuales, tener hijos.
        /// </summary>
        public static string eh02t010 {
            get {
                return ResourceManager.GetString("eh02t010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 Caminar, correr, saltar
        ///10 Mantener piel, uñas y cabellos sanos
        ///11 Relacionarse con las demás personas y el entorno
        ///12 Llevar, mover, utilizar objetos con las manos
        ///13 Cambiar y mantener las posiciones del cuerpo
        ///14 Alimentarse, asearse y vestirse por sí mismo
        ///15 Otra
        ///16 Ninguna
        ///98 No Sabe (NS)
        ///99 No Responde (NR).
        /// </summary>
        public static string eh02t011 {
            get {
                return ResourceManager.GetString("eh02t011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señor(a) funcionario(a), en el siguiente cuadro relacione los datos de todas las personas que hayan resultado afectadas por los hechos referidos en esta Declaración.
        ///El campo 16 (Relación) debe ser diligenciado de acuerdo a la relación de parentesco o consanguinidad de cada persona &lt;Run FontWeight=&quot;Bold&quot;&gt;con respecto al declarante&lt;/Run&gt;..
        /// </summary>
        public static string eh02t012 {
            get {
                return ResourceManager.GetString("eh02t012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Física
        ///2. Auditiva 
        ///3. Sordo Ceguera
        ///4. Intelectual
        ///5. Visual
        ///6. Psicosocial (mental)
        ///7. Múltiple
        ///15 Otra
        ///16 Ninguna
        ///98 No Sabe (NS) / No Responde (NR).
        /// </summary>
        public static string eh02t013 {
            get {
                return ResourceManager.GetString("eh02t013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;19 Sexo:&lt;/Run&gt;
        ///1. Mujer
        ///2. Hombre
        ///3. Intersexual
        ///98. No sabe/No responde.
        /// </summary>
        public static string eh02t014 {
            get {
                return ResourceManager.GetString("eh02t014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;19 Orientación Sexual:&lt;/Run&gt;
        ///1. Heterosexual
        ///2. Homosexual (Lesbiana-Gay)
        ///3. Bisexual
        ///4. Asexual
        ///5. Pansexual
        ///98. No sabe/no responde.
        /// </summary>
        public static string eh02t015 {
            get {
                return ResourceManager.GetString("eh02t015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;19 Identidad de Género:&lt;/Run&gt;
        ///1. Masculino
        ///2. Femenino
        ///3. Hombre trans
        ///4. Mujer trans
        ///5. Persona no binaria
        ///6. Género fluido
        ///98. No sabe / No responde.
        /// </summary>
        public static string eh02t016 {
            get {
                return ResourceManager.GetString("eh02t016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señor(a) funcionario(a), realice una entrevista previa al (a la) declarante con el fin de orientarlo(a) sobre el propósito y alcance de esta diligencia y de identificar los hechos victimizantes a los que se hará referencia..
        /// </summary>
        public static string h01t001 {
            get {
                return ResourceManager.GetString("h01t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * En los costados se han señalado los campos cuyo diligenciamiento es obligatorio. 
        ///Por favor &lt;Run TextDecorations=&quot;Underline&quot;&gt;NO&lt;/Run&gt; remita este formato sin diligenciar estos campos en su totalidad..
        /// </summary>
        public static string h01t002 {
            get {
                return ResourceManager.GetString("h01t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con el propósito de acceder a los beneficios que trata la Ley 1448 del 2011 y demás normas que la adicionan modifican o reforman, el (la) declarante jura decir la verdad, sólo la verdad y nada más que la verdad en lo que va a declarar..
        /// </summary>
        public static string h01t003 {
            get {
                return ResourceManager.GetString("h01t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señor(a) funcionario(a), recuérdele al (a la) solicitante que los trámites que realice ante la Unidad Administrativa Especial para la Atención y Reparación Integral a las víctimas no tienen ningún costo y no requieren de intermediarios o apoderados..
        /// </summary>
        public static string h01t004 {
            get {
                return ResourceManager.GetString("h01t004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señor(a) funcionario(a) diligencie la pregunta 4 de acuerdo con la siguiente información: Recuerde su deber de garantizar las condiciones para la toma de la declaración en los siguientes casos: 
        ///
        ///1. Si detecta que el (la) declarante no habla el español y requiere de un intérprete. 
        ///2. Si la declaración va a ser presentada por un menor de edad, para lo cual el (la) niño, niña o adolescente deberá presentarse con su tutor. A falta de éste, el (la) niño, niña o adolescente, deberá estar acompañado por el fu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string h01t005 {
            get {
                return ResourceManager.GetString("h01t005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Autorizo para que instituciones del estado, a través de los medios señalados a continuación, me envíen información sobre el acceso a medidas de atención, asistencia y reparación, lo cual se realizará sin que me genere ningún costo adicional&quot;..
        /// </summary>
        public static string h01t006 {
            get {
                return ResourceManager.GetString("h01t006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Declaro que los datos personales suministrados en este formato son verídicos y autorizo expresamente su recolección, almacenamiento y tratamiento, de conformidad con lo establecido en la Ley de Habeas Data (Ley 1581 de 2012) y sus disposiciones reglamentarias. Entiendo que los datos proporcionados serán utilizados únicamente para los fines relacionados con la aplicación y cumplimiento de la Ley 1448 de 2011 y los programas de asistencia, atención y reparación integral a las víctimas. Asimismo, me compromet [rest of string was truncated]&quot;;.
        /// </summary>
        public static string h01t006V2 {
            get {
                return ResourceManager.GetString("h01t006V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señor(a) funcionario(a): Diligencie en la siguiente hoja la caracterización básica de las personas a que se refieren los hechos relacionados en el cuadro anterior. A continuación, diligencie un anexo por cada hecho. Finalmente, tome la narración general de los hechos con base en las preguntas guía indicadas al respaldo de cada hoja y diligencie la hoja de verificación (Hoja 4)..
        /// </summary>
        public static string h01t007 {
            get {
                return ResourceManager.GetString("h01t007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Señor(a) funcionario(a), en el siguiente cuadro relacione los datos de todas las personas que hayan resultado afectadas por los hechos referidos en esta Declaración.
        ///El campo 16 (Relación) debe ser diligenciado de acuerdo a la relación de parentesco o consanguinidad de cada persona &lt;Run TextDecorations=&quot;Underline&quot;&gt;con respecto al declarante&lt;/Run&gt;..
        /// </summary>
        public static string h02t001 {
            get {
                return ResourceManager.GetString("h02t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;*Describa las circunstancias de tiempo, modo y lugar en que se dieron los hechos:&lt;/Run&gt; Oriente la declaración de modo tal que la narración describa con &lt;Run FontWeight=&quot;Bold&quot;&gt;suficiencia&lt;/Run&gt; el modo en que ocurrieron los hechos, así como los antecedentes, elementos relevantes y fuentes de verificación de la información..
        /// </summary>
        public static string h03t001 {
            get {
                return ResourceManager.GetString("h03t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Señor(a) funcionario(a): Con el fin de mejorar la calidad de la información recopilada y de facilitar la valoración de esta solicitud, puede orientar la narración de los hechos con las preguntas guía que se encuentran al respaldo de los Anexos 1 a 11 de este Formato, según el (los) hecho(s) victimizante(s) a que se refiera esta declaración..
        /// </summary>
        public static string h03t002 {
            get {
                return ResourceManager.GetString("h03t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;Observaciones:&lt;/Run&gt; Señor(a) funcionario(a): Escriba las observaciones sobre el diligenciamiento del formato que considere pertinentes..
        /// </summary>
        public static string h04t001 {
            get {
                return ResourceManager.GetString("h04t001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;Confidencialidad de la Información:&lt;/Run&gt; De conformidad con lo dispuesto en el parágrafo  1º  del artículo 156 de la Ley 1448 de  2011, con el fin de proteger el derecho a la intimidad de las víctimas y su seguridad, toda la información suministrada con ocasión de esta Declaración es de carácter reservado en concordancia con lo establecido en el artículo 15 de la Constitución Política..
        /// </summary>
        public static string h04t002 {
            get {
                return ResourceManager.GetString("h04t002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;Confidencialidad de la Información:&lt;/Run&gt; Confidencialidad de la información y tratamiento de datos: De conformidad con lo dispuesto en el parágrafo 1 del artículo 156 de la Ley 1448 de 2011, con el fin de proteger el derecho a la intimidad de las víctimas y su seguridad, toda la información suministrada con ocasión de esta Declaración es de carácter reservado en concordancia con lo establecido en el artículo 19 de la constitución. Asimismo, y teniendo en cuenta la sensibilidad de los [rest of string was truncated]&quot;;.
        /// </summary>
        public static string h04t002V2 {
            get {
                return ResourceManager.GetString("h04t002V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No siendo otro el objeto de la presente declaración se lee y firma por quienes en ella intervienen:*Favor diligenciar todos los campos sin excepción con letra legible..
        /// </summary>
        public static string h04t003 {
            get {
                return ResourceManager.GetString("h04t003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string h04t003V2 {
            get {
                return ResourceManager.GetString("h04t003V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifiesto que el funcionario público que tomó mi declaración me orientó sobre el trámite de esta diligencia..
        /// </summary>
        public static string h04t004 {
            get {
                return ResourceManager.GetString("h04t004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor registre a continuación si el declarante sabe o no firmar 
        ///(En caso negativo tome la huella dactilar).
        /// </summary>
        public static string h04t005 {
            get {
                return ResourceManager.GetString("h04t005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;Señor (a) funcionario (a):&lt;/Run&gt; antes de remitir esta declaración a la Unidad Administrativa Especial para la Atención y Reparación Integral a las Víctimas, asegúrese de que todos los campos marcados como obligatorios estén diligenciados en su totalidad..
        /// </summary>
        public static string h04t006 {
            get {
                return ResourceManager.GetString("h04t006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Run FontWeight=&quot;Bold&quot;&gt;Intérprete:&lt;/Run&gt; Con la presente firma, el intérprete, en aquellos casos en que fue autorizado por la autoridad competente, da fe que asistió de forma adecuada al  (a la) declarante, permitiéndole entender los alcances de esta diligencia y facilitando que los hechos narrados hayan quedado debidamente registrados en el presente Formato.
        ///
        ///&lt;Run FontWeight=&quot;Bold&quot;&gt;Tutor o representante legal:&lt;/Run&gt; Con la presente firma, el representante legal da fe que el &lt;Run TextDecorations=&quot;Underlin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string h04t007 {
            get {
                return ResourceManager.GetString("h04t007", resourceCulture);
            }
        }
    }
}
