//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.WPF.Captura.WSComunicacionSiravRuv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRespuesta", Namespace="http://schemas.datacontract.org/2004/07/WcfComunicacionSiravRuv")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ruv.WPF.Captura.WSComunicacionSiravRuv.RadicadoSirav))]
    public partial class BaseRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RadicadoSirav", Namespace="http://schemas.datacontract.org/2004/07/WcfComunicacionSiravRuv")]
    [System.SerializableAttribute()]
    public partial class RadicadoSirav : Ruv.WPF.Captura.WSComunicacionSiravRuv.BaseRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSComunicacionSiravRuv.IComunicacionSiravRuv")]
    public interface IComunicacionSiravRuv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComunicacionSiravRuv/GuardarRadicadoEntradaBPM", ReplyAction="http://tempuri.org/IComunicacionSiravRuv/GuardarRadicadoEntradaBPMResponse")]
        Ruv.WPF.Captura.WSComunicacionSiravRuv.RadicadoSirav GuardarRadicadoEntradaBPM(string radicado, string numFud, string fecha, System.Nullable<int> tipoRad, System.Nullable<int> conceptoId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComunicacionSiravRuvChannel : Ruv.WPF.Captura.WSComunicacionSiravRuv.IComunicacionSiravRuv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComunicacionSiravRuvClient : System.ServiceModel.ClientBase<Ruv.WPF.Captura.WSComunicacionSiravRuv.IComunicacionSiravRuv>, Ruv.WPF.Captura.WSComunicacionSiravRuv.IComunicacionSiravRuv {
        
        public ComunicacionSiravRuvClient() {
        }
        
        public ComunicacionSiravRuvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComunicacionSiravRuvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComunicacionSiravRuvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComunicacionSiravRuvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ruv.WPF.Captura.WSComunicacionSiravRuv.RadicadoSirav GuardarRadicadoEntradaBPM(string radicado, string numFud, string fecha, System.Nullable<int> tipoRad, System.Nullable<int> conceptoId) {
            return base.Channel.GuardarRadicadoEntradaBPM(radicado, numFud, fecha, tipoRad, conceptoId);
        }
    }
}
