//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.WPF.Captura.ControlDocumentosService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControlDocumentosService.IControlDocumentosService")]
    public interface IControlDocumentosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/GenerarFormularios", ReplyAction="http://tempuri.org/IControlDocumentosService/GenerarFormulariosResponse")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] GenerarFormularios(uint nCantidad, string cSerie, int nIdUsuario, int nIdEstado, System.Nullable<int> nIdPais, System.Nullable<int> nIdDepartamento, System.Nullable<int> nIdMunicipio, System.Nullable<int> nIdEntidadmunicipio, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/GenerarFormulariosWEB", ReplyAction="http://tempuri.org/IControlDocumentosService/GenerarFormulariosWEBResponse")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] GenerarFormulariosWEB(uint nCantidad, string cSerie, int nIdUsuario, int nIdEstado, System.Nullable<int> nIdEntidadmunicipio, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/ObtenerPaisGeneraFormularioWEB", ReplyAction="http://tempuri.org/IControlDocumentosService/ObtenerPaisGeneraFormularioWEBRespon" +
            "se")]
        int ObtenerPaisGeneraFormularioWEB(System.Nullable<int> nIdEntidadmunicipio, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/ListarFormularios", ReplyAction="http://tempuri.org/IControlDocumentosService/ListarFormulariosResponse")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ListarFormularios(ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/ListarFormulariosNoRadicados", ReplyAction="http://tempuri.org/IControlDocumentosService/ListarFormulariosNoRadicadosResponse" +
            "")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ListarFormulariosNoRadicados(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormularioSolicitudNoRadicados frmSolicitud, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/ListarFormulariosPorEstado", ReplyAction="http://tempuri.org/IControlDocumentosService/ListarFormulariosPorEstadoResponse")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ListarFormulariosPorEstado(ushort nIdEstado, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/AsignarFormulario", ReplyAction="http://tempuri.org/IControlDocumentosService/AsignarFormularioResponse")]
        void AsignarFormulario(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] FormulariosEnviar, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/AsignarFormularioFiltro", ReplyAction="http://tempuri.org/IControlDocumentosService/AsignarFormularioFiltroResponse")]
        bool AsignarFormularioFiltro(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSolicitudFormularioEstado frm, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/InactivarFormulario", ReplyAction="http://tempuri.org/IControlDocumentosService/InactivarFormularioResponse")]
        System.Nullable<uint> InactivarFormulario(uint nIdFormulario, string observacion, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/SepararFormularioImprenta", ReplyAction="http://tempuri.org/IControlDocumentosService/SepararFormularioImprentaResponse")]
        void SepararFormularioImprenta(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSeparacionFormularioSolicitud[] frmFormularioASeparar, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/SepararFormularioImprentaFiltro", ReplyAction="http://tempuri.org/IControlDocumentosService/SepararFormularioImprentaFiltroRespo" +
            "nse")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSeparacionFormularioSolicitud[] SepararFormularioImprentaFiltro(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSolicitudFormularioEstado frm, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/ObtenerFormulariosPorUsuario", ReplyAction="http://tempuri.org/IControlDocumentosService/ObtenerFormulariosPorUsuarioResponse" +
            "")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ObtenerFormulariosPorUsuario(int nIdUsuario, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/MarcarDescargado", ReplyAction="http://tempuri.org/IControlDocumentosService/MarcarDescargadoResponse")]
        System.Nullable<uint> MarcarDescargado(uint nIdFormulario, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/MarcarRadicado", ReplyAction="http://tempuri.org/IControlDocumentosService/MarcarRadicadoResponse")]
        bool MarcarRadicado(string cNumeroFormulario, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/ValidarNumeroFormulario", ReplyAction="http://tempuri.org/IControlDocumentosService/ValidarNumeroFormularioResponse")]
        Ruv.Infrastructure.Crosscutting.Common.eResultadoValidacionRadicacion ValidarNumeroFormulario(Ruv.Infrastructure.Crosscutting.Common.Entidades.clsRadicacion radicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/ObtenerFormulariosPorUsuarioEstadoPa" +
            "ginado", ReplyAction="http://tempuri.org/IControlDocumentosService/ObtenerFormulariosPorUsuarioEstadoPa" +
            "ginadoResponse")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ObtenerFormulariosPorUsuarioEstadoPaginado(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSolicitudFormularioEstado frm, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/ObtenerCantidadFormulariosPorUsuario" +
            "Estado", ReplyAction="http://tempuri.org/IControlDocumentosService/ObtenerCantidadFormulariosPorUsuario" +
            "EstadoResponse")]
        int ObtenerCantidadFormulariosPorUsuarioEstado(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSolicitudFormularioEstado frm, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/ObtenerCantidadFormulariosActivar", ReplyAction="http://tempuri.org/IControlDocumentosService/ObtenerCantidadFormulariosActivarRes" +
            "ponse")]
        int ObtenerCantidadFormulariosActivar(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormularioSolicitudNoRadicados Solicitud, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/ObtenerFormulariosActivar", ReplyAction="http://tempuri.org/IControlDocumentosService/ObtenerFormulariosActivarResponse")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ObtenerFormulariosActivar(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormularioSolicitudNoRadicados Solicitud, int nPagina, int nTamaño, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlDocumentosService/ObtenerFormulario", ReplyAction="http://tempuri.org/IControlDocumentosService/ObtenerFormularioResponse")]
        Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario ObtenerFormulario(string cNumeroFormulario, ref string cError);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControlDocumentosServiceChannel : Ruv.WPF.Captura.ControlDocumentosService.IControlDocumentosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlDocumentosServiceClient : System.ServiceModel.ClientBase<Ruv.WPF.Captura.ControlDocumentosService.IControlDocumentosService>, Ruv.WPF.Captura.ControlDocumentosService.IControlDocumentosService {
        
        public ControlDocumentosServiceClient() {
        }
        
        public ControlDocumentosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControlDocumentosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlDocumentosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlDocumentosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] GenerarFormularios(uint nCantidad, string cSerie, int nIdUsuario, int nIdEstado, System.Nullable<int> nIdPais, System.Nullable<int> nIdDepartamento, System.Nullable<int> nIdMunicipio, System.Nullable<int> nIdEntidadmunicipio, ref string cError) {
            return base.Channel.GenerarFormularios(nCantidad, cSerie, nIdUsuario, nIdEstado, nIdPais, nIdDepartamento, nIdMunicipio, nIdEntidadmunicipio, ref cError);
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] GenerarFormulariosWEB(uint nCantidad, string cSerie, int nIdUsuario, int nIdEstado, System.Nullable<int> nIdEntidadmunicipio, ref string cError) {
            return base.Channel.GenerarFormulariosWEB(nCantidad, cSerie, nIdUsuario, nIdEstado, nIdEntidadmunicipio, ref cError);
        }
        
        public int ObtenerPaisGeneraFormularioWEB(System.Nullable<int> nIdEntidadmunicipio, ref string cError) {
            return base.Channel.ObtenerPaisGeneraFormularioWEB(nIdEntidadmunicipio, ref cError);
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ListarFormularios(ref string cError) {
            return base.Channel.ListarFormularios(ref cError);
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ListarFormulariosNoRadicados(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormularioSolicitudNoRadicados frmSolicitud, ref string cError) {
            return base.Channel.ListarFormulariosNoRadicados(frmSolicitud, ref cError);
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ListarFormulariosPorEstado(ushort nIdEstado, ref string cError) {
            return base.Channel.ListarFormulariosPorEstado(nIdEstado, ref cError);
        }
        
        public void AsignarFormulario(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] FormulariosEnviar, ref string cError) {
            base.Channel.AsignarFormulario(FormulariosEnviar, ref cError);
        }
        
        public bool AsignarFormularioFiltro(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSolicitudFormularioEstado frm, ref string cError) {
            return base.Channel.AsignarFormularioFiltro(frm, ref cError);
        }
        
        public System.Nullable<uint> InactivarFormulario(uint nIdFormulario, string observacion, ref string cError) {
            return base.Channel.InactivarFormulario(nIdFormulario, observacion, ref cError);
        }
        
        public void SepararFormularioImprenta(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSeparacionFormularioSolicitud[] frmFormularioASeparar, ref string cError) {
            base.Channel.SepararFormularioImprenta(frmFormularioASeparar, ref cError);
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSeparacionFormularioSolicitud[] SepararFormularioImprentaFiltro(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSolicitudFormularioEstado frm, ref string cError) {
            return base.Channel.SepararFormularioImprentaFiltro(frm, ref cError);
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ObtenerFormulariosPorUsuario(int nIdUsuario, ref string cError) {
            return base.Channel.ObtenerFormulariosPorUsuario(nIdUsuario, ref cError);
        }
        
        public System.Nullable<uint> MarcarDescargado(uint nIdFormulario, ref string cError) {
            return base.Channel.MarcarDescargado(nIdFormulario, ref cError);
        }
        
        public bool MarcarRadicado(string cNumeroFormulario, ref string cError) {
            return base.Channel.MarcarRadicado(cNumeroFormulario, ref cError);
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.eResultadoValidacionRadicacion ValidarNumeroFormulario(Ruv.Infrastructure.Crosscutting.Common.Entidades.clsRadicacion radicacion) {
            return base.Channel.ValidarNumeroFormulario(radicacion);
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ObtenerFormulariosPorUsuarioEstadoPaginado(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSolicitudFormularioEstado frm, ref string cError) {
            return base.Channel.ObtenerFormulariosPorUsuarioEstadoPaginado(frm, ref cError);
        }
        
        public int ObtenerCantidadFormulariosPorUsuarioEstado(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsSolicitudFormularioEstado frm, ref string cError) {
            return base.Channel.ObtenerCantidadFormulariosPorUsuarioEstado(frm, ref cError);
        }
        
        public int ObtenerCantidadFormulariosActivar(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormularioSolicitudNoRadicados Solicitud, ref string cError) {
            return base.Channel.ObtenerCantidadFormulariosActivar(Solicitud, ref cError);
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario[] ObtenerFormulariosActivar(Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormularioSolicitudNoRadicados Solicitud, int nPagina, int nTamaño, ref string cError) {
            return base.Channel.ObtenerFormulariosActivar(Solicitud, nPagina, nTamaño, ref cError);
        }
        
        public Ruv.Infrastructure.Crosscutting.Common.Entidades.GestionFormulario.clsFormulario ObtenerFormulario(string cNumeroFormulario, ref string cError) {
            return base.Channel.ObtenerFormulario(cNumeroFormulario, ref cError);
        }
    }
}
