//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.WPF.Captura.PdfHelperServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsDatosparaDevolucion", Namespace="http://schemas.datacontract.org/2004/07/Ruv.Business.DTO.Devolucion")]
    [System.SerializableAttribute()]
    public partial class clsDatosparaDevolucion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNombreDeclaranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CParteEmotivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DFechaDeclaracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DFechaDevolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NIdDeclaracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cEntidadMunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cMunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cNumeroActoAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cTipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nNumeroDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNombreDeclarante {
            get {
                return this.CNombreDeclaranteField;
            }
            set {
                if ((object.ReferenceEquals(this.CNombreDeclaranteField, value) != true)) {
                    this.CNombreDeclaranteField = value;
                    this.RaisePropertyChanged("CNombreDeclarante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CParteEmotiva {
            get {
                return this.CParteEmotivaField;
            }
            set {
                if ((object.ReferenceEquals(this.CParteEmotivaField, value) != true)) {
                    this.CParteEmotivaField = value;
                    this.RaisePropertyChanged("CParteEmotiva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DFechaDeclaracion {
            get {
                return this.DFechaDeclaracionField;
            }
            set {
                if ((this.DFechaDeclaracionField.Equals(value) != true)) {
                    this.DFechaDeclaracionField = value;
                    this.RaisePropertyChanged("DFechaDeclaracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DFechaDevolucion {
            get {
                return this.DFechaDevolucionField;
            }
            set {
                if ((this.DFechaDevolucionField.Equals(value) != true)) {
                    this.DFechaDevolucionField = value;
                    this.RaisePropertyChanged("DFechaDevolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NIdDeclaracion {
            get {
                return this.NIdDeclaracionField;
            }
            set {
                if ((this.NIdDeclaracionField.Equals(value) != true)) {
                    this.NIdDeclaracionField = value;
                    this.RaisePropertyChanged("NIdDeclaracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cEntidadMunicipio {
            get {
                return this.cEntidadMunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.cEntidadMunicipioField, value) != true)) {
                    this.cEntidadMunicipioField = value;
                    this.RaisePropertyChanged("cEntidadMunicipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cMunicipio {
            get {
                return this.cMunicipioField;
            }
            set {
                if ((object.ReferenceEquals(this.cMunicipioField, value) != true)) {
                    this.cMunicipioField = value;
                    this.RaisePropertyChanged("cMunicipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cNumeroActoAdmin {
            get {
                return this.cNumeroActoAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.cNumeroActoAdminField, value) != true)) {
                    this.cNumeroActoAdminField = value;
                    this.RaisePropertyChanged("cNumeroActoAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cTipoDocumento {
            get {
                return this.cTipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.cTipoDocumentoField, value) != true)) {
                    this.cTipoDocumentoField = value;
                    this.RaisePropertyChanged("cTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nNumeroDocumento {
            get {
                return this.nNumeroDocumentoField;
            }
            set {
                if ((this.nNumeroDocumentoField.Equals(value) != true)) {
                    this.nNumeroDocumentoField = value;
                    this.RaisePropertyChanged("nNumeroDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PdfHelperServiceReference.IPdfHelperService")]
    public interface IPdfHelperService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPdfHelperService/GenerateOnePdfFile", ReplyAction="http://tempuri.org/IPdfHelperService/GenerateOnePdfFileResponse")]
        byte[] GenerateOnePdfFile(string codigo, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPdfHelperService/GenerateManyPdfFilesAsZip", ReplyAction="http://tempuri.org/IPdfHelperService/GenerateManyPdfFilesAsZipResponse")]
        byte[] GenerateManyPdfFilesAsZip(System.Collections.Generic.Dictionary<string, bool> codigos, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPdfHelperService/GeneratePdf", ReplyAction="http://tempuri.org/IPdfHelperService/GeneratePdfResponse")]
        byte[] GeneratePdf(string contenido, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPdfHelperService/GeneratePdfDevolucion", ReplyAction="http://tempuri.org/IPdfHelperService/GeneratePdfDevolucionResponse")]
        byte[] GeneratePdfDevolucion(Ruv.WPF.Captura.PdfHelperServiceReference.clsDatosparaDevolucion datosparaDevolucion, ref string cError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPdfHelperService/GenerateOnePdfFileConNacional", ReplyAction="http://tempuri.org/IPdfHelperService/GenerateOnePdfFileConNacionalResponse")]
        byte[] GenerateOnePdfFileConNacional(string codigo, ref string cError);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPdfHelperServiceChannel : Ruv.WPF.Captura.PdfHelperServiceReference.IPdfHelperService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PdfHelperServiceClient : System.ServiceModel.ClientBase<Ruv.WPF.Captura.PdfHelperServiceReference.IPdfHelperService>, Ruv.WPF.Captura.PdfHelperServiceReference.IPdfHelperService {
        
        public PdfHelperServiceClient() {
        }
        
        public PdfHelperServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PdfHelperServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PdfHelperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PdfHelperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GenerateOnePdfFile(string codigo, ref string cError) {
            return base.Channel.GenerateOnePdfFile(codigo, ref cError);
        }
        
        public byte[] GenerateManyPdfFilesAsZip(System.Collections.Generic.Dictionary<string, bool> codigos, ref string cError) {
            return base.Channel.GenerateManyPdfFilesAsZip(codigos, ref cError);
        }
        
        public byte[] GeneratePdf(string contenido, ref string cError) {
            return base.Channel.GeneratePdf(contenido, ref cError);
        }
        
        public byte[] GeneratePdfDevolucion(Ruv.WPF.Captura.PdfHelperServiceReference.clsDatosparaDevolucion datosparaDevolucion, ref string cError) {
            return base.Channel.GeneratePdfDevolucion(datosparaDevolucion, ref cError);
        }
        
        public byte[] GenerateOnePdfFileConNacional(string codigo, ref string cError) {
            return base.Channel.GenerateOnePdfFileConNacional(codigo, ref cError);
        }
    }
}
