UPDATE TBVALIDACIONESESTADO SET VALOR = 1 WHERE NOMBREHOJA = 'Anexo 11'  AND PROPIEDAD = 'BienesMuebles'; 
UPDATE TBVALIDACIONESESTADO SET VALOR = 0 WHERE NOMBREHOJA = 'HOJA 4'  AND PROPIEDAD in( 'DeclaranteSabeFirmar', 'HuboOrientacionParaCorregir');
COMMIT;