--PERSONERIA UAO RAFAEL URIBE URIBE
UPDATE tbentidadmunicipio 
   set nombre = 'PERSONERIA DIGNIFICAR RAFAEL URIBE',
       nombreencargado = 'PERSONERIA DIGNIFICAR RAFAEL URIBE'
where id = 1316;

--PERSONERIA UAO PER. UAO BOSA
UPDATE tbentidadmunicipio 
   set nombre = 'PERSONERIA DIGNIFICAR BOSA',
       nombreencargado = 'PERSONERIA DIGNIFICAR BOSA'
where id = 1128;

--PERSONERIA DELEGADA PARA LOS DERECHOS HUMANOS
UPDATE tbentidadmunicipio 
   set nombre = 'PERSONERIA DELEGADA PARA LAS VICTIMAS',
       nombreencargado = 'PERSONERIA DELEGADA PARA LAS VICTIMAS'
where id = 1106;

--PERSONERIA UAO PER. UAO CIUDAD BOLIVAR
UPDATE tbentidadmunicipio 
   set nombre = 'PERSONERIA DIGNIFICAR CIUDAD BOLIVAR',
       nombreencargado = 'PERSONERIA DIGNIFICAR CIUDAD BOLIVAR'
where id = 1;

--PERSONERIA DIGNIFICAR PUENTE ARANDA
UPDATE tbentidadmunicipio 
   set nombre = 'PERSONERIA DIGNIFICAR PUENTE ARANDA',
       nombreencargado = 'PERSONERIA DIGNIFICAR PUENTE ARANDA'
where id = 2;

--PERSONERIA UAO SUBA
UPDATE tbentidadmunicipio 
   set nombre = 'PERSONERIA DIGNIFICAR SUBA',
       nombreencargado = 'PERSONERIA DIGNIFICAR SUBA'
where id = 4;

--PERSONERIA UAO PER. UAO TERMINAL
UPDATE tbentidadmunicipio 
   set nombre = 'PERSONERIA DIGNIFICAR TERMINAL DE TRANSPORTES',
       nombreencargado = 'PERSONERIA DIGNIFICAR TERMINAL DE TRANSPORTES'
where id = 5;

INSERT INTO TBENTIDADMUNICIPIO VALUES(3760,1,7244,'PROCURADURIA PROVINCIAL','PROCURADURIA PROVINCIAL',NULL,NULL,NULL,0);           

commit;