INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, 2481, 'CONSULADO EN BRUSELAS', 'CONSULADO EN BRUSELAS', 'Avenue Louise 326, Blue Tower Building, 1050 Bruxelles - Belgique', 0);

INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, 2861, 'CONSULADO EN ANTOFAGASTA', 'CONSULADO EN ANTOFAGASTA', 'Calle Libertador Bernardo O''Higgins Nº 1291, Antofagasta', 0);	

INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, 2909, 'CONSULADO EN ESMERALDAS', 'CONSULADO EN ESMERALDAS', 'Calle Antonio Guerra No. 2 - 01 y BarbisottI, Esquina, Barrio las Palmas . Esmeraldas', 0); 

--INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
--VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, , 'CONSULADO EN NUEVA LOJA', 'CONSULADO EN NUEVA LOJA', 'Avenida Quito y Colombia, Edificio Moncada piso 4, Nueva Loja', 0); 

--INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
--VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, , 'CONSULADO EN SANTO DOMINGO DE LOS TSACHILAS', 'CONSULADO EN SANTO DOMINGO DE LOS TSACHILAS', 'Av. Esmeraldas y Calle Las Provincias 2do. Piso Santo', 0); 

INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, 2367, 'CONSULADO EN ABU DHABI', 'CONSULADO EN ABU DHABI (EMIRATOS ARABES UNIDOS)', 'Al Bateen Area, Villa 1 West 39, Plot No. 55. PO Box 60376', 0); 

INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, 3224, 'CONSULADO EN GUATEMALA', 'CONSULADO EN GUATEMALA', '5 Avenida 5-55 Zona 14 Edificio Europlaza Torre 1 Oficina 1603', 0); 

INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, 3257, 'CONSULADO EN YAKARTA', 'CONSULADO EN YAKARTA (INDONESIA)', 'Jl. Jend Sudirman Kav. 47, Piso 12, Jakarta, Indonesia', 0); 

INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, 6363, 'CONSULADO EN ARUBA', 'CONSULADO EN ARUBA (PAISES BAJOS)', 'Juliana Straat 4 Oranjestad - Aruba', 0);

INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, 4192, 'CONSULADO EN SHANGHAI', 'CONSULADO EN SHANGHAI (REPÚBLICA POPULAR DE CHINA)', '518 Anyuan Road, Baohua City Center, 20th Floor, Suite 2005, Shanghai 200060 P.R. of China', 0); 

INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, 5312, 'CONSULADO EN ESTOCOLMO', 'CONSULADO EN ESTOCOLMO(SUECIA)', 'Östermalsgatan 44 Piso- 1 - 114 26 - Estocolmo', 0);

INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, 5600, 'CONSULADO EN PUERTO ESPAÑA', 'CONSULADO EN PUERTO ESPAÑA (TRINIDAD Y TOBAGO)', 'Fourth Floor, Newtown Centre, 30-36 Maraval Road, Port of Spain, Trinidad and Tobago', 0);

INSERT INTO TBENTIDADMUNICIPIO(ID,ID_ENTIDAD,ID_MUNICIPIO,NOMBRE,NOMBREENCARGADO,DIRECCIONENTIDAD,ESPUNTONOTIFICACION)
VALUES(SEQ_TBENTIDADMUNICIPIO.NEXTVAL, 4, 5622, 'CONSULADO EN ANKARA', 'CONSULADO EN ANKARA (TURQUÍA)', 'Koza Sokak No. 91/5 Gaziosmanpasa, Çankaya, Ankara', 0);

COMMIT;