//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.Infrastructure.Crosscutting.Resources.DB {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Parametros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parametros() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruv.Infrastructure.Crosscutting.Resources.DB.Parametros", typeof(Parametros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Accion.
        /// </summary>
        public static string ActivarOInactivar {
            get {
                return ResourceManager.GetString("ActivarOInactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Ano.
        /// </summary>
        public static string Ano {
            get {
                return ResourceManager.GetString("Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_BusquedaGlobal.
        /// </summary>
        public static string BusquedaGlobal {
            get {
                return ResourceManager.GetString("BusquedaGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_CamposCorrecciones.
        /// </summary>
        public static string CamposCorrecciones {
            get {
                return ResourceManager.GetString("CamposCorrecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDSCAUSALES.
        /// </summary>
        public static string CausalesDevolucion {
            get {
                return ResourceManager.GetString("CausalesDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDCODIGOGUIA.
        /// </summary>
        public static string codigoguia {
            get {
                return ResourceManager.GetString("codigoguia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pi_codIntegradorGD.
        /// </summary>
        public static string CodIntegradorGD {
            get {
                return ResourceManager.GetString("CodIntegradorGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_COMUNIDAD.
        /// </summary>
        public static string Comunidad {
            get {
                return ResourceManager.GetString("Comunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_ContarCero.
        /// </summary>
        public static string ContarCero {
            get {
                return ResourceManager.GetString("ContarCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_CORREOELECTRONICO.
        /// </summary>
        public static string Correoelectronico {
            get {
                return ResourceManager.GetString("Correoelectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_CUALETNIAOPUEBLO.
        /// </summary>
        public static string Cualetnia {
            get {
                return ResourceManager.GetString("Cualetnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Declaracion.
        /// </summary>
        public static string Declaracion {
            get {
                return ResourceManager.GetString("Declaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_DepartamentoNotificacion.
        /// </summary>
        public static string DepartamentoNotificacion {
            get {
                return ResourceManager.GetString("DepartamentoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Descripcion.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_DESCRIPCION.
        /// </summary>
        public static string DescripcionNotificacionInterna {
            get {
                return ResourceManager.GetString("DescripcionNotificacionInterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_CDIRECCION.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_DireccionCitacion.
        /// </summary>
        public static string DireccionCitacion {
            get {
                return ResourceManager.GetString("DireccionCitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_DireccionEnvio.
        /// </summary>
        public static string DireccionEnvio {
            get {
                return ResourceManager.GetString("DireccionEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Documento.
        /// </summary>
        public static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_EntidadNotificacion.
        /// </summary>
        public static string EntidadNotificacion {
            get {
                return ResourceManager.GetString("EntidadNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_PARAM_ESTADOCIVIL.
        /// </summary>
        public static string EstadoCivil {
            get {
                return ResourceManager.GetString("EstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_EstadoCourier.
        /// </summary>
        public static string EstadoCourier {
            get {
                return ResourceManager.GetString("EstadoCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_EstadoDeclaracionAnterior.
        /// </summary>
        public static string EstadoDeclaracionAnterior {
            get {
                return ResourceManager.GetString("EstadoDeclaracionAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_PARAM_ETNIAPERTENECE.
        /// </summary>
        public static string EtniaPertenece {
            get {
                return ResourceManager.GetString("EtniaPertenece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_NumExpedienteGD.
        /// </summary>
        public static string ExpedienteGD {
            get {
                return ResourceManager.GetString("ExpedienteGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_FECHAAGREGADO.
        /// </summary>
        public static string FechaAgregado {
            get {
                return ResourceManager.GetString("FechaAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_FechaDevolucion.
        /// </summary>
        public static string FechaDevolucion {
            get {
                return ResourceManager.GetString("FechaDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_FechaFin.
        /// </summary>
        public static string FechaFin {
            get {
                return ResourceManager.GetString("FechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_FechaFinal.
        /// </summary>
        public static string FechaFinal {
            get {
                return ResourceManager.GetString("FechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_FechaInicio.
        /// </summary>
        public static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_FECHALLEGADA.
        /// </summary>
        public static string FechaLlegada {
            get {
                return ResourceManager.GetString("FechaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_FECHANACIMIENTO.
        /// </summary>
        public static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_FechaRadicacion.
        /// </summary>
        public static string FechaRadicacion {
            get {
                return ResourceManager.GetString("FechaRadicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_FechaSolicitud.
        /// </summary>
        public static string FechaSolicitud {
            get {
                return ResourceManager.GetString("FechaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pi_Filtro.
        /// </summary>
        public static string FiltroConsulta {
            get {
                return ResourceManager.GetString("FiltroConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a po_Formularios.
        /// </summary>
        public static string Formularios {
            get {
                return ResourceManager.GetString("Formularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_CFUNCIONARIO.
        /// </summary>
        public static string Funcionario {
            get {
                return ResourceManager.GetString("Funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_PARAM_GENERO.
        /// </summary>
        public static string Genero {
            get {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_GESTANTE.
        /// </summary>
        public static string Gestante {
            get {
                return ResourceManager.GetString("Gestante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P_ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_IdActoAdministrativo.
        /// </summary>
        public static string IdActoAdministrativo {
            get {
                return ResourceManager.GetString("IdActoAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDCENTROATENCION.
        /// </summary>
        public static string IdCentroAtencion {
            get {
                return ResourceManager.GetString("IdCentroAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IdCorreccion.
        /// </summary>
        public static string IdCorreccion {
            get {
                return ResourceManager.GetString("IdCorreccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PO_IdCorreccion.
        /// </summary>
        public static string IdCorreccionOut {
            get {
                return ResourceManager.GetString("IdCorreccionOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDCRITICAN.
        /// </summary>
        public static string IdCriticaN {
            get {
                return ResourceManager.GetString("IdCriticaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_IdDeclaracion.
        /// </summary>
        public static string IdDeclaracion {
            get {
                return ResourceManager.GetString("IdDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_IdDepartamento.
        /// </summary>
        public static string IdDepartamento {
            get {
                return ResourceManager.GetString("IdDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDDEVOLUCION.
        /// </summary>
        public static string IdDevolucion {
            get {
                return ResourceManager.GetString("IdDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDDIRECCIONTERRITORIAL.
        /// </summary>
        public static string IdDireccionTerritorial {
            get {
                return ResourceManager.GetString("IdDireccionTerritorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDDISCAPACIDAD.
        /// </summary>
        public static string IdDiscapacidad {
            get {
                return ResourceManager.GetString("IdDiscapacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_IdEntidadMunicipio.
        /// </summary>
        public static string IdEntidad {
            get {
                return ResourceManager.GetString("IdEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_IdEntidadmunicipio.
        /// </summary>
        public static string IdEntidadmunicipio {
            get {
                return ResourceManager.GetString("IdEntidadmunicipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P_ID_ENTIDADMUNICIPIO.
        /// </summary>
        public static string IdEntidadMunicipioRad {
            get {
                return ResourceManager.GetString("IdEntidadMunicipioRad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_IdEstado.
        /// </summary>
        public static string IdEstado {
            get {
                return ResourceManager.GetString("IdEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IdExpedienteGD.
        /// </summary>
        public static string IdExpedienteGD {
            get {
                return ResourceManager.GetString("IdExpedienteGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDFESTIVO.
        /// </summary>
        public static string IdFestivo {
            get {
                return ResourceManager.GetString("IdFestivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a po_IdIdentificadorFormulario.
        /// </summary>
        public static string IdFormulario {
            get {
                return ResourceManager.GetString("IdFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_NIDFORMULARIO.
        /// </summary>
        public static string IdFormularioIn {
            get {
                return ResourceManager.GetString("IdFormularioIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_ID_INTEGRADORGD.
        /// </summary>
        public static string IdIntegradorGD {
            get {
                return ResourceManager.GetString("IdIntegradorGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_IdMunicipio.
        /// </summary>
        public static string IdMunicipio {
            get {
                return ResourceManager.GetString("IdMunicipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P_ID_MUNICIPIO.
        /// </summary>
        public static string IdMunicipioRad {
            get {
                return ResourceManager.GetString("IdMunicipioRad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDNOTIFICACION.
        /// </summary>
        public static string IdNotificacion {
            get {
                return ResourceManager.GetString("IdNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDNOTINTERNA.
        /// </summary>
        public static string IdNotificacionInterna {
            get {
                return ResourceManager.GetString("IdNotificacionInterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_IdPais.
        /// </summary>
        public static string IdPais {
            get {
                return ResourceManager.GetString("IdPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PO_IDPAQUETENOTIFICA.
        /// </summary>
        public static string IdPaqueteNotificacion {
            get {
                return ResourceManager.GetString("IdPaqueteNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDPAQUETENOTIFICA.
        /// </summary>
        public static string IdPaqueteNotificacionIn {
            get {
                return ResourceManager.GetString("IdPaqueteNotificacionIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IdPersona.
        /// </summary>
        public static string IdPersona {
            get {
                return ResourceManager.GetString("IdPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDPROCESO.
        /// </summary>
        public static string IdProcesos {
            get {
                return ResourceManager.GetString("IdProcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_PUNTONOTIFICACION.
        /// </summary>
        public static string IdPuntoNotificacion {
            get {
                return ResourceManager.GetString("IdPuntoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDRADICACION.
        /// </summary>
        public static string IdRadicacion {
            get {
                return ResourceManager.GetString("IdRadicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDREGPERSONA.
        /// </summary>
        public static string IdRegistroPersona {
            get {
                return ResourceManager.GetString("IdRegistroPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_TIPOMOTIVACION.
        /// </summary>
        public static string IdTipoMotivacion {
            get {
                return ResourceManager.GetString("IdTipoMotivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P_NRO_ID_TIPO_RADICACION.
        /// </summary>
        public static string IdTipoRadicacion {
            get {
                return ResourceManager.GetString("IdTipoRadicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_IdUsuario.
        /// </summary>
        public static string IdUsuario {
            get {
                return ResourceManager.GetString("IdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDUSUARIOGENERA.
        /// </summary>
        public static string IdUsuarioGenera {
            get {
                return ResourceManager.GetString("IdUsuarioGenera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IdUsuarioRechaza.
        /// </summary>
        public static string IdUsuarioRechaza {
            get {
                return ResourceManager.GetString("IdUsuarioRechaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDUSUARIORECIBE.
        /// </summary>
        public static string IdUsuarioRecibe {
            get {
                return ResourceManager.GetString("IdUsuarioRecibe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IdUsuarioSolicitud.
        /// </summary>
        public static string IdUsuarioSolicitud {
            get {
                return ResourceManager.GetString("IdUsuarioSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDVALORACION.
        /// </summary>
        public static string IdValoracion {
            get {
                return ResourceManager.GetString("IdValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PO_IDVALORACION.
        /// </summary>
        public static string IdValoracionOut {
            get {
                return ResourceManager.GetString("IdValoracionOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a po_Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_PARAM_MINORIAETNICA.
        /// </summary>
        public static string MinoriaEtnica {
            get {
                return ResourceManager.GetString("MinoriaEtnica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_ESMUJERCABEZADEHOGAR.
        /// </summary>
        public static string MujerCabezaHogar {
            get {
                return ResourceManager.GetString("MujerCabezaHogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_MunicipioNotificacion.
        /// </summary>
        public static string MunicipioNotificacion {
            get {
                return ResourceManager.GetString("MunicipioNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDCREADO.
        /// </summary>
        public static string nIdCreadoPersona {
            get {
                return ResourceManager.GetString("nIdCreadoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_ESTADONOTIFICACION.
        /// </summary>
        public static string nIdEstadoNotificacion {
            get {
                return ResourceManager.GetString("nIdEstadoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_NOMBRECENTRO.
        /// </summary>
        public static string NombreCentroAtencion {
            get {
                return ResourceManager.GetString("NombreCentroAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_NombreDeclarante.
        /// </summary>
        public static string NombreDeclarante {
            get {
                return ResourceManager.GetString("NombreDeclarante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PO_NombreSubEtnia.
        /// </summary>
        public static string NombreSubetnia {
            get {
                return ResourceManager.GetString("NombreSubetnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_NumeroDias.
        /// </summary>
        public static string NumeroDias {
            get {
                return ResourceManager.GetString("NumeroDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_NumeroDocumento.
        /// </summary>
        public static string NumeroDocumento {
            get {
                return ResourceManager.GetString("NumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_NumeroFormulario.
        /// </summary>
        public static string NumeroFormulario {
            get {
                return ResourceManager.GetString("NumeroFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P_NRO_FORMULARIO.
        /// </summary>
        public static string NumeroFormularioRad {
            get {
                return ResourceManager.GetString("NumeroFormularioRad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_NumeroGuia.
        /// </summary>
        public static string NumeroGuia {
            get {
                return ResourceManager.GetString("NumeroGuia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_PageNumber.
        /// </summary>
        public static string NumeroPagina {
            get {
                return ResourceManager.GetString("NumeroPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_OBSERVACION.
        /// </summary>
        public static string Observacion {
            get {
                return ResourceManager.GetString("Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_OBSERVACIONCRITICAN.
        /// </summary>
        public static string ObservacionCriticaN {
            get {
                return ResourceManager.GetString("ObservacionCriticaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P_OBSERVACIONES.
        /// </summary>
        public static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pi_Orden.
        /// </summary>
        public static string OrdenConsulta {
            get {
                return ResourceManager.GetString("OrdenConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_OrdenServicio.
        /// </summary>
        public static string OrdenServicio {
            get {
                return ResourceManager.GetString("OrdenServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PO_IDRADICACION.
        /// </summary>
        public static string OutIdRadicacion {
            get {
                return ResourceManager.GetString("OutIdRadicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PO_RADICACION.
        /// </summary>
        public static string OutRadicacion {
            get {
                return ResourceManager.GetString("OutRadicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_PaisNotificacion.
        /// </summary>
        public static string PaisNotificacion {
            get {
                return ResourceManager.GetString("PaisNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pi_Param_Estado.
        /// </summary>
        public static string ParametroEstado {
            get {
                return ResourceManager.GetString("ParametroEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P_PARAM_RESULTADO_VALIDACION.
        /// </summary>
        public static string ParamResultadoValidacion {
            get {
                return ResourceManager.GetString("ParamResultadoValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P_PARAM_TIPOENTIDAD.
        /// </summary>
        public static string ParamTipoEntidad {
            get {
                return ResourceManager.GetString("ParamTipoEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_PARTEEMOTIVAMOD.
        /// </summary>
        public static string ParteEmotiva {
            get {
                return ResourceManager.GetString("ParteEmotiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_IDCREADO.
        /// </summary>
        public static string PersonaAgregadaId {
            get {
                return ResourceManager.GetString("PersonaAgregadaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_CCODIGOORFEO.
        /// </summary>
        public static string PICodigoOrfeo {
            get {
                return ResourceManager.GetString("PICodigoOrfeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_DGENERADO.
        /// </summary>
        public static string PIDGenerado {
            get {
                return ResourceManager.GetString("PIDGenerado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_CESTADO.
        /// </summary>
        public static string PIEstado {
            get {
                return ResourceManager.GetString("PIEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_DESTADO.
        /// </summary>
        public static string PIFechaEstado {
            get {
                return ResourceManager.GetString("PIFechaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_NID.
        /// </summary>
        public static string PINId {
            get {
                return ResourceManager.GetString("PINId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_NDESDE.
        /// </summary>
        public static string PINumeroDesde {
            get {
                return ResourceManager.GetString("PINumeroDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_NHASTA.
        /// </summary>
        public static string PINumeroHasta {
            get {
                return ResourceManager.GetString("PINumeroHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Po_IdPais.
        /// </summary>
        public static string Po_IdPais {
            get {
                return ResourceManager.GetString("Po_IdPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PO_CCODIGOORFEO.
        /// </summary>
        public static string POCodigoOrfeo {
            get {
                return ResourceManager.GetString("POCodigoOrfeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Preguntas.
        /// </summary>
        public static string Preguntas {
            get {
                return ResourceManager.GetString("Preguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_PrimerApellido.
        /// </summary>
        public static string PrimerApellido {
            get {
                return ResourceManager.GetString("PrimerApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_PrimerNombre.
        /// </summary>
        public static string PrimerNombre {
            get {
                return ResourceManager.GetString("PrimerNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Recurrente.
        /// </summary>
        public static string Recurrente {
            get {
                return ResourceManager.GetString("Recurrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_REGIMENESPECIAL.
        /// </summary>
        public static string RegimenEspecial {
            get {
                return ResourceManager.GetString("RegimenEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pi_RegInicial.
        /// </summary>
        public static string RegInicialConsulta {
            get {
                return ResourceManager.GetString("RegInicialConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_PageSize.
        /// </summary>
        public static string RegistrosPorPagina {
            get {
                return ResourceManager.GetString("RegistrosPorPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_PARAM_RESGUARDO.
        /// </summary>
        public static string ReguargoPertenece {
            get {
                return ResourceManager.GetString("ReguargoPertenece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_RELACION.
        /// </summary>
        public static string RelacionPersona {
            get {
                return ResourceManager.GetString("RelacionPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_RESPUESTA.
        /// </summary>
        public static string Respuesta {
            get {
                return ResourceManager.GetString("Respuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Respuestas.
        /// </summary>
        public static string Respuestas {
            get {
                return ResourceManager.GetString("Respuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a po_Cursor.
        /// </summary>
        public static string Resultado {
            get {
                return ResourceManager.GetString("Resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Po_Resultado.
        /// </summary>
        public static string ResultadoConsulta {
            get {
                return ResourceManager.GetString("ResultadoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a po_RecordCount.
        /// </summary>
        public static string ResultadoConteo {
            get {
                return ResourceManager.GetString("ResultadoConteo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PO_RUTAIMAGEN.
        /// </summary>
        public static string RutaImagen {
            get {
                return ResourceManager.GetString("RutaImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P_RUTAIMAGEN.
        /// </summary>
        public static string RutaImagenRad {
            get {
                return ResourceManager.GetString("RutaImagenRad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_SEGUNDOAPELLIDO.
        /// </summary>
        public static string SegundoApellido {
            get {
                return ResourceManager.GetString("SegundoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_SEGUNDONOMBRE.
        /// </summary>
        public static string SegundoNombre {
            get {
                return ResourceManager.GetString("SegundoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_Serie.
        /// </summary>
        public static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_SOLOASIGNACIONES.
        /// </summary>
        public static string SoloAsignaciones {
            get {
                return ResourceManager.GetString("SoloAsignaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pi_TamanoPagina.
        /// </summary>
        public static string TamañoPaginaConsulta {
            get {
                return ResourceManager.GetString("TamañoPaginaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_NTELEFONO.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_TEXTO.
        /// </summary>
        public static string TextoNotificacionInterna {
            get {
                return ResourceManager.GetString("TextoNotificacionInterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_TipoCentro.
        /// </summary>
        public static string TipoCentroAtencion {
            get {
                return ResourceManager.GetString("TipoCentroAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_TipoCodigo.
        /// </summary>
        public static string TipoCodigo {
            get {
                return ResourceManager.GetString("TipoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_TipoDocumento.
        /// </summary>
        public static string TipoDocumento {
            get {
                return ResourceManager.GetString("TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PO_TIPOMOTIVACION.
        /// </summary>
        public static string TipoMotivacionId {
            get {
                return ResourceManager.GetString("TipoMotivacionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_TIPOPROCESO.
        /// </summary>
        public static string TipoProceso {
            get {
                return ResourceManager.GetString("TipoProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_TipoPunto.
        /// </summary>
        public static string TipoPuntoNotificacion {
            get {
                return ResourceManager.GetString("TipoPuntoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pi_UbicacionNotificacion.
        /// </summary>
        public static string UbicacionNotificacion {
            get {
                return ResourceManager.GetString("UbicacionNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pi_ValoradorId.
        /// </summary>
        public static string ValoradorId {
            get {
                return ResourceManager.GetString("ValoradorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PI_ValoresCorrecciones.
        /// </summary>
        public static string ValoresCorrecciones {
            get {
                return ResourceManager.GetString("ValoresCorrecciones", resourceCulture);
            }
        }
    }
}
