//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruv.Infrastructure.Crosscutting.Resources.DB {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Procedimientos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Procedimientos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruv.Infrastructure.Crosscutting.Resources.DB.Procedimientos", typeof(Procedimientos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ActualizarEstadoCourier.
        /// </summary>
        public static string ActualizaEstadoCourier {
            get {
                return ResourceManager.GetString("ActualizaEstadoCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_AsociarNotificacionAPaquete.
        /// </summary>
        public static string ActualizaEstadoEnviadoNotificacion {
            get {
                return ResourceManager.GetString("ActualizaEstadoEnviadoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_DEVOLUCION.sp_ActualizarDevolucion.
        /// </summary>
        public static string ActualizarDevolucion {
            get {
                return ResourceManager.GetString("ActualizarDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_COMMON.sp_setDirPuntoNotificacion.
        /// </summary>
        public static string ActualizarDireccionPuntoNotificacion {
            get {
                return ResourceManager.GetString("ActualizarDireccionPuntoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_COMMON.SP_UPDESTADO_DECLARACION.
        /// </summary>
        public static string ActualizarEstadoDeclaracion {
            get {
                return ResourceManager.GetString("ActualizarEstadoDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_RADICACION.SP_ACTUALIZAR_INTEGRADORGD.
        /// </summary>
        public static string ActualizarLogIntegrador {
            get {
                return ResourceManager.GetString("ActualizarLogIntegrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_ACTUALIZARNOTIFICACION.
        /// </summary>
        public static string ActualizarNotificacion {
            get {
                return ResourceManager.GetString("ActualizarNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_ActualizarPuntoNotificacion.
        /// </summary>
        public static string ActualizarPuntoNotificacion {
            get {
                return ResourceManager.GetString("ActualizarPuntoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pkg_Radicacion.SP_UPDRADICACION.
        /// </summary>
        public static string ActualizarRadicacion {
            get {
                return ResourceManager.GetString("ActualizarRadicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_ACTOSADMIN.sp_ActualizarTipoCodigo.
        /// </summary>
        public static string ActualizarTipoCodigoActoAdministrativo {
            get {
                return ResourceManager.GetString("ActualizarTipoCodigoActoAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_AGREGADISCAPACIDADVALORA.
        /// </summary>
        public static string AgregaDiscapacidadValoracion {
            get {
                return ResourceManager.GetString("AgregaDiscapacidadValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_AGREGAREGPERSONA.
        /// </summary>
        public static string AgregaRegPersonaValoracion {
            get {
                return ResourceManager.GetString("AgregaRegPersonaValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_AGREGARORDENSERVICIO.
        /// </summary>
        public static string AgregarOrdenServicio {
            get {
                return ResourceManager.GetString("AgregarOrdenServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_AGREGAPERSONA.
        /// </summary>
        public static string AgregarPersonaValoracion {
            get {
                return ResourceManager.GetString("AgregarPersonaValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CORRECCIONES.SP_APROBARSOLICITUD.
        /// </summary>
        public static string AprobarCorreccion {
            get {
                return ResourceManager.GetString("AprobarCorreccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_APROBARNOTIFICACION.
        /// </summary>
        public static string AprobarNotificacion {
            get {
                return ResourceManager.GetString("AprobarNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_APROBARVALORACION.
        /// </summary>
        public static string AprobarValoracion {
            get {
                return ResourceManager.GetString("AprobarValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_GLOSAS.SP_ASIGNAGLOSA.
        /// </summary>
        public static string AsignaGlosa {
            get {
                return ResourceManager.GetString("AsignaGlosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_AsignarFormulario.
        /// </summary>
        public static string AsignarFormulario {
            get {
                return ResourceManager.GetString("AsignarFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.SP_ASIGNARFORMULARIOFILTRO.
        /// </summary>
        public static string AsignarFormularioFiltro {
            get {
                return ResourceManager.GetString("AsignarFormularioFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_ASOCIARCODIGUIANOTIFICACION.
        /// </summary>
        public static string AsociarCodigosGuia {
            get {
                return ResourceManager.GetString("AsociarCodigosGuia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_AUTOASIGNARVALORACION.
        /// </summary>
        public static string AutoAsignaValoracion {
            get {
                return ResourceManager.GetString("AutoAsignaValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CALENDARIO.sp_BorrarFestivo.
        /// </summary>
        public static string BorrarFestivo {
            get {
                return ResourceManager.GetString("BorrarFestivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CorreccionES.SP_BUSCAPERSONAS.
        /// </summary>
        public static string BuscaPersonas {
            get {
                return ResourceManager.GetString("BuscaPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CorreccionES.SP_BUSCAPERSONASCOUNT.
        /// </summary>
        public static string BuscaPersonasCount {
            get {
                return ResourceManager.GetString("BuscaPersonasCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_CAMBIAESTADONOTIFICACION.
        /// </summary>
        public static string CambiarEstadoNotificacion {
            get {
                return ResourceManager.GetString("CambiarEstadoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_ObtenerFormulariosCantidad.
        /// </summary>
        public static string CantidadFormulariosActivarInactivar {
            get {
                return ResourceManager.GetString("CantidadFormulariosActivarInactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CORRECCIONES.SP_CARGADATOSCORREGIR.
        /// </summary>
        public static string CargaDatosCorreccion {
            get {
                return ResourceManager.GetString("CargaDatosCorreccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_ACTOSADMIN.SP_NOTIFICACION.
        /// </summary>
        public static string CargaDatosNotificacion {
            get {
                return ResourceManager.GetString("CargaDatosNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_DEVOLUCION.SP_DATOSPARADEVOLUCION.
        /// </summary>
        public static string CargaDatosparaDevolucion {
            get {
                return ResourceManager.GetString("CargaDatosparaDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_DEVOLUCION.SP_CARGADEVOLUCION.
        /// </summary>
        public static string CargaDevolucion {
            get {
                return ResourceManager.GetString("CargaDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_CARGAPERSONASASOCIADAS.
        /// </summary>
        public static string CargaPersonasAsociadas {
            get {
                return ResourceManager.GetString("CargaPersonasAsociadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_FINALIZANOTIFICACION.
        /// </summary>
        public static string CierraNotificacion {
            get {
                return ResourceManager.GetString("CierraNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_confirmaEnvionNotificacion.
        /// </summary>
        public static string ConfirmarEnvioNotificacion {
            get {
                return ResourceManager.GetString("ConfirmarEnvioNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ConsultaNotificacionesCount.
        /// </summary>
        public static string ConsultaCantidadNotificaciones {
            get {
                return ResourceManager.GetString("ConsultaCantidadNotificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_CONSULTAVALORADORES.
        /// </summary>
        public static string ConsultaGestionValorador {
            get {
                return ResourceManager.GetString("ConsultaGestionValorador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_CONSULTACENTROATENCIONOTIF.
        /// </summary>
        public static string ConsultaNotificacionesCentroAtencion {
            get {
                return ResourceManager.GetString("ConsultaNotificacionesCentroAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_CONSULTACENTROATENCIONCOUNT.
        /// </summary>
        public static string ConsultaNotificacionesCentroAtencionCount {
            get {
                return ResourceManager.GetString("ConsultaNotificacionesCentroAtencionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ConsultaNtfEntregadas.
        /// </summary>
        public static string ConsultaNotificacionesEntregadas {
            get {
                return ResourceManager.GetString("ConsultaNotificacionesEntregadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ConsultaNtfEntregadasCount.
        /// </summary>
        public static string ConsultaNotificacionesEntregadasConteo {
            get {
                return ResourceManager.GetString("ConsultaNotificacionesEntregadasConteo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ConsultaNotificaciones.
        /// </summary>
        public static string ConsultaNotificacionesPaginado {
            get {
                return ResourceManager.GetString("ConsultaNotificacionesPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ConsultaNotificacionPorId.
        /// </summary>
        public static string ConsultaNotificacionPorId {
            get {
                return ResourceManager.GetString("ConsultaNotificacionPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CORRECCIONES.sp_ConsultarCamposCorreccion.
        /// </summary>
        public static string ConsultarCamposCorreccion {
            get {
                return ResourceManager.GetString("ConsultarCamposCorreccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CORRECCIONES.sp_ConsultarCorreccion.
        /// </summary>
        public static string ConsultarCorreccion {
            get {
                return ResourceManager.GetString("ConsultarCorreccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CALENDARIO.sp_ConsultarFestivos.
        /// </summary>
        public static string ConsultarFeriadosPorAnio {
            get {
                return ResourceManager.GetString("ConsultarFeriadosPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_DETALLEVALORADORCOOUNT.
        /// </summary>
        public static string ContadorDetalleValora {
            get {
                return ResourceManager.GetString("ContadorDetalleValora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_CARGAPERSONASASOCIADASCOUNT.
        /// </summary>
        public static string ContadorPersonasAsociadasDeclaracion {
            get {
                return ResourceManager.GetString("ContadorPersonasAsociadasDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_CONSULTAVALORADORESCOUNT.
        /// </summary>
        public static string ContadorValoradores {
            get {
                return ResourceManager.GetString("ContadorValoradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_ENCARGADOSPORENTIDADCOUNT.
        /// </summary>
        public static string CountEncargadosPorEntidad {
            get {
                return ResourceManager.GetString("CountEncargadosPorEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_CrearPaqueteNotificacion.
        /// </summary>
        public static string CreaPaqueteNotificacion {
            get {
                return ResourceManager.GetString("CreaPaqueteNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_CrearPaqueteDesdeFiltro.
        /// </summary>
        public static string CrearPaqueteNotificacionDesdeFiltro {
            get {
                return ResourceManager.GetString("CrearPaqueteNotificacionDesdeFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_DetalleCentroAtencion.
        /// </summary>
        public static string DetalleCentroAtencion {
            get {
                return ResourceManager.GetString("DetalleCentroAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_DetalleCentroAtencionCOUNT.
        /// </summary>
        public static string DetalleCentroAtencioncontador {
            get {
                return ResourceManager.GetString("DetalleCentroAtencioncontador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_CONSULTAVALORADORDETALLE.
        /// </summary>
        public static string DetalleGestionValorador {
            get {
                return ResourceManager.GetString("DetalleGestionValorador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_DetalleNotificacion.
        /// </summary>
        public static string DetalleNotificacion {
            get {
                return ResourceManager.GetString("DetalleNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_DEVOLUCION.sp_DevolverDeclaracion.
        /// </summary>
        public static string DevolverDeclaracion {
            get {
                return ResourceManager.GetString("DevolverDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_NOTIFICACIONLEYNUEVAOVIEJA.
        /// </summary>
        public static string EvaluaLeyViejaoNueva {
            get {
                return ResourceManager.GetString("EvaluaLeyViejaoNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CALENDARIO.sp_CalcularDiasHabiles.
        /// </summary>
        public static string FechaDiasHabiles {
            get {
                return ResourceManager.GetString("FechaDiasHabiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACIONINTERNA.SP_GENERANOTIFICACION.
        /// </summary>
        public static string GeneraNotificacionInterna {
            get {
                return ResourceManager.GetString("GeneraNotificacionInterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_GenerarFormularios.
        /// </summary>
        public static string GenerarFormularios {
            get {
                return ResourceManager.GetString("GenerarFormularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_GenerarFormulariosWEB.
        /// </summary>
        public static string GenerarFormularioWEB {
            get {
                return ResourceManager.GetString("GenerarFormularioWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_GETENCARGADOSPORENTIDAD.
        /// </summary>
        public static string getEncargadosPorEntidad {
            get {
                return ResourceManager.GetString("getEncargadosPorEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.SP_INACTIVARFORMULARIO.
        /// </summary>
        public static string InactivarFormulario {
            get {
                return ResourceManager.GetString("InactivarFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CRITICAN.SP_INSERTACRITICA.
        /// </summary>
        public static string InsertaCriticaN {
            get {
                return ResourceManager.GetString("InsertaCriticaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_INSERTANOTIFICACION.
        /// </summary>
        public static string InsertaNotificacion {
            get {
                return ResourceManager.GetString("InsertaNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pkg_Radicacion.SP_INSERTARADICACIONDEV.
        /// </summary>
        public static string InsertaRadicacionDevolucion {
            get {
                return ResourceManager.GetString("InsertaRadicacionDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CALENDARIO.sp_InsertarFestivo.
        /// </summary>
        public static string InsertarFestivo {
            get {
                return ResourceManager.GetString("InsertarFestivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_RADICACION.SP_RADICACION_INTEGRACION.
        /// </summary>
        public static string InsertarIntregacionGD {
            get {
                return ResourceManager.GetString("InsertarIntregacionGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_INSERTATIPOMOTIVACION.
        /// </summary>
        public static string InsertaTipoMotivacion {
            get {
                return ResourceManager.GetString("InsertaTipoMotivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_ObtenerFormularios.
        /// </summary>
        public static string ListarFormularios {
            get {
                return ResourceManager.GetString("ListarFormularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_ObtenerFormulariosPaginado.
        /// </summary>
        public static string ListarFormulariosAcitvarInactivar {
            get {
                return ResourceManager.GetString("ListarFormulariosAcitvarInactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.SP_GETFORMULARIOSNORADICADOS.
        /// </summary>
        public static string ListarFormulariosNoRadicados {
            get {
                return ResourceManager.GetString("ListarFormulariosNoRadicados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_ObtenerFormulariosPorEstado.
        /// </summary>
        public static string ListarFormulariosPorEstado {
            get {
                return ResourceManager.GetString("ListarFormulariosPorEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.sp_getDeclaraValoradorPaginado.
        /// </summary>
        public static string ListaTareasValorador {
            get {
                return ResourceManager.GetString("ListaTareasValorador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.sp_getDeclaraValoradorCantidad.
        /// </summary>
        public static string ListaTareasValoradorCantidad {
            get {
                return ResourceManager.GetString("ListaTareasValoradorCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_MarcarDescargado.
        /// </summary>
        public static string MarcarDescargado {
            get {
                return ResourceManager.GetString("MarcarDescargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_MarcarRadicado.
        /// </summary>
        public static string MarcarFormularioRadicado {
            get {
                return ResourceManager.GetString("MarcarFormularioRadicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACIONINTERNA.SP_MARCALEIDOS.
        /// </summary>
        public static string MarcarLeidos {
            get {
                return ResourceManager.GetString("MarcarLeidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CRITICAN.SP_CARGAIMAGENCRITICAN.
        /// </summary>
        public static string NombreImagenACargar {
            get {
                return ResourceManager.GetString("NombreImagenACargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_GUARDAOBSERVACION.
        /// </summary>
        public static string ObservacionNotificacion {
            get {
                return ResourceManager.GetString("ObservacionNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_ORFEO.SP_GETORFEOPORIDVALORACION.
        /// </summary>
        public static string ObtenerDatosOrfeoPorIdValoracion {
            get {
                return ResourceManager.GetString("ObtenerDatosOrfeoPorIdValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ConsultaDetallePaquete.
        /// </summary>
        public static string ObtenerDetallePaqueteNotificacion {
            get {
                return ResourceManager.GetString("ObtenerDetallePaqueteNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ConsultaDetallePaqueteCount.
        /// </summary>
        public static string ObtenerDetallePaqueteNotificacionConteo {
            get {
                return ResourceManager.GetString("ObtenerDetallePaqueteNotificacionConteo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_DEVOLUCION.sp_ObtenerDevolucion.
        /// </summary>
        public static string ObtenerDevolucion {
            get {
                return ResourceManager.GetString("ObtenerDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_COMMON.sp_getDirPuntoNotificacion.
        /// </summary>
        public static string ObtenerDireccionPuntoNotificacion {
            get {
                return ResourceManager.GetString("ObtenerDireccionPuntoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_GETESTADOSDENOTIFICACION.
        /// </summary>
        public static string ObtenerEstadosDeNotificacion {
            get {
                return ResourceManager.GetString("ObtenerEstadosDeNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_ObtenerFrmPorNumero.
        /// </summary>
        public static string ObtenerFrmPorNumero {
            get {
                return ResourceManager.GetString("ObtenerFrmPorNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_ObtenerFrmPorUsuario.
        /// </summary>
        public static string ObtenerFrmPorUsuario {
            get {
                return ResourceManager.GetString("ObtenerFrmPorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_ObtenerFrmsCantidad.
        /// </summary>
        public static string ObtenerFrmPorUsuarioEstadoCantidad {
            get {
                return ResourceManager.GetString("ObtenerFrmPorUsuarioEstadoCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_ObtenerFrmsPaginado.
        /// </summary>
        public static string ObtenerFrmPorUsuarioEstadoPaginado {
            get {
                return ResourceManager.GetString("ObtenerFrmPorUsuarioEstadoPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_COMUNICACION.SP_OBTENERGRUPOFAMILIAR.
        /// </summary>
        public static string ObtenerGrupoFamiliar {
            get {
                return ResourceManager.GetString("ObtenerGrupoFamiliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_COMUNICACION.SP_OBTENERHECHOSPORIDPERSONA.
        /// </summary>
        public static string ObtenerHechosPorIdPersona {
            get {
                return ResourceManager.GetString("ObtenerHechosPorIdPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ObtenerHistorico.
        /// </summary>
        public static string ObtenerHistoricoNotificacion {
            get {
                return ResourceManager.GetString("ObtenerHistoricoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ObtenerHistoricoPaquete.
        /// </summary>
        public static string ObtenerHistoricoPaqueteNotificacion {
            get {
                return ResourceManager.GetString("ObtenerHistoricoPaqueteNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_ACTOSADMIN.SP_GETIDVALORACIONBYIDDEC.
        /// </summary>
        public static string ObtenerIdValoracionPorIdDeclaracion {
            get {
                return ResourceManager.GetString("ObtenerIdValoracionPorIdDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CORRECCIONES.SP_OBTENERINFOCORRECCION.
        /// </summary>
        public static string ObtenerInfoCorreccion {
            get {
                return ResourceManager.GetString("ObtenerInfoCorreccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_DEVOLUCION.SP_OBTENERLISTACAUSALES.
        /// </summary>
        public static string ObtenerListaCausales {
            get {
                return ResourceManager.GetString("ObtenerListaCausales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_DEVOLUCION.sp_ObtenerCausalesDevolucion.
        /// </summary>
        public static string ObtenerListadoCausalesDevolucion {
            get {
                return ResourceManager.GetString("ObtenerListadoCausalesDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACIONINTERNA.SP_OBTENERNOTIUSUARIO.
        /// </summary>
        public static string ObtenerNotificacionInterna {
            get {
                return ResourceManager.GetString("ObtenerNotificacionInterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ConsultaPaquetePorId.
        /// </summary>
        public static string ObtenerPaqueteNotificacion {
            get {
                return ResourceManager.GetString("ObtenerPaqueteNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ConsultaPaquetes.
        /// </summary>
        public static string ObtenerPaquetesNotificacion {
            get {
                return ResourceManager.GetString("ObtenerPaquetesNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.sp_ConsultaPaquetesCount.
        /// </summary>
        public static string ObtenerPaquetesNotificacionConteo {
            get {
                return ResourceManager.GetString("ObtenerPaquetesNotificacionConteo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_COMUNICACION.sp_ObtenerPersonaPorDocumento.
        /// </summary>
        public static string ObtenerPersonaPorDocumento {
            get {
                return ResourceManager.GetString("ObtenerPersonaPorDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_COMUNICACION.sp_ObtenerPersonaPorId.
        /// </summary>
        public static string ObtenerPersonaPorId {
            get {
                return ResourceManager.GetString("ObtenerPersonaPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_COMUNICACION.sp_ObtenerPersonas.
        /// </summary>
        public static string ObtenerPersonas {
            get {
                return ResourceManager.GetString("ObtenerPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pkg_Radicacion.SP_OBTENERRADFROMDECLA.
        /// </summary>
        public static string ObtenerRadicacionIdDeclaracion {
            get {
                return ResourceManager.GetString("ObtenerRadicacionIdDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pkg_Radicacion.SP_OBTENERRADFROMNROFORM.
        /// </summary>
        public static string ObtenerRadicacionNumeroFormulario {
            get {
                return ResourceManager.GetString("ObtenerRadicacionNumeroFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_OBTIENETIPOMOTIVACION.
        /// </summary>
        public static string ObtenerTipoMotivacion {
            get {
                return ResourceManager.GetString("ObtenerTipoMotivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_GETALLNOTIFICACIONES.
        /// </summary>
        public static string ObtenerTodasNotificaciones {
            get {
                return ResourceManager.GetString("ObtenerTodasNotificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_ORFEO.SP_GETCODORFEOPORIDVALORACION.
        /// </summary>
        public static string ObtieneCodigoOrfeoPorIdValoracion {
            get {
                return ResourceManager.GetString("ObtieneCodigoOrfeoPorIdValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_IDVALORACIONPORDECLARACION.
        /// </summary>
        public static string ObtieneIdValoracionporDeclaracion {
            get {
                return ResourceManager.GetString("ObtieneIdValoracionporDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CORRECCIONES.SP_OBTENERNOMBRESUBETNIA.
        /// </summary>
        public static string ObtieneNombreSubetnia {
            get {
                return ResourceManager.GetString("ObtieneNombreSubetnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_ObtienePaisGenerFormuWEB.
        /// </summary>
        public static string ObtienePaisGeneradorFormularioWEB {
            get {
                return ResourceManager.GetString("ObtienePaisGeneradorFormularioWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_Common.SP_OBTIENESUBETNIAS.
        /// </summary>
        public static string ObtieneSubEtnias {
            get {
                return ResourceManager.GetString("ObtieneSubEtnias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CORRECCIONES.sp_RechazarCorreccion.
        /// </summary>
        public static string RechazarCorreccion {
            get {
                return ResourceManager.GetString("RechazarCorreccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_RECHAZARVALORACION.
        /// </summary>
        public static string RechazarValoracion {
            get {
                return ResourceManager.GetString("RechazarValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_ORFEO.SP_RELACIONARVALORACIONORFEO.
        /// </summary>
        public static string RelacionarCodigoOrfeoValoracion {
            get {
                return ResourceManager.GetString("RelacionarCodigoOrfeoValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONSULTA.sp_BuscaDeclaraciones.
        /// </summary>
        public static string ReporteDeclaracion {
            get {
                return ResourceManager.GetString("ReporteDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONSULTA.sp_BuscaDeclaracionesCount.
        /// </summary>
        public static string ReporteDeclaracionCount {
            get {
                return ResourceManager.GetString("ReporteDeclaracionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONSULTA.sp_DetalleDeclaracion.
        /// </summary>
        public static string ReporteDetalleDeclaracion {
            get {
                return ResourceManager.GetString("ReporteDetalleDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_RESUMENVALORACION.
        /// </summary>
        public static string ResumenLiderValoracion {
            get {
                return ResourceManager.GetString("ResumenLiderValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.sp_SepararImprenta.
        /// </summary>
        public static string SepararFormularioImprenta {
            get {
                return ResourceManager.GetString("SepararFormularioImprenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CONTROLIDFORMULARIO.SP_SEPARARIMPRENTAFILTRO.
        /// </summary>
        public static string SepararFormularioImprentaFiltro {
            get {
                return ResourceManager.GetString("SepararFormularioImprentaFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_NOTIFICACION.SP_SOLICITACORRECCION.
        /// </summary>
        public static string SolicitaCorrecionDireccion {
            get {
                return ResourceManager.GetString("SolicitaCorrecionDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_CORRECCIONES.sp_SolicitarCorreccion.
        /// </summary>
        public static string SolicitarCorreccion {
            get {
                return ResourceManager.GetString("SolicitarCorreccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_DEVOLUCION.sp_SolicitarDevolucion.
        /// </summary>
        public static string SolicitarDevolucion {
            get {
                return ResourceManager.GetString("SolicitarDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.sp_getDeclaracionesValPaginada.
        /// </summary>
        public static string ValoracionesEnValoracion {
            get {
                return ResourceManager.GetString("ValoracionesEnValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.sp_getDeclaracionesValCantidad.
        /// </summary>
        public static string ValoracionesEnValoracionCantidad {
            get {
                return ResourceManager.GetString("ValoracionesEnValoracionCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.sp_getValoracionHistorico.
        /// </summary>
        public static string ValoracionHistorico {
            get {
                return ResourceManager.GetString("ValoracionHistorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKG_VALORACION.SP_GETMOTIVACIONVALORACION.
        /// </summary>
        public static string ValoracionMotivacion {
            get {
                return ResourceManager.GetString("ValoracionMotivacion", resourceCulture);
            }
        }
    }
}
