-- Create new package
create or replace PACKAGE PKG_DUPLICADOS AS

  PROCEDURE sp_GetDeclaraciones(po_Cursor OUT SYS_REFCURSOR);

  PROCEDURE sp_PersonasIdCriterio(po_Cursor OUT SYS_REFCURSOR);
  
  PROCEDURE sp_PersonasIdRegistros(pi_NumeroDocumento IN TBPERSONAS.NUMERODOCUMENTO%TYPE,
                                   pi_PrimerNombre    IN TBPERSONAS.PRIMERNOMBRE%TYPE,
                                   pi_SegundoNombre   IN TBPERSONAS.SEGUNDONOMBRE%TYPE,
                                   pi_PrimerApellido  IN TBPERSONAS.PRIMERAPELLIDO%TYPE,
                                   pi_SegundoApellido IN TBPERSONAS.SEGUNDOAPELLIDO%TYPE,
                                   po_Cursor          OUT SYS_REFCURSOR);

  PROCEDURE sp_PersonasBorrar(pi_IdPersona IN NUMBER, pi_IdPersonaOrg IN NUMBER, po_Cursor OUT SYS_REFCURSOR);
  
  PROCEDURE sp_RegistrosPersonaIdCriterio(po_Cursor OUT SYS_REFCURSOR);
  
  PROCEDURE sp_RegistrosPersonaIdRegistros(po_Cursor OUT SYS_REFCURSOR);
  
  PROCEDURE sp_RegistrosPersonaBorrar(pi_IdRegistroPersona IN NUMBER, pi_IdRegistroPersonaOriginal IN NUMBER);
  
END PKG_DUPLICADOS;
/

-- Create package body
create or replace PACKAGE BODY PKG_DUPLICADOS AS

  --Retorna los numeros de formulario repetidos.
  PROCEDURE sp_GetDeclaraciones(po_Cursor OUT SYS_REFCURSOR) IS
  BEGIN
  
    OPEN PO_CURSOR FOR
      SELECT * FROM (
        SELECT numeroformulario, count(numeroformulario) CONTEO FROM tbdeclaraciones 
        GROUP BY numeroformulario
        ) 
      WHERE CONTEO > 1
      ORDER BY CONTEO, NUMEROFORMULARIO;
  
  END;

  PROCEDURE sp_PersonasIdCriterio(po_Cursor OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN PO_CURSOR FOR
      SELECT  NUMERODOCUMENTO, 
              PRIMERNOMBRE,
              SEGUNDONOMBRE,
              PRIMERAPELLIDO,
              SEGUNDOAPELLIDO, 
              COUNT(1)
      FROM TBPERSONAS
      WHERE NUMERODOCUMENTO IS NOT NULL
      GROUP BY  NUMERODOCUMENTO, 
                PRIMERNOMBRE,
                SEGUNDONOMBRE,
                PRIMERAPELLIDO,
                SEGUNDOAPELLIDO
      HAVING COUNT(1) > 1;
  END;
  
  PROCEDURE sp_PersonasIdRegistros(pi_NumeroDocumento IN TBPERSONAS.NUMERODOCUMENTO%TYPE,
                                   pi_PrimerNombre    IN TBPERSONAS.PRIMERNOMBRE%TYPE,
                                   pi_SegundoNombre   IN TBPERSONAS.SEGUNDONOMBRE%TYPE,
                                   pi_PrimerApellido  IN TBPERSONAS.PRIMERAPELLIDO%TYPE,
                                   pi_SegundoApellido IN TBPERSONAS.SEGUNDOAPELLIDO%TYPE,
                                   po_Cursor          OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN PO_CURSOR FOR
      SELECT P.ID IDPERSONA,
            P.PRIMERNOMBRE,
            P.SEGUNDONOMBRE,
            P.PRIMERAPELLIDO,
            P.SEGUNDOAPELLIDO,
            P.PARAM_TIPODOCUMENTO,
            P.NUMERODOCUMENTO,
            P.PARAM_ESTADOCIVIL,
            P.PARAM_GENERO,
            P.PARAM_MINORIAETNICA,
            P.GESTANTE,
            P.PARAM_REGIMENSALUD,
            P.FECHANACIMIENTO,
            P.PARAM_ETNIAPERTENECE,
            P.PARAM_RESGUARDO,
            P.CUALETNIAOPUEBLO
            --RA.FECHALLEGADA,
            --D.PARAM_ESTADO
      FROM TBPERSONAS P
      --INNER JOIN TBREGISTROS_PERSONAS R ON R.ID_PERSONA = P.ID
      --INNER JOIN TBDECLARACIONES D ON D.ID = R.ID_DECLARACION
      --INNER JOIN TBRADICACION RA ON RA.ID_DECLARACION = D.ID
      WHERE (P.NUMERODOCUMENTO = PI_NUMERODOCUMENTO) AND
           (P.PRIMERNOMBRE = PI_PRIMERNOMBRE OR P.PRIMERNOMBRE IS NULL) AND
           (P.SEGUNDONOMBRE = PI_SEGUNDONOMBRE OR P.SEGUNDONOMBRE IS NULL) AND
           (P.PRIMERAPELLIDO = PI_PRIMERAPELLIDO OR P.PRIMERAPELLIDO IS NULL) AND
           (P.SEGUNDOAPELLIDO = PI_SEGUNDOAPELLIDO OR P.SEGUNDOAPELLIDO IS NULL);
            
  END;

  PROCEDURE sp_PersonasBorrar(pi_IdPersona IN NUMBER, pi_IdPersonaOrg IN NUMBER, po_Cursor OUT SYS_REFCURSOR) IS
    V_CONTEO NUMBER;
  BEGIN
    -- Tablas dependientes
    INSERT INTO TBREGISTROS_PERSONAS
    SELECT * FROM TBREGISTROS_PERSONAS WHERE ID_PERSONA = PI_IDPERSONA;
    
    UPDATE TBREGISTROS_PERSONAS SET ID_PERSONA = PI_IDPERSONAORG
    WHERE ID_PERSONA = PI_IDPERSONA;
    
    INSERT INTO TBTUTOR
    SELECT * FROM TBTUTOR WHERE ID_PERSONA = PI_IDPERSONA;
    
    UPDATE TBTUTOR SET ID_PERSONA = PI_IDPERSONAORG
    WHERE ID_PERSONA = PI_IDPERSONA;
    
    INSERT INTO TBPERSONA_FONETICA
    SELECT * FROM TBPERSONA_FONETICA WHERE ID_PERSONA = PI_IDPERSONA;
    
    --UPDATE TBPERSONA_FONETICA SET ID_PERSONA = PI_IDPERSONAORG
    --WHERE ID_PERSONA = PI_IDPERSONA;
    
    SELECT COUNT(ID_PERSONA) INTO V_CONTEO FROM TBPERSONA_FONETICA WHERE ID_PERSONA = PI_IDPERSONAORG;
    IF V_CONTEO = 0 THEN
      UPDATE TBPERSONA_FONETICA SET ID_PERSONA = PI_IDPERSONAORG
      WHERE ID_PERSONA = PI_IDPERSONA;
    ELSE
      DELETE FROM TBPERSONA_FONETICA WHERE ID_PERSONA = PI_IDPERSONA;
    END IF;
    
    INSERT INTO TBAUDITORIA
    SELECT * FROM TBAUDITORIA WHERE ID_PERSONA = PI_IDPERSONA;
    
    UPDATE TBAUDITORIA SET ID_PERSONA = PI_IDPERSONAORG
    WHERE ID_PERSONA = PI_IDPERSONA;
    
    INSERT INTO TBPERSONAS
    SELECT * FROM TBPERSONAS WHERE ID = PI_IDPERSONA;
    
    DELETE FROM TBPERSONAS WHERE ID = PI_IDPERSONA;
    
    OPEN PO_CURSOR FOR
      SELECT P.ID IDPERSONA,
            P.PRIMERNOMBRE,
            P.SEGUNDONOMBRE,
            P.PRIMERAPELLIDO,
            P.SEGUNDOAPELLIDO,
            P.PARAM_TIPODOCUMENTO,
            P.NUMERODOCUMENTO,
            P.PARAM_ESTADOCIVIL,
            P.PARAM_GENERO,
            P.PARAM_MINORIAETNICA,
            P.GESTANTE,
            P.PARAM_REGIMENSALUD,
            P.FECHANACIMIENTO,
            P.PARAM_ETNIAPERTENECE,
            P.PARAM_RESGUARDO,
            P.CUALETNIAOPUEBLO
      FROM TBPERSONAS P
      WHERE P.ID = PI_IDPERSONA;
  END;
  
  PROCEDURE sp_RegistrosPersonaIdCriterio(po_Cursor OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN po_Cursor FOR
      SELECT DCL.ID               AS ID_DECLARACION
           , DCL.NUMEROFORMULARIO AS NUMEROFORMULARIO
           , DCL.FECHADECLARACION AS FECHADECLARACION
           , PRS.ID               AS ID_PERSONA
           , PRS.PRIMERNOMBRE ||
             CASE WHEN PRS.SEGUNDONOMBRE   IS NULL THEN '' ELSE ' ' || PRS.SEGUNDONOMBRE   END ||
             CASE WHEN PRS.PRIMERAPELLIDO  IS NULL THEN '' ELSE ' ' || PRS.PRIMERAPELLIDO  END ||
             CASE WHEN PRS.SEGUNDOAPELLIDO IS NULL THEN '' ELSE ' ' || PRS.SEGUNDOAPELLIDO END AS NOMBRECOMPLETO
           , PRS.NUMERODOCUMENTO  AS NUMERODOCUMENTO
           , CONTEO               AS CANTIDADREGISTROS
           , CONTEOVALORADOS      AS CANTIDADREGISTROSVALORADOS
      FROM (SELECT R.ID_DECLARACION, R.ID_PERSONA, COUNT(R.ID) AS CONTEO, COUNT(V.ID) AS CONTEOVALORADOS
            FROM TBREGISTROS_PERSONAS R
            LEFT JOIN TBVAL_ANEXO_PERSONA V ON V.ID_REGPERSONA = R.ID
            GROUP BY R.ID_DECLARACION, R.ID_PERSONA HAVING COUNT(1) > 1) RGP
      INNER JOIN TBDECLARACIONES DCL ON DCL.ID = RGP.ID_DECLARACION
      INNER JOIN TBPERSONAS      PRS ON PRS.ID = RGP.ID_PERSONA
      ORDER BY CONTEO DESC;
  END;
  
  PROCEDURE sp_RegistrosPersonaIdRegistros(po_Cursor OUT SYS_REFCURSOR) IS
    TYPE DuplicateCriteriaArray IS VARRAY(100000) OF NumberKeyValuePair;
    REGPERSONACriteria         DuplicateCriteriaArray;
    REGPERSONAPersistedValues  StringKeyValueArray    := StringKeyValueArray();
    REGPERSONADeleteCandidates NumberArray            := NumberArray();
  BEGIN
    /* Retrieve the aforementioned criteria */
    SELECT NumberKeyValuePair(RGP.ID_DECLARACION, RGP.ID_PERSONA) BULK COLLECT INTO REGPERSONACriteria
    FROM TBREGISTROS_PERSONAS RGP
    GROUP BY RGP.ID_DECLARACION, RGP.ID_PERSONA HAVING COUNT(1) > 1
    ORDER BY RGP.ID_DECLARACION, RGP.ID_PERSONA;
    IF REGPERSONACriteria.Count > 0 THEN
      FOR i IN REGPERSONACriteria.First..REGPERSONACriteria.Last LOOP
        DECLARE
          REGPERSONACriteriaRegistries NumberArray;
        BEGIN
          /* Condition for keeping registries of a duplicate criteria are given by the order clause */
          SELECT RGP.ID BULK COLLECT INTO REGPERSONACriteriaRegistries
          FROM TBREGISTROS_PERSONAS RGP
          LEFT JOIN (SELECT ID_REGPERSONA, COUNT(1) AS CONTEO FROM TBREGPERSONASFIRMA
                     GROUP BY ID_REGPERSONA) RPF ON RPF.ID_REGPERSONA = RGP.ID
          LEFT JOIN (SELECT ID_REGPERSONA, COUNT(1) AS CONTEO FROM TBCORRECCION
                     GROUP BY ID_REGPERSONA) CRP ON CRP.ID_REGPERSONA = RGP.ID
          WHERE RGP.ID_DECLARACION = REGPERSONACriteria(i).Key
            AND RGP.ID_PERSONA     = REGPERSONACriteria(i).Value
            AND RGP.ID NOT IN (SELECT ID_REGPERSONA FROM TBVAL_ANEXO_PERSONA) /* Do not consider records in this table */
          ORDER BY NVL(CRP.CONTEO, 0) DESC, NVL(RPF.CONTEO, 0) DESC;
          /* Append to delete candidates */
          IF REGPERSONACriteriaRegistries.Count > 0 THEN
            REGPERSONAPersistedValues.Extend();
            REGPERSONAPersistedValues(REGPERSONAPersistedValues.Count) := StringKeyValuePair(REGPERSONACriteria(i).Key || '-' || REGPERSONACriteria(i).Value, REGPERSONACriteriaRegistries(REGPERSONACriteriaRegistries.First));
            FOR j IN REGPERSONACriteriaRegistries.First..REGPERSONACriteriaRegistries.Last LOOP
              /* Skip first record */
              IF j <> REGPERSONACriteriaRegistries.First THEN
                REGPERSONADeleteCandidates.Extend();
                REGPERSONADeleteCandidates(REGPERSONADeleteCandidates.Count) := REGPERSONACriteriaRegistries(j);
              END IF;
            END LOOP;
          END IF;
        END;
      END LOOP;
    END IF;
    /* Display delete candidates using established collection */
    OPEN po_Cursor FOR
      SELECT RGP.ID_DECLARACION AS ID_DECLARACION
           , RGP.ID_PERSONA     AS ID_PERSONA
           , PSS.Value          AS ID_PERSISTIDO
           , RGP.ID             AS ID
           , NVL(RPC.CONTEO, 0) AS TBREGPERSONASCOMENTARIO
           , NVL(RPF.CONTEO, 0) AS TBREGPERSONASFIRMA
           , NVL(RPH.CONTEO, 0) AS TBREG_PERSONA_HECHOS
           , NVL(SNP.CONTEO, 0) AS TBSINIESTROS_PERSONA
           , NVL(VGP.CONTEO, 0) AS TBVALREG_PERSONA
           , NVL(CRP.CONTEO, 0) AS TBCORRECCION
      FROM TBREGISTROS_PERSONAS RGP
      LEFT JOIN (SELECT ID_REGPERSONA, COUNT(1) AS CONTEO FROM TBREGPERSONASCOMENTARIO
                 GROUP BY ID_REGPERSONA) RPC ON RPC.ID_REGPERSONA = RGP.ID
      LEFT JOIN (SELECT ID_REGPERSONA, COUNT(1) AS CONTEO FROM TBREGPERSONASFIRMA
                 GROUP BY ID_REGPERSONA) RPF ON RPF.ID_REGPERSONA = RGP.ID
      LEFT JOIN (SELECT ID_REGISTRO_PERSONA, COUNT(1) AS CONTEO FROM TBREG_PERSONA_HECHOS
                 GROUP BY ID_REGISTRO_PERSONA) RPH ON RPH.ID_REGISTRO_PERSONA = RGP.ID
      LEFT JOIN (SELECT ID_REGPERSONA, COUNT(1) AS CONTEO FROM TBSINIESTROS_PERSONA
                 GROUP BY ID_REGPERSONA) SNP ON SNP.ID_REGPERSONA = RGP.ID
      LEFT JOIN (SELECT ID_REGPERSONA, COUNT(1) AS CONTEO FROM TBVALREG_PERSONA
                 GROUP BY ID_REGPERSONA) VGP ON VGP.ID_REGPERSONA = RGP.ID
      LEFT JOIN (SELECT ID_REGPERSONA, COUNT(1) AS CONTEO FROM TBCORRECCION
                 GROUP BY ID_REGPERSONA) CRP ON CRP.ID_REGPERSONA = RGP.ID
      LEFT JOIN (SELECT Key, Value FROM TABLE(REGPERSONAPersistedValues)) PSS ON PSS.KEY = RGP.ID_DECLARACION || '-' || RGP.ID_PERSONA
      WHERE RGP.ID IN (SELECT * FROM TABLE(REGPERSONADeleteCandidates))
      ORDER BY RGP.ID_DECLARACION, RGP.ID_PERSONA, NVL(CRP.CONTEO, 0) DESC, NVL(RPF.CONTEO, 0) DESC;
  END;
  
  PROCEDURE sp_RegistrosPersonaBorrar(pi_IdRegistroPersona IN NUMBER, pi_IdRegistroPersonaOriginal IN NUMBER) IS
  BEGIN
    INSERT INTO TBREGPERSONASCOMENTARIO
      SELECT * FROM TBREGPERSONASCOMENTARIO WHERE ID_REGPERSONA = pi_IdRegistroPersona;  
    DELETE FROM TBREGPERSONASCOMENTARIO WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBREGPERSONASFIRMA
      SELECT * FROM TBREGPERSONASFIRMA WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBREGPERSONASFIRMA WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBREG_PERSONA_HECHOS
      SELECT * FROM TBREG_PERSONA_HECHOS WHERE ID_REGISTRO_PERSONA = pi_IdRegistroPersona;
    DELETE FROM TBREG_PERSONA_HECHOS WHERE ID_REGISTRO_PERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBVALREG_PERSONA
      SELECT * FROM TBVALREG_PERSONA WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBVALREG_PERSONA WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBCORRECCION
      SELECT * FROM TBCORRECCION WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBCORRECCION WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBDISCAPACIDAD_PERSONA
      SELECT * FROM TBDISCAPACIDAD_PERSONA WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBDISCAPACIDAD_PERSONA WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBDISCAPACIDADOTRO_PERSONA
      SELECT * FROM TBDISCAPACIDADOTRO_PERSONA WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBDISCAPACIDADOTRO_PERSONA WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBANEXO1
      SELECT * FROM TBANEXO1 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBBIEN_AFECTADO_A1 WHERE ID_A1 IN (SELECT ID FROM TBANEXO1 WHERE ID_REGPERSONA = pi_IdRegistroPersona);
    DELETE FROM TBANEXO1 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBANEXO2
      SELECT * FROM TBANEXO2 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBANEXO2 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBANEXO3
      SELECT * FROM TBANEXO3 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBANEXO3 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBANEXO4
      SELECT * FROM TBANEXO4 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBANEXO4 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    DECLARE
      Anexo5Ids NUMBERARRAY;
    BEGIN
      SELECT DISTINCT(A.ID) BULK COLLECT INTO Anexo5Ids FROM TBANEXO5 A
      INNER JOIN TBANEXO5_DESPLAZADOS D ON D.ID_ANEXO5 = A.ID
      WHERE D.ID_REGPERSONA = pi_IdRegistroPersona;
      IF Anexo5Ids.Count > 0 THEN
        INSERT INTO TBANEXO5
          SELECT * FROM TBANEXO5 WHERE ID IN (SELECT * FROM TABLE(Anexo5Ids));
        INSERT INTO TBANEXO5_DESPLAZADOS
          SELECT * FROM TBANEXO5_DESPLAZADOS WHERE ID_ANEXO5 IN (SELECT * FROM TABLE(Anexo5Ids));
        DELETE FROM TBANEXO5_DESPLAZADOS WHERE ID_ANEXO5 IN (SELECT * FROM TABLE(Anexo5Ids));
        DELETE FROM TBANEXO5 WHERE ID IN (SELECT * FROM TABLE(Anexo5Ids));
      END IF;
    END;
    
    INSERT INTO TBANEXO6
      SELECT * FROM TBANEXO6 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBANEXO6 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBANEXO7
      SELECT * FROM TBANEXO7 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBANEXO7 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBANEXO8
      SELECT * FROM TBANEXO8 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBANEXO8 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBANEXO9
      SELECT * FROM TBANEXO9 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBANEXO9 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    INSERT INTO TBANEXO10
      SELECT * FROM TBANEXO10 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBANEXO10 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    DECLARE
      Anexo11Ids NUMBERARRAY;
    BEGIN
      SELECT DISTINCT(A.ID) BULK COLLECT INTO Anexo11Ids FROM TBANEXO11 A
      INNER JOIN (SELECT I.ID_ANEXO11, I.ID_REGPERSONA FROM TBANEXO11_INMUEBLES I
                  UNION
                  SELECT M.ID_ANEXO11, M.ID_REGPERSONA FROM TBANEXO11_MUEBLES M) IM ON IM.ID_ANEXO11 = A.ID
      WHERE IM.ID_REGPERSONA = pi_IdRegistroPersona;
      
      IF Anexo11Ids.Count > 0 THEN
        INSERT INTO TBANEXO11
          SELECT * FROM TBANEXO11 WHERE ID IN (SELECT * FROM TABLE(Anexo11Ids));
        INSERT INTO TBANEXO11_INMUEBLES
          SELECT * FROM TBANEXO11_INMUEBLES WHERE ID_ANEXO11 IN (SELECT * FROM TABLE(Anexo11Ids));
        INSERT INTO TBANEXO11_MUEBLES
          SELECT * FROM TBANEXO11_MUEBLES WHERE ID_ANEXO11 IN (SELECT * FROM TABLE(Anexo11Ids));
        DELETE FROM TBANEXO11_INMUEBLES WHERE ID_ANEXO11 IN (SELECT * FROM TABLE(Anexo11Ids));
        DELETE FROM TBANEXO11_MUEBLES WHERE ID_ANEXO11 IN (SELECT * FROM TABLE(Anexo11Ids));
        DELETE FROM TBANEXO11 WHERE ID IN (SELECT * FROM TABLE(Anexo11Ids));
      END IF;
    END;
    
    INSERT INTO TBANEXO13
      SELECT * FROM TBANEXO13 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    DELETE FROM TBANEXO13 WHERE ID_REGPERSONA = pi_IdRegistroPersona;
    
    /* Siniestros. Cada anexo (de cada familiar) puede estar apuntando a un siniestro eliminable.
       Si no es posible eliminar individualmente, actualizar al registro no eliminable
     */
    DECLARE
      MultipleReferenceSiniestro EXCEPTION;
      PRAGMA EXCEPTION_INIT (MultipleReferenceSiniestro, -2292);
      SiniestroIds NUMBERARRAY;
    BEGIN
      SELECT ID BULK COLLECT INTO SiniestroIds FROM TBSINIESTROS_PERSONA WHERE ID_REGPERSONA = pi_IdRegistroPersona;
      IF SiniestroIds.Count > 0 THEN
        INSERT INTO TBSINIESTROS_PERSONA
          SELECT * FROM TBSINIESTROS_PERSONA WHERE ID IN (SELECT * FROM TABLE(SiniestroIds));
        FOR s IN SiniestroIds.First..SiniestroIds.Last LOOP
          BEGIN
            DELETE FROM TBSINIESTROS_PERSONA WHERE ID = SiniestroIds(s);
          EXCEPTION WHEN MultipleReferenceSiniestro THEN
            UPDATE TBSINIESTROS_PERSONA SET ID_REGPERSONA = pi_IdRegistroPersonaOriginal WHERE ID = SiniestroIds(s);
          END;
        END LOOP;
      END IF;
    END;
    
    INSERT INTO TBREGISTROS_PERSONAS
      SELECT * FROM TBREGISTROS_PERSONAS WHERE ID = pi_IdRegistroPersona;
      
    DELETE FROM TBREGISTROS_PERSONAS WHERE ID = pi_IdRegistroPersona;
  END;

END PKG_DUPLICADOS;
/
