-- Create new package
create or replace PACKAGE PKG_CRITICAN AS

  TYPE CURSOR_TYPE IS REF CURSOR;
  ROLCRITICA    NUMBER := 1011;
  ESTADOCRITICA NUMBER := 10015;
  DECLA_PENDE_DEVOL NUMBER := 10024;
  RADICADO_PENDIENTE_CAPTURA NUMBER := 704;
  ROL_LIDER_DEVOLUCION NUMBER := 1013;
  ROL_DIGITADOR NUMBER := 90;
  
  /*	DESCRIPCION: INSERTA LAS RESPUESTAS A LAS VALIDACIONES DE CRITICA N. CUANDO HAYA TERMINADO LAS
      INSERCIONES GUARDA EL RESULTADO.
  **	AUTOR: 
  **	FECHA: 
  **	CAMBIOS:
  **		20121128 - JAIRO VALDERRAMA
  **		1. V_Result ERA COMPARADO CON EL NUMERO DE INSERCIONES HECHAS SOBRE LA TABLA TBRADICACRITICAN
  **    CON UN OPERADOR LOGICO '>' Y NO CON '=' POR LO TANTO UNICAMENTE SE REALIZABA EL GUARDADO
  **    CUANDO SE VOLVIA A REALIZAR LAS VALIDACIONES DE CRITICA SOBRE EL APLICATIVO LO QUE INSERTABA
  **    CINCO VECES MAS EN EL HISTORIAL DE LA DECLARACION Y GENERABA LOS DUPLICADOS EN LA LISTA DE TAREAS
  */
  PROCEDURE SP_INSERTACRITICA (
                               PI_IDCRITICAN  VARCHAR,
                               PI_RESPUESTA  VARCHAR,
                               PI_IDUSUARIO  NUMBER,
                               PI_IDRADICACION  NUMBER,
                               PI_OBSERVACIONCRITICAN VARCHAR2 DEFAULT NULL                         
                              );

  /*	DESCRIPCION: GUARDA EL RESULTADO DE LA VALIDACION
  **	AUTOR: 
  **	FECHA: 
  **	CAMBIOS:
  **		20121129 - JAIRO VALDERRAMA
  **		1. SE ELIMINA LA ACTUALIZACION QUE SE ESTABA REALIZANDO A LA DECLARACION
  **    LA CUAL LA DEJABA EN PENDIENTE POR DEVOLUCION EN CASO TAL QUE NO PASARA
  **    TODAS LAS VALIDACIONES. ESTO DEBO A QUE LA SOLICITUD DE LA DEVOLUCION SE
  **    HACE CONSUMIENDO EL SERVICIO.
  */
  PROCEDURE SP_GUARDARESULTADO (
                                PI_IDRADICACION  NUMBER
                               );

  /* Obtiene el n煤mero de cr铆ticas que pasa una radicaci贸n determinada */
  FUNCTION FT_CUMPLECONCRITICA (
                                V_IDRADICACION  NUMBER
                               ) return number;
 /* Asigna la critica a un usuario */
  PROCEDURE SP_ASIGNACRITICA(PI_IDDECLARACION  NUMBER);
  
 /*Carga la imagen asociada a una radicacion*/
  PROCEDURE SP_CARGAIMAGENCRITICAN(
                                PI_IDRADICACION  NUMBER, 
                                PO_RUTAIMAGEN OUT VARCHAR
                               );
END PKG_CRITICAN;
/

-- Create package body
create or replace PACKAGE BODY PKG_CRITICAN AS

    ERRORINSERTACRITICA EXCEPTION;
    
  /* Inserta el resultado de cada pregunta de cr铆tica para una radicaci贸n */
  PROCEDURE SP_INSERTACRITICA(
                               PI_IDCRITICAN  IN VARCHAR,
                               PI_RESPUESTA  IN VARCHAR,
                               PI_IDUSUARIO  NUMBER,
                               PI_IDRADICACION  NUMBER,
                               PI_OBSERVACIONCRITICAN VARCHAR2 DEFAULT NULL                           
                             ) is
    V_ID NUMBER := 0;
    V_RESULT NUMBER :=0;
    NUMEROCRITICAS NUMBER :=0;
    
    V_IDCRITICAS  PKG_COMMON.STRING_ARRAY;
    V_RESPUESTAS  PKG_COMMON.STRING_ARRAY;
    
    --ERRORGENERICO EXCEPTION;
    
  BEGIN
    
      V_IDCRITICAS := PKG_COMMON.SPLIT_STRING(PI_IDCRITICAN);
      V_RESPUESTAS := PKG_COMMON.SPLIT_STRING(PI_RESPUESTA);
    
      IF V_IDCRITICAS.COUNT > 0 THEN
        FOR I IN 1..V_IDCRITICAS.COUNT LOOP
        
          V_ID:=SEQ_RADICA_CRITICAN.NEXTVAL;
        
          INSERT INTO TBRADICACRITICAN
            (ID, 
             ID_RADICACION, 
             ID_CRITICAN, 
             RESPUESTA, 
             ID_USUARIO)
          VALUES
            (V_ID, 
             PI_IDRADICACION, 
             V_IDCRITICAS(I), 
             V_RESPUESTAS(I), 
             PI_IDUSUARIO);
          
        END LOOP;
      END IF;
      
      SELECT COUNT(1) INTO V_Result
      FROM TBRADICACRITICAN RC 
      INNER JOIN TBCRITICAN CN ON RC.ID_CRITICAN = CN.ID
      WHERE RC.ID_RADICACION = PI_IDRADICACION;
      
      SELECT COUNT(1) INTO NUMEROCRITICAS FROM TBCRITICAN;
      
      IF V_Result >= NUMEROCRITICAS THEN
        PKG_CRITICAN.SP_GUARDARESULTADO(PI_IDRADICACION);
      ELSE
        RAISE ERRORINSERTACRITICA;
      END IF;
      
      EXCEPTION
        WHEN ERRORINSERTACRITICA THEN
          RAISE_APPLICATION_ERROR(-20000, 'Ocurri贸 un error en DB insertando la cr铆tica');

  END;
  
  /* Cuenta el numero de respuestas y de acuerdo a esto establece el resultado de la critica */
  PROCEDURE SP_GUARDARESULTADO (PI_IDRADICACION  NUMBER) IS
    RESULTADO      NUMBER;
    NUMEROCRITICAS INT;
    V_ID_DECLARACION              NUMBER;
    V_ID_USUARIO                  NUMBER;
  BEGIN
    SELECT COUNT(1) INTO NUMEROCRITICAS FROM TBCRITICAN;
    RESULTADO:= PKG_CRITICAN.FT_CUMPLECONCRITICA(PI_IDRADICACION);
    IF RESULTADO < NUMEROCRITICAS THEN
      UPDATE TBRADICACION R SET R.RESULTADOCRITICA = 0 WHERE R.ID = PI_IDRADICACION;
      --UPDATE TBDECLARACIONES D SET D.PARAM_ESTADO = 10024 WHERE D.ID = (SELECT R.ID_DECLARACION FROM TBRADICACION R WHERE R.ID = PI_IDRADICACION);
    ELSE
      UPDATE TBRADICACION R SET R.RESULTADOCRITICA = 1 WHERE R.ID = PI_IDRADICACION;
      SELECT R.ID_DECLARACION INTO V_ID_DECLARACION FROM TBRADICACION R WHERE R.ID = PI_IDRADICACION;        
      IF (V_ID_DECLARACION IS NOT NULL) THEN
          V_ID_USUARIO := pkg_common.F_USUARIOMENOSCARGA(ROL_DIGITADOR);
        IF (V_ID_USUARIO IS NOT NULL) THEN
          PKG_COMMON.SP_UPDESTADO_DECLARACION(V_ID_DECLARACION, V_ID_USUARIO, RADICADO_PENDIENTE_CAPTURA);
        ELSE
          RAISE ERRORINSERTACRITICA;
        END IF;
      ELSE
        RAISE ERRORINSERTACRITICA;
      END IF;
      --UPDATE TBDECLARACIONES D SET D.PARAM_ESTADO = 704 WHERE D.ID = (SELECT R.ID_DECLARACION FROM TBRADICACION R WHERE R.ID = PI_IDRADICACION);
    END IF;
    
    EXCEPTION
      WHEN ERRORINSERTACRITICA THEN
        RAISE_APPLICATION_ERROR(-20000, 'Ocurri贸 un error en DB insertando la cr铆tica');
  END;
  
  /* Asigna CRITICA A UN USUARIO */
  PROCEDURE SP_ASIGNACRITICA(PI_IDDECLARACION  NUMBER) IS
    ID_USUARIOASIGNADO NUMBER;
  BEGIN      
    ID_USUARIOASIGNADO := PKG_Common.F_USUARIOMENOSCARGA(ROLCRITICA);
    PKG_COMMON.SP_UPDESTADO_DECLARACION(PI_IDDECLARACION,ID_USUARIOASIGNADO,ESTADOCRITICA);           
  END;

  /* Obtiene el n鷐ero de cr韙icas que pasa una radicaci髇 determinada */
  FUNCTION FT_CUMPLECONCRITICA (
                                V_IDRADICACION NUMBER
                               ) RETURN NUMBER IS 
                              
    V_Result NUMBER;
  BEGIN
    SELECT COUNT(1) INTO V_Result
    FROM TBRADICACRITICAN RC 
    INNER JOIN TBCRITICAN CN ON RC.ID_CRITICAN = CN.ID
    WHERE RC.ID_RADICACION = V_IDRADICACION
    AND RC.RESPUESTA = 1;
    RETURN V_Result;
  END;
  
 /*Carga la imagen asociada a una radicacion*/ 
  PROCEDURE SP_CARGAIMAGENCRITICAN(
                                PI_IDRADICACION  NUMBER, 
                                PO_RUTAIMAGEN OUT VARCHAR
                               ) IS
  BEGIN
    SELECT R.RUTAIMAGEN INTO PO_RUTAIMAGEN FROM TBRADICACION R WHERE R.ID = PI_IDRADICACION;
  END;

END PKG_CRITICAN;
/