-- Create new package
create or replace PACKAGE PKG_GLOSAS AS

   ROLGLOSAS NUMBER := 1008;
   ESTADOGLOSA NUMBER:= 10011;

PROCEDURE SP_ASIGNAGLOSA(PI_IDDECLARACION IN NUMBER);

END PKG_GLOSAS;
/

-- Create package body
create or replace PACKAGE BODY PKG_GLOSAS AS
  PROCEDURE SP_ASIGNAGLOSA(PI_IDDECLARACION IN NUMBER) IS
  ID_USUARIOASIGNADO NUMBER;
  BEGIN
     ID_USUARIOASIGNADO := PKG_COMMON.F_USUARIOMENOSCARGA(ROLGLOSAS);
     PKG_COMMON.SP_UPDESTADO_DECLARACION(PI_IDDECLARACION,ID_USUARIOASIGNADO,PKG_GLOSAS.ESTADOGLOSA);
  END;
END PKG_GLOSAS;
/
